### ISSUE TITLE
Improve style of chat window

### ISSUE THREAD

**Issue by devdan** [wireapp/wire-android#260] opened 2016-10-21 08:00 UTC
I'm used to the chat style of other apps like Signal, Conversations, Threema and the SMS app where you have bubbles around the messages with different colors pointing to different sides of the screen, messages from others on the left side, own messages on the right side. 

This improves readability a lot.

Looking at the uninflected chat window  in Wire always irritates me and lets me stop for a while to understand who wrote which messages, because I have to read the names first.

Feature proposal: Adapt the standard style of all the other messengers or make it at least optional.

**Comment by someoneEsle** [comment] 2016-10-21 13:53
Duplicate of #192

**Comment by bjoernherbig** [comment] 2016-10-24 16:40
closing as duplicate

**Closed by bjoernherbig** 2016-10-24 16:40 UTC
