### ISSUE TITLE
Missed messages

### ISSUE THREAD

**Issue by Da0012** [wireapp/wire-android#1556] opened 2018-05-03 03:17 UTC
## The problem

I sent one message yesterday and another today, but it didn't reach to friend's smart phone or her desktop application.
Yesterday message was send from my smartphone and today message was send from my desktop.
Wire shows delivered tag on my smartphone.
Those messages are on my devices.

## Environment

* Wire version that exhibits the issue: desktop 3.0.2816 and android 3.10.439
* Last Wire version that did not exhibit the issue (if applicable):
* Android OS version used to run Wire: ubuntu 17.10, android 6
* Is this a custom firmware or a stock one:
* Mobile phone model/manufacturer:
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi

## Details

Describe the steps necessary to reproduce the problem in more details. The detailed description
will help us to fix the issue faster.

## Link to Debug logs

Create a [GIST](https://gist.github.com) which is a paste of your Wire logs, and link them here.
It is recommended to directly contact our [customer support](mailto:support@wire.com) and send the debug report by email, because it can potentially contain some private information, that you don't want to share to the public.

## How to send detailed debug report from Wire:

1. Go to Settings -> About
2. Tap "Wire swiss GmbH" 10 times
3. Reproduce your issue
4. Send the report from Settings -> Advanced -> Submit debug report
5. Go to Settings -> About
6. Tap "Wire swiss GmbH" 10 times again to disable detailed debug reports, because this slows down Wire

## Screenshots

Please attach screenshots if you consider them as helpful to understand/reproduce the issue

**Comment by Da0012** [comment] 2018-05-04 02:42
today, we lost two adjacent messages

**Comment by Da0012** [comment] 2018-05-07 03:51
today, we lost three adjacent messages again

**Comment by someoneEsle** [comment] 2018-05-07 08:02
Can you reproduce this bug consistently?

**Comment by Da0012** [comment] 2018-05-08 23:43
yesterday, we lost one message :/
this time she used LTE
i can't reproduce that bug, it is random.

**Comment by Da0012** [comment] 2018-05-10 05:50
10+ message lost :(
what happend?
I like wire,This is a very serious problem.

**Comment by someoneEsle** [comment] 2018-05-11 06:44
What phone is she on? If it only happens with her it's probably a bug on her side

**Comment by Da0012** [comment] 2018-05-11 15:52
yes and not, the messages don't reach her smartphone or her computer.

**Comment by Da0012** [comment] 2018-05-11 15:59
yes and not, the messages don't reach her smartphone or her computer.

**Comment by someoneEsle** [comment] 2018-05-14 07:34
Are her phone and computer on the same network when this happens?

**Comment by Da0012** [comment] 2018-05-15 01:12
almost always,
But she one time used smartphone with LTE, and her computer was offline.
and two messages didn't reach both devices.

**Comment by Da0012** [comment] 2018-06-20 04:39
Hi
¿You guys were able to fix this bug?
or do you have any news about it?

**Comment by Da0012** [comment] 2018-06-21 20:48
the problem persists,
i will send a debug log

**Comment by someoneEsle** [comment] 2018-06-29 15:04
Do you have this bug with anybody else?

**Comment by Da0012** [comment] 2018-06-29 15:15
I think so

**Comment by Da0012** [comment] 2018-06-29 15:23
she log out all her devices, and relogin, and the new messages appeared

**Comment by someoneEsle** [comment] 2018-07-02 09:22
It would be very useful if you could contact support and send the logs from all of her devices which are not receiving any messages

**Comment by Da0012** [comment] 2018-07-06 20:11
i sent two debug log,because the bug persists.
The problem occurs on android and desktop.

**Comment by Da0012** [comment] 2018-07-06 23:29
3.12.623 
The messages delays but it appears

**Comment by Da0012** [comment] 2018-07-09 16:29
3.13.625
I don't think messages get lost.
but some of them take more than an hour to appear.

**Comment by Da0012** [comment] 2018-07-10 01:36
3.13.625
I don't think messages get lost.
but some of them take more than an hour to appear.

i sent two photos and She got those photos 30 minutes later on desktop windows,android smartphone off.The problem exists on desktop windows, the problem is unidirectional.
All messages are on my devices.
Please fix this quickly. I've been dealing with this problem for months.
The problem is't of android,is on android and desktop. I don't want to have to change platforms,
but this generates discontent and frustration..

**Comment by Da0012** [comment] 2018-08-07 04:59
Yes wire fails bidirectionally.
on this Messengers the messages mark delivered,etc.

**Comment by marcoconti83** [comment] 2019-02-13 12:07
Hi @Da0012 ,
can you confirm that this is still a problem for you? I'm a bit puzzled by your comment:

> I'm not using wire often lately.
> But i notice this problem on Signal,telegram and Wpp
> i don't understand what happend.

Are you having this issue on other applications too? Then we should start to think about the phone (maybe the storage is full, or faulty...)

**Comment by makingthematrix** [comment] 2020-03-25 11:56
I'm going to close this ticket as I can't reproduce the bug. Please reopen if it happens again.

**Closed by makingthematrix** 2020-03-25 11:56 UTC
Labels: bug
