### ISSUE TITLE
Video/audio call issue

### ISSUE THREAD

**Issue by ogiright123** [wireapp/wire-android#1499] opened 2018-03-24 08:52 UTC
## The problem

I built branch release repo successfully.
App runs but when i start  audio/video calling,  app is crashed.
how does it fix?

## Environment
* Wire version                  latest branch release
* android studio 2.3.2 gradle version 1.5.0
* Android OS  is   android 6.0
* Mobile phone model/manufacturer:                samsung galaxy s5
* Mobile network type (EDGE/LTE/Wi-Fi/Offline):  wifi

**Comment by someoneEsle** [comment] 2018-03-27 11:41
duplicate of #1481

**Closed by someoneEsle** 2018-03-27 11:41 UTC
Labels: bug

**Comment by hub-ch** [comment] 2019-02-17 05:08
https://github.com/wireapp/wire-android/issues/1892
