### ISSUE TITLE
Pictures not being loaded on receiver's side

### ISSUE THREAD

**Issue by wireusr** [wireapp/wire-android#612] opened 2017-02-16 14:49 UTC
Pictures sent to somebody else are not loaded on the receiver's side, even though sender has “delivered” status. Workaround for this is to try to “save it”, then it brings-up photo onto display (re-downloading it). It looks like after getting app back online (from offline) it simply does not retrieve photo from the server. It works 90% of the time (in rare cases fails) if both sender & receiver are both online at the same time.

**Comment by someoneEsle** [comment] 2017-02-16 15:30
duplicate of #220 ?

**Comment by xuanzhaopeng** [comment] 2017-02-21 16:45
I received several clients reported the similar issues.  But unfortunately I cannot reproduce it.

Could u kindly provide following information:
1) Wire version AND Android version that used in sender and receiver
2) Does sender or receiver login on multiple devices during this operation
3) Does sender and receiver both are in Android 
4) Does sender and receiver both have Google Service

Thanks

**Comment by wireusr** [comment] 2017-02-21 20:28
1. wireapp 2.27.314 installed through google play, N.7.1.1
2. no
3. yes
4. yes

**Comment by DrAxelbauer** [comment] 2017-02-28 13:21
Same here ...aleady sent to support an android 4.2 devices ver. 2.28

**Comment by makingthematrix** [comment] 2020-02-20 13:47
The assets were rewritten completely since this issue was opened. I guess I can close this. Please reopen or create a new one if the problem is still happening.

**Closed by makingthematrix** 2020-02-20 13:47 UTC
Labels: bug
