### ISSUE TITLE
Messages fail to send after switching between mobile and wifi

### ISSUE THREAD

**Issue by stinsonga** [wireapp/wire-android#1500] opened 2018-03-25 04:23 UTC
Wire version: latest
Android version: 8.0.0
Device: OnePlus 5

This is a long-standing issue for me with the Android version of Wire:

The app, freshly-installed, works normally. However, once I move from WiFi to using mobile data (or back to WiFi), the app becomes unusable: messages perpetually fail to send, nor do I receive new messages. During this, a red line appears at the top of the screen, which looks like a progress bar.

Killing the app and restarting does not solve the issue. The red progress bar inevitably comes back shortly after opening a conversation. The only solution seems to be a complete uninstall and reinstall.

**Comment by someoneEsle** [comment] 2018-03-26 11:40
Hi, could you elaborate more on how the bug works? For example, you open the app while on data, switch to wifi, and then you cannot send/receive anything?
Does the same happen if you open the app while on wifi and then switch to data? Are you sure that the issue is related to network switching, and not to either wifi or 4g not working at all?

**Comment by makingthematrix** [comment] 2020-05-07 12:01
I think I can close this issue now? I remember having this bug but it was gone some time ago after changes to websockets and the http client.

**Closed by makingthematrix** 2020-05-07 12:01 UTC
Labels: bug
