### ISSUE TITLE
add landscape orientation for conversations

### ISSUE THREAD

**Issue by madprogger** [wireapp/wire-android#455] opened 2017-01-09 14:48 UTC
Currently, the app only supports portait mode. This makes writing large texts in conversations hard, especially on compact (up to 5") devices.
Please support landscape mode for entering text, as every other messaging app does.

Wire: 2.24.303
Android: 5.1.1
Device: Sony Xperia Z1 Compact

**Comment by someoneEsle** [comment] 2017-01-09 17:49
duplicate of #78

**Comment by h5rdly** [comment] 2017-01-19 17:40
#78 is closed, and the reluctance to support landscape mode on an otherwise good app is baffling. The reason given is design overhead, which is again baffling, given that Android supports relative resizing to allow this adaptation painlessly-  
https://developer.android.com/training/multiscreen/screensizes.html

I have little means pitching Wire at its current state. How does one explain no landscape mode on a messaging app?

**Comment by jullit31** [comment] 2017-09-23 15:52
Not only is it bad for typing, also viewing landscape images is a real pain...
When looking through the wire-android issues, imho this one is *the* most important missing feature right now. Wire-android completely ignoring the device orientation (see also #892) really breaks it.

**Comment by dns2utf8** [comment] 2017-11-15 14:14
I second that. Please add it.

**Comment by thefierybreeze** [comment] 2017-12-20 12:50
I made an account just to report this incovienience, especially since the app can work in landscape mode with the use of third party landscape forcing apps like spin n go from f-droid

**Comment by rdb** [comment] 2018-02-23 21:58
Could this receive developer attention?  This issue makes Wire unusable on Android laptops without use of thirdparty apps to force Wire into landscape mode.

**Comment by FeepingCreature** [comment] 2018-04-01 17:24
I have the same issue.

**Comment by xalmat** [comment] 2018-08-11 14:08
The fact that Wire does not allow landscape orientation is exactly why I don't use Wire. I would call this a bug that needs fixed, not just a feature request.

**Comment by FeepingCreature** [comment] 2018-08-13 13:17
When recommending the app to my parents, I literally had to install an Android hack to forcibly permit landscape mode. To use on a tablet? You know, the Android device that is in landscape mode _by default_?

**Comment by svaens** [comment] 2018-10-03 08:48
@FeepingCreature
Do you know if Wires means of handling device rotation can explain my problem: Trying to Wire video talk with mother, and we are unable to see each other in same orientation. I.e., if i see her upright, she sees my head sideways. And visa versa. Difficult for me to troubleshoot as she's not so tech savvy, and 3000km away.
I've got a Samsung galaxy s3, and she got an older Samsung tablet of some sort...

**Comment by xalmat** [comment] 2018-10-03 11:50
On 10/3/18 1:48 AM, svaens wrote:
> @FeepingCreature <https://github.com/FeepingCreature>
> Do you know if Wires means of handling device rotation can explain my
> problem: Trying to Wire video talk with mother, and we are unable to see
> each other in same orientation. I.e., if i see her upright, she sees my
> head sideways. And visa versa. Difficult for me to troubleshoot as she's
> not so tech savvy, and 3000km away.
> I've got a Samsung galaxy s3, and she got an older Samsung tablet of
> some sort...

Yes, that is exactly the problem, and the reason that Wire needs to
handle device rotation.

**Comment by Hypnosii** [comment] 2019-12-25 20:04
This is not a feature, it's a major flaw in the app. No idea why this is not taken up in priority as it is a major handicap for its adoption

**Comment by makingthematrix** [comment] 2020-01-09 16:54
@Hypnosii  We experimented with the landscape mode in the past but the sheer number of issues it created convinced us to drop it. Currently there are no plans to try it again. We may consider it in the future, after we move the architecture to Kotlin, but I can't promise anything.

**Comment by XenGi** [comment] 2020-01-21 10:52
@makingthematrix Can you explain what problems you had? Maybe the community can help you with that.
I just bought a F(x)tec Pro1 (smartphone with hardware keyboard) and was hoping to switch back to wire and finally type without a damn touchscreen. Don't tell me I have to stick with buggy signal just for the landscape mode? It shouldn't be that hard. Wire is the only messaging app that doesn't support it. You could at least give us a experimental toggle in the app and let us give you feedback on what works and what doesn't.

**Comment by makingthematrix** [comment] 2020-01-22 10:11
@XenGi There were some design decisions made a long time ago which can't be reverted without rewriting a lot of code. Actually, we are rewriting the code, but we are a small team. It will take time, and the landscape mode is not our priority.

**Comment by XenGi** [comment] 2020-01-22 14:04
Nevermind, I just read about your move to a US based company. So wire is basically dead to me. The last privacy aware messaging system that is left that fits my needs is jabber/xmpp then.

See tweet and followups: https://twitter.com/brokep/status/1194392575442067456

**Comment by makingthematrix** [comment] 2020-01-29 14:10
We didn't move to US.

**Comment by android10** [comment] 2020-01-30 10:52
Hey everyone, just jumping in to make a couple of things more clear. First of all thanks for taking your time and suggesting new features. 

Regarding landscape mode, we are basically refactoring/rewriting the app and it is something we have in our roadmap, but due to priorities, some internal coupling and legacy code based on some architectural design decisions, we need to address other problems before:

- Introduce our new architecture based on clean architecture written in Kotlin, which involves:
    **1- Restructure Data Layer**
    **2- Restructure Domain Layer**
    **3- Refactor UI**

Currently because of Scala and its ecosystem around android, it makes a bit difficult to do achieve all these challenges in a fast way. 

We listen to you and the community, and that is why we make everything transparent and open source. You can check the progress on the codebase and keep track of the changes. 

Any suggestion and pull requests are more than welcome. 

Related our move to the US, this is something out of our hands (Engineering) but if you check the documentation on how Wire works, there is no impact on the privacy since we cannot decrypt/see any messages, that is end to end encryption that happens at a client level, so the data is totally safe and only users can access to it. 

There is way more to understand and it is hard to explain it here, but here is further documentation:
https://wire-docs.wire.com/download/Wire+Security+Whitepaper.pdf

@XenGi no one is forcing anyone to use Wire of course and constructive feedback and politeness is always more than appreciated it.

**Comment by FeepingCreature** [comment] 2020-01-30 12:54
Okay, but here's the part that I don't understand.

The app works fine if I just *force* it to widescreen using an Android hack.

So whatever the app is doing to prevent itself from being put into widescreen, why can't it just stop doing that?

**Comment by android10** [comment] 2020-01-30 14:36
@FeepingCreature there is way more than that. Maybe you can send a video or something to help us?

Android recreates activities when configuration changes (in this case from Portrait to Landscape). if you do not handle correctly garbage collection and you rotate the screen several times, the app is going to freeze, because it is retaining all these references. That leads to a lot of problems and as I said, it requires a big refactor, something we are working on. 

@FeepingCreature also feel free to contribute by sending a PR, that is more than welcome. Complaining via chat is easy, we are doing our best to make Wire a robust Messaging Platform and that is why we also decided to open everything we are doing.

**Comment by FeepingCreature** [comment] 2020-01-30 14:37
I see what you mean, but ... if the application is *started* in landscape mode, then why not stay in landscape mode and lock it in that mode? That way you would bypass the GC cost from changing state but still support the tablet usecase.

**Comment by android10** [comment] 2020-01-30 14:41
@FeepingCreature that the expected feedback we are looking for. Maybe that could be an option to setup a default mode when the app starts. This is something to consider, although I cannot promise that, I have to say that this functionality is definitely in our road map. 

BTW, I'm curious about how you are forcing landscape mode :)

**Comment by Hypnosii** [comment] 2020-01-30 14:47
@android10 I confirm the feedback from @FeepingCreature ... I use RotationControl (https://www.phonearena.com/news/How-to-force-landscape-or-portrait-mode-in-apps-like-Instagram-and-others-Android_id78439) in order to force Wire to go on landscape. Although it sometimes has the undesirable side effect that picture show upside down

**Comment by madranet** [comment] 2020-02-28 18:19
There are a [metric tonne of apps](https://play.google.com/store/search?q=rotation%20control&c=apps) on the Google Play Store that will force a certain orientation on your phone. 

I've been using [control screen rotation](https://play.google.com/store/apps/details?id=ahapps.controlthescreenorientation) and, as with @FeepingCreature and @Hypnosii have not experienced any ill-effects when forcing Wire into landscape orientation.

I'm glad someone from the dev team has actually taken the time to explain *why* they  made the decision not to obey device orientation --even though we've got at least 3 people who've not had any problems when using Wire in landscape mode.  But, again as others have said; Why not allow the user to make the choice --maybe with a warning that landscape mode is not officially supported and may be buggy?  

For me the 3 most annoying features that any app can have are:

1: Require me to setup an account before I can even look at the interface
2: Prevent me from changing the font size to one I can actually read
3: Ignore my preference setting for screen orientation.

Wire currently has all three of those and only the first is in any way justifiable.

**Closed** 2020-05-07 11:26 UTC
Labels: enhancement

**Comment by FeepingCreature** [comment] 2020-05-07 11:35
Uh? This bug is not fixed. Why the close?

**Comment by Hypnosii** [comment] 2020-05-07 19:17
A sign perhaps of giving up on new feature development?
On May 7, 2020, at 17:05, madprogger <notifications@github.com<mailto:notifications@github.com>> wrote:

This and #1570<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwireapp%2Fwire-android%2Fissues%2F1570&data=02%7C01%7C%7C80cf94d1b8c6483f971d08d7f2a070ad%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637244643210879282&sdata=CFMLr9xQV7tF%2BcAUKjfJxsGYpBEJArpL801pq2zypQM%3D&reserved=0> were closed without comment.
That's sad.

**Comment by makingthematrix** [comment] 2020-05-08 13:51
Folks, we made comments about it many times in the past. 

The decision stands: we are a small team and so we have be very careful about priorities. We won't work on this feature (the way we see it, it's not a bug to be fixed, but a request for a feature) in the near future. We have no time and energy to spend on this. 

I closed this issue because we try to clean up the list of open issues so it's easier for us to focus.
