### ISSUE TITLE
Backup and restore conversation history not working

### ISSUE THREAD

**Issue by bugtopus** [wireapp/wire-android#2831] opened 2020-05-07 22:28 UTC
Hi,
When I backup the conversation history on the old phone and want to restore it on a newly added device it doesn't show the old history.

OS: Android 9 Pie / LineageOS 16.0 
Devices: Samsung Galaxy S5 and all other phones i tried
Wire: 3.47.909, 3.47.911, 3.48.914

Tried on multiple devices with different procedures.

When I put no password when attemting to backup the history there is a red error message that says: Password has to be min. 8 characters long, upper and lowercase, contain min. one digit and a special character. 

I can put two characters or eight digits or only a space and it will not complain about the input and creates the backup file. Looks to me like a bug. What format is really working as password? 

When i try to restore the backup:

1. With correct password format it doesn't work.
2. With 2 or 8 digits as password it doesn't work.
3. With a space as password it doesn't work.
(of course all the times the password corresponds to the backup)

It looks like with the space as password it has a different behaviour when restoring the conversation - all the contacts/conversations are shown in the main window - no archived ones. When trying with correct password format there are archived ones and there is not everywhere a: You are using this device now.

Other things:

I cannot restore old backups with no password from past year because it won't accept an empty password on newer versions. How would users restore old backups? Install old Wire restore backup and upgrade - where do they get old Wire?

I cannot create backups with empty password with newer versions (why no empty password - could be my decision :).

When I put the wrong password, when restoring, it didn't complain about that. How do I know for sure if the password was correct (yes when history is there again :) but what if there is a bug)?

Backup and restore was working on my device last august. Cannot remember which version of Wire it was. I didn't use password for the backup because it's protected by other encryption.

Thanks for the great Wire app :)

**Comment by bugtopus** [comment] 2020-05-08 17:07
Tryied again with Version 3.48.914 on the new phone. I got new device id but no history restored. After reboot of the phone I had a clone (same device id) of the device I backed up the history from (device still in use!) with visible history. So now I have two phones with the same device id. Using both together will not work - you know that!

Why is it not possible to restore only the history, merge multiple backups or use backups made on other platforms? Is that so hard to implement? Decrypt old database(s), create new one and encrypt again. Why there is no tool far that - what if I need data from lost history that is in an encrypted backup? It is not possible to load a Backup on a known device (device list) on Android without check out and registering again the device. 

The versions I download on https://wire.com/de/download/ are named wire-prod-release - may you should think twice what you put there and how you name it. (for me as personal user no problem - think about your pro users having trouble in business)

In the time I'm using wire I convinced at least 50 people to use it as an alternative for communication (that was hard work). For me it is not a proplem fiddling around with Wire for hours just to have a working new device with a history backup on it (if it's possible at all without altering other working devices) or other funny things. 

Others users (98%) incl. pro users  just say: Let's use Whats... (or whatever) again because Wire S#cks. They will never ever use it again because now they lost their data/patience. For a messenger the user base is crucial - who will use a messenger if he is the only one using it.
If you get $8.2M fund raise and loose confidence from user base for that hidden move towards supervision you should keep care on remaining users (use that money for new software engineers if you are short handed). There are less and less arguments to convince friends/new users of using wire. That colud lead to an "avalanche breakdown".

I still like the Wire app - rumours tell that not everyone thinks the same.

**Comment by tokariu** [comment] 2020-05-08 22:01
@bugtopus I came to a similar conclusion here: https://github.com/wireapp/wire-android/issues/2756#issuecomment-625919675

and I can confirm that this lately has changed the opinion of a lot of people, not just the nerds who used and struggled with Wire before.

However, don't get me wrong on this, I'd still like to see people prefering Wire over most of it's competitors. But the signs tend towards normal people going back to the big players and experienced users just waiting for an alternative to switch as soon as they are on par with the feature set.

**Comment by kausban** [comment] 2020-05-27 05:59
I reported this issue to support back in January and received the following response. They were aware of it then at least.

> Thanks for reaching out and sorry to hear about this issue!
> 
> We know about it and will be working on a fix as soon as possible. Apologies for the inconvenience in the meantime.
> 
> I will get back to you as soon as it is fixed

Concerned to learn its remains an open issue.
I really hope backup works on desktop. I have resigned to live with incomplete chat history on phone.

Note: I am paying user. With a small 5 person team we can probably tolerate these issues especially since we have little complaints elsewhere. But data is precious and backups being broken means we probably would look to switch to a different platform when we scale up.

**Comment by makingthematrix** [comment] 2020-06-03 10:12
@kausban : Sorry for that. We plan to rewrite the backup functionality. The current functionality proved to be too unreliable and our work on fixing it met with only partial success. Unfortunately, rewriting it will take some time.

**Comment by Christian-Git01** [comment] 2020-06-26 21:56
> @kausban : Sorry for that. We plan to rewrite the backup functionality. The current functionality proved to be too unreliable and our work on fixing it met with only partial success. Unfortunately, rewriting it will take some time.

Any ideas on when this will be released? Is backup going to be cross-plattform?

**Comment by BradleyWire** [comment] 2020-07-07 11:16
Hi, As an update: we have introduced the backup functionality rewrite into our current sprints. We don't have an hard ETA, however, we will update this issue when we know exact details.

**Comment by makingthematrix** [comment] 2020-09-16 09:14
Hi @bugtopus,
With the new release, 3.55, we finally have new backups functionality in place. Please try it out!

**Comment by kausban** [comment] 2020-09-17 13:24
> Hi @bugtopus, @kausban,
> With the new release, 3.55, we finally have new backups functionality in place. Please try it out!

Thanks for the fix and update. The apk is however not yet available to download on https://wire.com/en/download/.

**Comment by makingthematrix** [comment] 2020-09-18 13:54
@kausban We're having some problems with updating the webpage. Meanwhile you can download the APK from my unofficial archive: https://makingthematrix.github.io/Wire-Android-Archive/ .

**Closed** 2020-09-29 12:31 UTC
Labels: released

**Comment by muellert** [comment] 2021-03-20 21:41
I am trying to copy my conversation history to a new phone. So I made a backup on Wire Desktop and copied the file to the phone. But trying to restore there does not work, since the file is apparently password-protected. But I was never asked for a password to set, and also didn't find any elsewhere. What gives?
