### ISSUE TITLE
Photos dont load, I need help.

### ISSUE THREAD

**Issue by MeteorSkills** [wireapp/wire-android#3468] opened 2021-08-25 15:46 UTC
About 6 months ago I changed my cell phone and the photos I had in wire conversations cannot be seen, they do not load. They only load the last 10 of the conversation approximately.

**Comment by Gardosen** [comment] 2021-09-02 08:11
@makingthematrix  explained it very well, as this is not a bug, i will close this ticket.

Kind regards
Marco

**Closed by Gardosen** 2021-09-02 08:11 UTC
