### ISSUE TITLE
See my favorited (hearted) messages in a conversation

### ISSUE THREAD

**Issue by forteller** [wireapp/wire-android#787] opened 2017-04-12 01:06 UTC
The ability to heart messages seems a bit underutilized at the moment. It's nice to give a "thumbs up", but I find it very intuitive that the hearts should also function sort of like a favorite/bookmark button. A way to see just the messages that you've hearted in each separate chat/thread would IMHO be very useful and nice.

**Comment by someoneEsle** [comment] 2017-04-13 13:29
duplicate of #634

**Comment by ImAnnoying2** [comment] 2018-12-16 16:20
Please close this duplicate.

**Closed** 2018-12-17 13:32 UTC
Labels: enhancement
