### ISSUE TITLE
No notifications in Android while app is closed

### ISSUE THREAD

**Issue by dedaxys** [wireapp/wire-android#2127] opened 2019-05-09 16:55 UTC
Notifications of any type do not appear for Android users when the app is not open in the background (not visible in the Recent Apps view of the OS). Notifications appear as normal when the app is running or minimized.

**To Reproduce**
Have a user from any any device running Wire send a message to the Android user after the Android user has closed the app.

**Expected behavior**
Notifications of new messages, pings or incoming calls should appear without needing to open the app. This was working fine until app update a week or so ago.

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.32.781
- Android OS version used to run Wire: 9.0.0.256
- Is this a custom firmware or a stock one: stock
- Mobile phone model/manufacturer: Any Android mobile device
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi or data

**Additional context**
Further digging shows that the app is stopped as a background process when it is closed. New messages take a moment to appear when the app is opened.

**Comment by catinello** [comment] 2019-05-09 20:15
I can confirm this unfortunate behaviour since the update to 3.32.781.

Smartphone (please complete the following information):

- Wire version that exhibits the issue: 3.32.781
- Android OS version used to run Wire: Android Pie with latest security patches (5. May 2019)
- Is this a custom firmware or a stock one: stock
- Mobile phone model/manufacturer: Essential PH-1
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi or data

**Comment by IronJunkie** [comment] 2019-05-12 00:22
One other thing I've noted is if wifi/data has been turned off overnight & is turned on again in the morning notifications are then received.

I have same issue (Essential phone, same status as above except also running beta Google Play Services rev 17.1.22 Apr 30th update) Also it was present with April security patch (& might have worked properly for sometime after May security update as I did get one notification & thought it was fixed ... but can't be certain)

**Comment by DeWir3** [comment] 2019-05-15 14:08
I've been having the same issue for a few days now as well. I think it started with a Wire update, but cannot say for sure or with which one. Wire and Google Play Services are up to date and I haven't changed anything in battery settings or the like.

**Comment by charlag** [comment] 2019-05-15 15:44
Can confirm, Lineage OS with Oreo here, was working fine until the last update. Did GCM priority change? Does background service crash? I have Android experience (spoiler: I built SSE notification system for Tutanota) so if I can help you with debugging, please let me know.
I'll try to get logs first.

**Comment by CeryleRudis** [comment] 2019-05-16 05:53
Same issue here https://github.com/wireapp/wire/issues/269

I can confirm the same issue across android and ios.
Android 7 - 9, ios 12
App is closed, nothing comes through unless it is opened and only then do messages appear.

This is becoming quite a serious issue, we are already discussing changing from wire to something else.

**Comment by ganego** [comment] 2019-05-16 08:42
> I've been having the same issue for a few days now as well.   
More interestingly, WA has this problem with not giving me notifications for some weeks now. Just out of the blue, I did not update android (lol, updating android). I'm used to Wire not giving notifications anyway since I use it, but just found it curious that WA now has the same problem.

**Comment by alien2003** [comment] 2019-05-16 16:43
Sometimes this happens to me too. Android 7, LineageOS

**Comment by 2048-Bit** [comment] 2019-05-17 11:44
For any of you following this, there has been a commit to fix this:  https://github.com/wireapp/wire-android/commit/77051081043d5dff2a5f4fb3e2fc7a67bd8434b3

Thanks for sharing all the great detail!

**Comment by Caspy7** [comment] 2019-05-20 03:12
Got an ETA for when this will hit the Play store?

**Comment by IronJunkie** [comment] 2019-05-20 03:22
@caspy7
I can't say for sure as I'm a nobody around these parts but I'd think it'll be soon as I got the beta update from Play store & it is fixed (on my phone at least)

**Comment by dedaxys** [comment] 2019-05-21 14:09
Issue is now resolved for me after the latest patch

**Comment by kYwzor** [comment] 2019-05-22 13:25
This seems like a duplicate of #777, which is a long-standing issue. I'm quite surprised that the devs aren't prioritizing this.

**Comment by charlag** [comment] 2019-05-22 13:26
Also can confirm that issue is solved for me now

**Comment by marcoconti83** [comment] 2019-06-05 12:36
Hi everyone,
this was an issue introduced as a regression, and it has been fixed as of 3.33. This is unlike #777 in the sense that this issue was 100% reproducible. This specific issue has been fixed, for any other comment on notification please use #777. Closing this one. Thanks for your patience!

**Closed by marcoconti83** 2019-06-05 12:36 UTC
