### ISSUE TITLE
Messages are stuck in -sending- without being sent

### ISSUE THREAD

**Issue by revpp** [wireapp/wire-android#1014] opened 2017-07-14 13:11 UTC
From time to time messages are being stuck permanently in " sending" mode and never go through. To make it work again it's necessary to do "force stop" app under Android's settings and relaunch it again. Probable cause might be lack of internet at the moment of sending messages afterthat it get stuck that way without trying to resend message again.

**Comment by stinsonga** [comment] 2017-07-19 01:57
I've had a similar issue, though in my case even force-stopping the app doesn't suffice to remove the eternal sending state. I see an animated, red bar (probably a progress bar) at the top of the screen, and it never stops. Once a message fails to send, every message thereafter fails to send. The only thing that has fixed this, for me, is clearing the app's data (or reinstalling) - even signing out won't clear it. 

I do think there is something to the idea that this is caused by losing connection (or maybe in my case, switching between wifi and cell data) at the moment of sending. This has been the case each time I've seen this issue.

**Comment by someoneEsle** [comment] 2017-08-03 11:35
Hi, this is a known bug and we have been working on a fix. It will soon be fixed. :)

**Comment by someoneEsle** [comment] 2017-09-07 14:47
Hi, this should have been fixed so I'm going to close the issue. Let us know if you are still experiencing it.

**Closed by someoneEsle** 2017-09-07 14:47 UTC

**Comment by spbmas** [comment] 2022-02-14 18:41
This happens to me almost every day. It requires FORCE STOP and restart to resolve, and then the message goes through. It seems to correlate with switching between mobile data and WiFi on my Pixel 3 phone running Android 12 and Wire for Android version 3.69.996. It has happened continuously over more than a year during which time both Android and Wire have been updated several times. It's quite annoying to have to watch out for it and manually restart to successfully send messages. Luckily, it just about the only annoying thing about Wire, so we keep using it.  :)
