### ISSUE TITLE
Images not loaded in Android 4.4.

### ISSUE THREAD

**Issue by DrAxelbauer** [wireapp/wire-android#830] opened 2017-05-01 07:07 UTC
I encountered a bug (it seems) on android 4.4.2 devices.sent images do not show up instead there is a gray box where the picture should show up. I encountered this on 3 different devices with android 4.4. 

Newest wire version installed from the homepage. I also tried to verifyand reset the session but nothing seems to work. Pictures are in compatible format.

How ro reproduce:
Send a picture to the phone.

**Comment by mykola-mokhnach** [comment] 2017-05-01 07:46
Please get the debug log like it is described in the issue reporting template and send the log to our customer support.

**Comment by rbu** [comment] 2017-05-04 07:30
Duplicate of #826 ?

**Comment by MrCustomizer** [comment] 2017-05-04 15:53
I think, I can confirm, that the two issues are related. I also don't see images on my android  device, which are added by my desktop device. If I've understood my buddy correctly, he has the same problem, whereas the friend who could download my file, also can see the images.

**Comment by DrAxelbauer** [comment] 2017-05-07 10:50
I just sent the bugreport to the support. Hopefully there will be solutions ;)

**Comment by darkbluelight** [comment] 2017-05-21 08:39
The reason pictures don't load is here: #518 
The solution would probably this: #870

**Comment by DrAxelbauer** [comment] 2017-05-24 07:56
Thanks for the hints! I will then wait for the next android update for the 4.2 Android phones. It is a little bit inconvenient  because many manufacturers do not provide newer android versions (Fairphone for example (which is a mess (for foss people ;) )!!!)) and I don't use Google Services as far as possible due to privacy reasons ;)

**Comment by DrAxelbauer** [comment] 2017-06-22 13:53
He Everyone! 
As we know and can read above there is an issue with regard to older android version and tsl.....I now fond an workaround, which is solving the TSL issue:

1. Update your **Google Play Services** for the right architecture/dpi...Just follow the instructions here (or elsewhere): [http://www.apkmirror.com/apk/google-inc/google-play-services/google-play-services-11-0-56-release/]

2. Install the latest Wire version from the webpage (or elsewhere)
3. Restart your phone

4. Here we go! Images at least work!

Have and use Wire! – It might be helpful if you let everyone know if the workaround also helps you...I must confess that i don't know how critical the Update via this course is and if it might damage your phone, but in my case it worked out of the box with no problem!

**Comment by makingthematrix** [comment] 2020-01-29 14:57
As we don't support Andriod 4.x anymore, I think we can safely close this issue.

**Closed by makingthematrix** 2020-01-29 14:57 UTC
