### ISSUE TITLE
Parts of conversations missing

### ISSUE THREAD

**Issue by nijel** [wireapp/wire-android#2262] opened 2019-08-21 07:15 UTC
**Describe the bug**
Sometimes I miss parts of conversation on Android app, while it's visible in the web. It seems to be related with file sending. Whenever file is sent, this message and following one is missing.

**To Reproduce**

1. Send me a file
2. Send me a message
3. I see them on the web interface
4. But they won't appear in the Android app

**Expected behavior**
Web and Android app should show same conversation.

**Screenshots**
Conversation in web:
![web](https://user-images.githubusercontent.com/212189/63410489-b608a580-c3f3-11e9-93ef-2c64a8829279.png)
Conversation in Android app:
![android](https://user-images.githubusercontent.com/212189/63410494-b99c2c80-c3f3-11e9-942b-106375330329.png)

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.36.819
- Last Wire version that did not exhibit the issue (if applicable): N/A
- Android OS version used to run Wire: 8.1.0
- Is this a custom firmware or a stock one: stock
- Mobile phone model/manufacturer: Moto G5s
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): any

**Additional context**

**Comment by CeryleRudis** [comment] 2019-08-22 06:58
I believe the same as #2249 and #2226 (Closed).
This has just happened again to me on the latest version.

**Comment by IronJunkie** [comment] 2019-08-27 07:10
I have had this happen also, but only once, missing content appeared the next day. Essential ph-1 stock Pie.

**Comment by makingthematrix** [comment] 2019-09-11 13:14
Hi.

Can you reproduce the bug on the newest Android client? Recently we made many changes to how assets (files, photos, videos...) are handled and I although it doesn't look like a bug that is directly connected to any of those changes, I can't reproduce it now.
To be honest, I installed the 3.36 version and couldn't reproduce it as well, so... strange.

If you can, please turn on "Collect usage data" in Settings -> Advanced, reproduce the bug again, and then "Create debug report" and send it to us.

Thanks in advance!

**Comment by nijel** [comment] 2019-09-11 14:14
New app definitely doesn't fix past conversations - the same parts are still missing there. I will keep eye on new ones if I notice some problem.

**Comment by makingthematrix** [comment] 2019-09-11 15:31
Nevermind. I can reproduce the bug now. Thanks!

**Comment by nijel** [comment] 2019-09-23 14:00
I've just hit this bug again now. Is debug report still useful now when you can reproduce the issue?

**Comment by marcoconti83** [comment] 2019-09-23 15:26
Hi @nijel ,
we are almost there with the fix, at the moment we don't need additional logs. Thanks!

**Comment by marcoconti83** [comment] 2019-09-24 20:52
Hi all,
Thanks for the reports! We investigated the issue and likely found the cause, we are working on a fix that should be ready soon. There are multiple tickets related to this issue, I'm going to use only one to keep track of the progress, https://github.com/wireapp/wire-android/issues/2232. I will close this one, and we can continue the conversation there.

**Closed by marcoconti83** 2019-09-24 20:52 UTC
