### ISSUE TITLE
Sharing files to multiple recipients

### ISSUE THREAD

**Issue by kroerig** [wireapp/wire-android#2379] opened 2019-10-21 10:07 UTC
**Describe the bug**
When sharing files (e.g. pictures) from outside wire to multiple recipients some of them get the file, while others don't because the file stucks with "Uploading failed. Retry". But retry does not work.

**To Reproduce**
Share a file from e.g. image gallery to multiple recipients.

**Expected behavior**
Every recipient should get the file.

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.41.848
- Last Wire version that did not exhibit the issue (if applicable): one or two version before
- Android OS version used to run Wire: 9
- Is this a custom firmware or a stock one: Sony stock
- Mobile phone model/manufacturer: Sony XZ1 compact
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): any

**Comment by kroerig** [comment] 2019-11-11 14:04
I just had the same problem sharing an audio file to a wire group.

I than shared it using the "attache file" function within wire. This worked.

**Comment by Gardosen** [comment] 2020-03-02 13:02
based on the latest client with an android 9 phone, i was not able to reproduce this. 

@kroerig is this still happen for you? i will keep this ticket open for 7 days to wait for your response. after that i will close it, but feel free to open another one if the issue still persists, and we can communicate about it in a ticket which is up to date :)

Kind regards
Marco from the Android Team

**Comment by kroerig** [comment] 2020-03-02 13:29
@Gardosen I tried it again with 3.45.886 right now and the picture was deliverd to all recipients.

So I think this issue has been resolved.

**Comment by makingthematrix** [comment] 2020-03-06 16:37
ahh, heck, I wanted to write that we made one more improvement ot this functionality, but if it works already then there's no point... ;)

**Closed** 2020-03-06 16:36 UTC
Labels: Needs more information
