### ISSUE TITLE
[Enhancement] Audio-messages bigger than 25Mb are lost

### ISSUE THREAD

**Issue by ronidee** [wireapp/wire-android#972] opened 2017-06-30 18:57 UTC
After recording a 25mb+ audio-message, the message is lost. 
Then the user has to repeat everything he just said in two separated messages.

### Please implement one of these functionalities: 

a) automatically stop the recording/notify the user
b) split the recording into several files and send them
c) increase the maximum size
d) add an option to increase compression/decrease quality.

Thank you very much

**Comment by someoneEsle** [comment] 2017-07-01 06:56
duplicate of #508, please upvote that ticket and comment there if needed :)

**Comment by ronidee** [comment] 2017-07-01 09:19
Ah, I'm sorry. I searched for this issue but didn't find it, that's.

**Closed** 2017-07-01 09:19 UTC
