### ISSUE TITLE
Sending picture removes send button in next text message

### ISSUE THREAD

**Issue by ShawnPConroy** [wireapp/wire-android#1230] opened 2017-10-30 12:59 UTC
## The problem

If you send a picture from the conversation list, the keyboard send button is missing on next message until you close the chat.

## Environment

* LG G6
* Android 7.0 (stock)
* Wire 3.1.369
* WiFi and 3G
(On Friday I signed up for the beta program on the Play Store)

## Details

Turn off the send button, making the keyboard enter button become a send button in text messages.

From the conversation list, swipe one of the conversations. Tap the picture icon. Select and send a picture. Now, tap the input area and type some text.

The 'send' button is not present on keyboard. Tapping the back button does not show a send button on the chat screen. Tapping back a second time bring you to the conversation list. Going back in, tapping the input field now correctly shows the send button on the keyboard.

*What works normally*:

If you send by tapping the picture button in the chat, the text input still works as expected.

If the 'Send Button' option is turned on, the send button appears above the keyboard as usual.

**Comment by makingthematrix** [comment] 2020-02-20 14:14
The assets functionality was rewritten completely. I can't reproduce the bug.
I'll close it now - if it happens again, please reopen.

**Closed by makingthematrix** 2020-02-20 14:14 UTC
Labels: bug
