### ISSUE TITLE
Notifications are a mess since about 2 weeks ago

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-android#2545] opened 2020-01-11 18:53 UTC
This look like 2 different bugs.

Notification on desktop never clear when message read on mobile.

Same notification show up sometime 3-4 times after I swipe them away.

**Comment by BradleyWire** [comment] 2020-01-13 08:38
Hi @Transisto, can you please add the steps on how you're able to reproduce this?

**Comment by Transisto** [comment] 2020-01-16 20:06
Steps: 
Receive a message
Read it on your phone
When going to desktop app all conversation still have same pending notification for already read messages.
Need to click all of them one by one to clean notifications.

**Comment by YellowOnion** [comment] 2020-02-09 00:35
Notifications never get delivered, or are 24 hrs late, it's been happening for years, I've been hoping they will fix this issue, but most of the bug trackers they're just ignoring now, and so I'll be advising friends to move away to something else since they don't take this service seriously.

#777 #1517 https://github.com/wireapp/wire/issues/18

**Comment by makingthematrix** [comment] 2020-02-17 12:00
A possible fix or at least a step forward: https://github.com/wireapp/wire-android/pull/2616

**Comment by Transisto** [comment] 2020-02-20 21:28
None of the problem originally described improved one bit.

Mobile notification eventually clear between mobiles (after showing 3-4 times in notifications) but not on desktop.

**Comment by makingthematrix** [comment] 2020-02-21 09:52
@Transisto : That fix will be included in the next release, 3.46.

**Closed** 2020-05-06 14:42 UTC
