### ISSUE TITLE
Allow to know from what contact that wire account comes from. 

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-android#1111] opened 2017-09-11 00:34 UTC
If people from my contacts list get added it would be great to know from what phone number they come from.

Also seeing the contact name I've associated to them in my phone would be very useful.

**Comment by someoneEsle** [comment] 2017-09-11 07:11
Hi, this is a duplicate of #248. Please upvote that issue to show your support for the feature. Thanks!

**Closed by someoneEsle** 2017-09-11 07:11 UTC
Labels: enhancement
