### ISSUE TITLE
Erratic input problems

### ISSUE THREAD

**Issue by voidzero** [wireapp/wire-android#1428] opened 2018-02-23 16:12 UTC
## The problem

When I type a little bit too fast, there is some strange kind of word / character replacement going on that adds / removes characters from the previous word. It is hard to figure out a pattern, because it is not consistent.

When I type, the word that I am currently typing gets underlined. I think this is some kind of word recognition. Then, as soon as I type a space and start writing the next word, it modifies the previous word and does not add the character I typed last.

"This is an example sentence that gets garbled up", turns into something like this:

"Tthis i an eexampl entence ttha gge garbled up."

But like I said, the behavior is erratic. If I type the same sentence over and over again, sometimes it happens and sometimes it doesn't. If I type more slowly, it does not happen at all.

It only happens with the "standard" Google keyboard (from the Play store - not Android's built in keyboard, I haven't tried that one) on which I am using the Dvorak keyboard layout. I have not enabled the autocorrect feature (or most other features e.g. swipe). Word suggestions (including next word suggestion) is enabled. In Android's language/input settings, I have disabled the spell checker.

If I use Google's Japanese keyboard with Roman input, the problem does not happen at all (but that one does not support dvorak layout).

This problem does seem to be related to whatever causes the word currently being typed to be underlined / recognized. Sometimes, after a space, the next word also gets underlined. It has to be related to whatever does this.

This problem happens only with Wire, and it happens both in the main app, and in the quick reply feature in the notifications.

I surely hope we can nail and squash this nasty bug.

## Environment

* Wire version that exhibits the issue: latest version (Android)
* Last Wire version that did not exhibit the issue (if applicable): unsure but I *think* somewhere in the last year
* Android OS version used to run Wire: Lineage OS 13 (Android M)
* Mobile phone model/manufacturer: HTC One M9

**Comment by someoneEsle** [comment] 2018-02-27 10:12
Hi, thanks for reporting. Please avoid vague expressions like "latest version" when specifying the version number -- we cannot trust that everybody checks for updates daily, plus one month from now "latest version" won't mean anything.
This bug sounds like a bug we had in the past, but fixed a few versions ago. Please let us know exactly what version you're using -- and if you realize that you're not on the latest update, please update and check if it's still happening. Thanks!

**Comment by makingthematrix** [comment] 2020-03-25 11:59
Hi.

I'm going to close this ticket as I can't reproduce the bug. Please reopen if it happens again.

**Closed by makingthematrix** 2020-03-25 11:59 UTC
