### ISSUE TITLE
Old notifications won't disappear

### ISSUE THREAD

**Issue by peterpanondrugs** [wireapp/wire-android#348] opened 2016-11-27 12:36 UTC
Yo,

Actual result:
- receive a new notification
- 1 old notification is always shown below the new ones (contact unrelated?!)

Expected result:
- only show the actual new notification
[wire_debug_report.txt](https://github.com/wireapp/wire-android/files/614696/wire_debug_report.txt)

P.S. Reinstall / delete Data doesn't solve this issue

**Comment by levinus** [comment] 2016-11-27 13:04
I recognized this too. I'm on a Nexus 5X with Android 7. App Version 2.22.298.

**Comment by someoneEsle** [comment] 2016-11-27 19:46
This is an old bug that keeps getting fixed and reappearing somehow. I'm not sure what the root cause is, but I do know that the developers are aware of it.

**Comment by danielw93** [comment] 2016-12-30 09:02
You can fix this by scrolling up in the conversation until you get past the message that always shows in the notification and then scroll back down. After that it is not shown anymore.
I can never reliably reproduce this bug though. Just tends to happen every now and then. 

The only constant factor I noticed so far is, that it ever only happens when someone sends me > 3 messages in quick succession 

-Nexus 5X, Android 7.1.1, Wire v.2.24.303

**Comment by someoneEsle** [comment] 2017-01-07 06:30
Unfortunately the fix/workaround you suggested doesn't work for me. Tried it many times now 😭

**Comment by Gardosen** [comment] 2020-03-03 12:02
this issue has been fixed i guess, as there was no report regarding this for months/a year.

i close this ticket as "fixed"

Kind regards
Marco from the Android Team

**Closed by Gardosen** 2020-03-03 12:02 UTC
Labels: bug
