### ISSUE TITLE
List of contacts gets "scrambled" regularly

### ISSUE THREAD

**Issue by forteller** [wireapp/wire-android#903] opened 2017-06-03 14:48 UTC
My list of contacts on Wire does not stay sorted by who I've talked to most recently. Many times the last month at least the list has been "scrambled". The person I talk with the most has even been sent to the very bottom, just above Otto, quite a lot. I've mostly kept my Wire up to date. I haven't updated to 338 because it's not available from the website yet.

**Comment by forteller** [comment] 2017-07-17 18:20
This is still happening with the latest version (2.36.343), and it's still extremely annoying. My most used contact is still mostly at the bottom, just above Otto.

Does no one else have this issue?

**Comment by Transisto** [comment] 2017-09-22 21:02
Noticed the same problem.

**Comment by someoneEsle** [comment] 2017-09-25 08:36
Next time this happens to you, please go into Settings>Advanced and send us a log with a link to this issue.
Thanks!

**Comment by makingthematrix** [comment] 2020-02-20 14:06
The conversation list was rewrriten and I can't reproduce the bug. I'll close it for now. Please reopen if it is still happening to you.

**Closed by makingthematrix** 2020-02-20 14:06 UTC
Labels: bug
