### ISSUE TITLE
Load bar stays forever and nothing comes in or get sent unless wire is closed and restarted.

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-android#2003] opened 2019-02-16 21:36 UTC
I think this began about 2 months ago when you pushed individual notification or something.

**Comment by marcoconti83** [comment] 2019-02-18 11:08
Hi @Transisto , 

Thanks for the report, can you tell us which version of Wire are you using, and what steps do you take to trigger this bug?

**Comment by Transisto** [comment] 2019-02-18 20:01
Latest version and it just seems to happen 75% of the time I open the app.

**Comment by marcoconti83** [comment] 2019-02-19 12:25
We are in the process of enabling more logs on public builds, so that user can send us log to investigate issues that we can't reproduce on our side. Since logs might contain sensitive information, we are performing an audit of the logs logic to verify that the logs are reasonably anonymized and contain no sensitive information. Once this is done and deployed, we will ask you to send logs which will help us debug this issue.

**Comment by RITFW** [comment] 2019-02-21 00:01
I can confirm this behaviour as well on Android 8.1 (LOS) without Google services and Wire 3.2.6 as well as 3.2.7 which is kinda annoying as I sometimes only get the messages someone sent me when I open the Desktop Client. 

I have the feeling that Wire somehow freezes when I don't open it for a couple of hours on Android and then nothing gets synchronised, even when I open Wire and only killing the app and reopening it helps solve this issue. As soon as logs are anonymized I am happy to send some as well and hope this will help finding the root of the problem.

**Comment by marcoconti83** [comment] 2019-04-03 08:19
Hi everyone,
logs have been released to the public. 

This is how it works: before you can send logs, you need to enable logs recording. This is because we don't want to store this log file on your filesystem unless you decided to do it. As a consequence, you need to first enable logging, then reproduce your bug. If you do enable the logs after the bug has occurred, it will not contain the necessary information as nothing was recorded at that time.

To enable the logs, you can go to "Settings" -> "Advanced". You turn the logs on with the "Collect Usage Data" toggle. Once the logs are enabled, a log file is stored locally on your device. The log is not sent to Wire until you click on "Create debug report" in the same screen. When this happen, you are prompted to save/send the log file.

You can have a look at the log file yourself to make sure of what it contains; we have put an effort to anonymize most data via hashing. Once you are satisfied with the content, you can send it to our support (support@wire.com, and please mention the github ticket) or paste/link the content here, your choice.

**Comment by marcoconti83** [comment] 2019-09-27 14:26
Hi @RITFW ,
thanks for the report. We just released a beta version that should fix your issue. We will probably release it to public beginning of next week, but you can give the beta version a try if you want to provide us some feedback. You can join the beta from the Play store page.

**Comment by RITFW** [comment] 2019-09-28 11:40
Hi @marcoconti83 ,
thanks for making Wire better. Unfortunately I don't use the Playstore version, but I am happy to test the apk from your website release as soon as it is available and give feedback if something doesn't work.

**Comment by marcoconti83** [comment] 2019-09-30 11:35
Hi all,
we released a fix to public just today. You can get it from the play store and from our website. I'll close the issue for now, please reopen if this is still an issue for you. Thanks!

**Closed by marcoconti83** 2019-09-30 11:35 UTC
Labels: wait for logs
