### ISSUE TITLE
Blank/White screen whenever a message is received (and opened) from the notifications bar

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-android#769] opened 2017-04-04 20:12 UTC
Whenever I receive a new message, I get a notification (as usual); when I tap on that notification in the bar to bring up the application and read the message I can only see a white/blank screen.

In order to see the message I have to "go back" (with the operating system button, the one in the application doesn't appear since the whole screen is white/blank); then the app's interface shows up. If the same conversation is opened again, the same blank/white screen appears again, so I have to open up a different conversation (with another user/friend) and then go back to see the original message (the actual one I was notified for).

I've tried removing the conversation(s) but it didn't help. I thought it could have been _something in particular_ with those threads.

This issue happens continuously (to me and a couple of my friends that also use Android). I have a `Nexus 6P` running Android `7.1.x`.

**UPDATE:** Actually, it also happens when I just load the app and try to see a conversation; always the first one I try to see.

**Comment by someoneEsle** [comment] 2017-04-06 09:33
See also #112 and #475. I'm attaching a log captured right after opening and closing a blank conversation a couple of times (I did not need to receive a notification in order to reproduce this bug).
[wire_debug_report.txt](https://github.com/wireapp/wire-android/files/902112/wire_debug_report.txt)

**Comment by ghsrcgh** [comment] 2017-04-09 16:39
I have the same issue just by openning contacts window and opening a "chat" with a some contact. In some cases I see just a full blank white screen and nothing more. Even if you will wait a minute - nothing is changed. If you will press back button and try to open specified contact again - it may opened normally, but may be opened as white blank screen again.

**Comment by 2114L3** [comment] 2017-04-19 11:12
myself and another friend on wire are getting this on androids. latest version. didnt notice this on previous version.

**Comment by 2114L3** [comment] 2017-05-04 09:52
still getting this issue in Release 2.31.324 which listed "Fix: You could experience a blank screen when opening Wire from notifications. Fixed."

**Comment by makingthematrix** [comment] 2020-05-07 11:32
This functionality was reworked and I can't reproduce this bug anymore. I think I can close it now. Please reopen if something like this happen again.

**Closed by makingthematrix** 2020-05-07 11:32 UTC
Labels: bug
