### ISSUE TITLE
Unable to receive messages exchanged while Wire was stopped

### ISSUE THREAD

**Issue by kYwzor** [wireapp/wire-android#2145] opened 2019-05-20 16:02 UTC
**Describe the bug**
Since around the end of April, I've been having issues receiving messages on my smartphone, although sending messages works perfectly. While in this "bugged state", Wire is completely unable to load messages that have been exchanged since I last opened the app and there is no loading bar at the top, even if I wait for a long time (~30min). While the app is opened, I can receive new messages from other people and send new ones too. However, messages sent by myself from other devices appear on my smartphone as an error with a "Learn More" link.
Relogging doesn't fix the issue. Reinstalling fixes the issue for a couple of days, but so far it came back eventually every single time.
A friend of mine has recently started to have these issues too, so I believe this is not a problem with my phone.

**To Reproduce**
Although it happens consistently a few days after a reinstall, I'm not sure what triggers it exactly, so I haven't been able to find the what the reproduction steps are. It seems to mostly happen when I haven't opened the app for a while and lot of messaging has been going on (on both chat groups and direct messages). I regularly force stop Wire, which might be related to the issue, but it didn't cause any problems to me previously.

**Expected behavior**
Being able to send and receive messages without any issue and also browse older messages that were exchanged while the application was killed.

**Smartphone:**
- Wire version that exhibits the issue: 3.32.781
- Last Wire version that did not exhibit the issue: Not sure, but I didn't have this issue until late April
- Android OS version used to run Wire: 4.4.2
- Is this a custom firmware or a stock one: Stock firmware
- Mobile phone model/manufacturer: Vodafone Smart first 6
- Mobile network type: Wi-Fi

**Additional context**
I'm using Wire simultaneously on Android, Windows and Linux. I have been using it on Android since around the beginning of the year with no issues until now. I'm available to give you any further information that might be needed to track down this issue. Currently, Wire is working perfectly for me, as I've reinstalled it for the 5th time, but it's very likely the issue will come back eventually.

**Comment by rothnorton** [comment] 2019-05-21 00:22
I wonder if this is related to a recent commit #2136 , in which case hopefully there's a fix coming soon.

This issue, and similar, has basically scared my coworkers back to telegram, (missed messages and notifications can cost us too much money), but I don't like telegram, so am hanging in with wire for a robust android wire app.  I'm sure it's not far off.

Basically we need the notification system to work smoothly, no missed messages, and (preferably), not a huge battery drain on the phone apps.  I'm sure the devs know this, and I'm wishing them on, 'cause telegram is surely just sophisticated spyware.

**Comment by kYwzor** [comment] 2019-05-22 13:32
> I wonder if this is related to a recent commit #2136 , in which case hopefully there's a fix coming soon.
I don't think so. That appears to be a commit for #2127/#777 and people are claiming those issues were fixed in the latest update. However, I'm currently on 3.33.786 and my issue persists.
To be clear, the issue I'm having is that the old messages simply never show up in the chat history, while these other reported issues are just about not getting notifications.

**Comment by kYwzor** [comment] 2019-05-22 14:01
Some further findings:
I created a new chat group on my desktop while the application on my phone was closed. A day later, I opened my phone and that chat group didn't appear on my chat list. Then, with Wire open on both my desktop and my phone, I sent a message from my desktop to that chat and I received absolutely nothing in my phone. Messages sent by other people on that chat had the same behaviour. Changing the chat group's name didn't make it appear either. However, sending messages from my phone to a chat group that appears on my chat list works perfectly, and so does getting recent messages sent by either me on my desktop or by my friends in that group.

Another interesting behaviour is that it seems to be able to load messages that were exchanged while the app was stopped as long as they were sent somewhat recently (a few minutes). Older messages never show up though and for my phone it's like they never existed.

**Comment by gcsilva11** [comment] 2019-05-22 14:33
I have a similar issue where I can't see any conversations that were had when they weren't on the mobile app, as well as new conversations/chat title changes and anything of the sorts.

**Comment by rothnorton** [comment] 2019-05-25 15:41
Seems to have fixed itself for me.  Not sure why, its since i uninstalled and reinstalled the latest version 3.33.786.  Good for now, but it's possible i havent triggered the conditions which cause the issue.

**Comment by marcoconti83** [comment] 2019-06-05 12:36
Hi everyone,
this was an issue introduced as a regression, and it has been fixed as of 3.33. This is unlike #777 in the sense that this issue was 100% reproducible. This specific issue has been fixed, for any other comment on notification please use #777. Closing this one. Thanks for your patience!

**Comment by kYwzor** [comment] 2019-06-05 12:53
This hasn't been fixed for me at all. It is not the same issue as #777 as it's not related with notifications. I simply do not receive messages. Please consider reopening.

**Comment by selurvedu** [comment] 2019-06-05 13:43
@marcoconti83, ^^^ https://github.com/wireapp/wire-android/issues/2145#issuecomment-499070048

**Comment by marcoconti83** [comment] 2019-06-05 15:38
Thanks for the feedback. Reopening this one then.

**Comment by marcoconti83** [comment] 2019-06-05 15:42
For those that are having this issue: can you please enable logging, wait until this happens again (e.g. creating a new chat that does not show up, ...) and then export the logs? Make sure that logging is enabled BEFORE this happens.

The logs are reasonably anonymized so you could post them on gist/pastebin and link them here, or send them at support@wire.com , If you send them at support@wire.com, you have to specify that they are related to this ticket or we will not be able to correlate them.

**Comment by kYwzor** [comment] 2019-06-06 16:54
I'll reinstall and enable logging right away then. Then I'll send the logs when I first notice the bug occurring. However, I've noticed it also logs the contents of the messages themselves and I'm not comfortable with sharing that. Is there any way to easily censor the contents without going through it manually?

**Comment by marcoconti83** [comment] 2019-06-07 07:56
Hi @kYwzor , 
what do you mean by content of the message? Can you copy paste one line where you see that (replace the actual content with "xxxxxxxxxxx" by hand before pasting)? 
Thanks

**Comment by kYwzor** [comment] 2019-06-07 12:54
@marcoconti83 from what I can see, each message seems to appear twice in different places on the log. Here's 2 logs that contained the same message (it's an old report):

> 2019-05-22T13:40:39.123Z-TID:2129/V/NotificationService#6c9ab0dd:` show: , ignore: NotificationData(61b9a19c-4266-41bb-9691-d357ddc13fee,**MESSAGE HERE**,2c2fec69-006c-4bea-a7c1-8a1b0459b245,bcefb295-8319-4267-8d4a-8e5c3a81bb4f,TEXT,RemoteInstant(2019-05-22T13:40:39.493Z),false,false,None,false,false)

>05-22 14:40:38.872 V/MessageEventProcessor(20068): MessageData content: MessageContent(TEXT,**MESSAGE HERE**,None,None,None,0,0,false,Stream())

I guess I could find a way to remove it with regex, but I hoped there was an easier way

**Comment by marcoconti83** [comment] 2019-06-07 13:08
Thanks for the feedback @kYwzor . We'll look into it straight away.

**Comment by marcoconti83** [comment] 2019-06-12 15:49
This last issue from @kYwzor has been addressed [here](https://github.com/wireapp/wire-android-sync-engine/commit/56fed68ca850ffb4f1685100297888daa38cc4a7) and will be released shortly.

**Comment by kYwzor** [comment] 2019-06-12 15:53
> 
> 
> This last issue from @kYwzor has been addressed [here](https://github.com/wireapp/wire-android-sync-engine/commit/56fed68ca850ffb4f1685100297888daa38cc4a7) and will be released shortly.

Another similar (although not as worrying) situation is that Group Chat names also get leaked in the logs if a rename occurs. An example below:

> 2019-06-09T15:22:21.905Z-TID:2370/V/Stage[ConversationStateEvent]: processing 1 event: RenameConversationEvent(2c2fec69-006c-4bea-a7c1-8a1b0459b245,RemoteInstant(2019-06-09T11:43:09.706Z),bcefb295-8319-4267-8d4a-8e5c3a81bb4f, **NEW CHAT NAME HERE**)

**Comment by kYwzor** [comment] 2019-06-15 18:20
I can confirm that the issue with logs leaking message contents and chat names has been fixed in the latest patch. 
I have enabled logging once again and I'll wait for the bug to reoccur.

**Comment by marcoconti83** [comment] 2019-06-17 11:17
Thanks for confirming, @kYwzor !

**Comment by kYwzor** [comment] 2019-06-24 17:47
I force stopped Wire about 3 days ago and I've only opened it again today, which caused the bug to reoccurr. Once again, I'm now in a state in which:

- Wire doesn't retrieve any message that occurred during the time it was stopped.
- I can receive new messages from other people, but only while the app is opened.
- I can send messages using the app and the other people can receive them.
- I can't receive my own messages sent from another device (An error appears saying that it couldn't receive my own message and it links me to [this support page](https://support.wire.com/hc/en-us/articles/207948115-Why-was-I-notified-that-a-message-from-a-contact-was-not-received-))

I'm fairly convinced that, in order for this bug to be reproduced, all we need is to stop the app for a couple of days while exchanging a lot of messages using other devices. Here's the debug report, which started recording logs since about a week ago.

[wire_debug_report.txt](https://github.com/wireapp/wire-android/files/3321923/wire_debug_report.txt)

**Comment by kYwzor** [comment] 2019-07-11 16:41
@marcoconti83 are there any updates on this?

**Comment by marcoconti83** [comment] 2019-07-12 08:45
Hi @kYwzor ,
We didn't have any luck reproducing this issue on our side. We have to dig into the code to figure out where this comes from, but unfortunately we could not spend enough time on this to find anything interesting. 

@kYwzor have you tried turning on the setting to stay connected to the websocket even when the app is closed? Does it make a difference?

**Comment by kYwzor** [comment] 2019-08-14 20:58
Hey @marcoconti83, sorry for the late answer.
The issue is still occurring occasionally, even with the setting to stay connected. I'm not sure if I'm helping much by sending more logs but I'll send them anyway. I think that on the first log I only turned on the setting to stay connected after it bugged out (and it didn't fix it), however on the second one I had it always on (and it still stopped working). Hopefully this will help. Thanks

[wire_debug_report.txt](https://github.com/wireapp/wire-android/files/3503308/wire_debug_report.txt)
[wire_debug_report2.txt](https://github.com/wireapp/wire-android/files/3503309/wire_debug_report2.txt)

**Comment by marcoconti83** [comment] 2019-09-27 14:26
Hi @kYwzor ,
we believe we found the source of the issue for some missing messages while Wire was not running. We just released a beta version that should fix your issue. We will probably release it to public beginning of next week, but you can give the beta version a try if you want to provide us some feedback. You can join the beta from the Play store page.

**Comment by kYwzor** [comment] 2019-09-27 15:51
Hey! Unfortunately you no longer support my Android version, so I can't test it.

**Comment by marcoconti83** [comment] 2019-09-30 11:33
Hi all,
a fix for this issue has been released to public today. I'll close the ticket, but please let us know if you are still experiencing this issue.

**Closed by marcoconti83** 2019-09-30 11:33 UTC
Labels: bug

**Comment by masumiuc** [comment] 2022-05-03 21:50
I having same problem
