### ISSUE TITLE
Wire disconnects by itself

### ISSUE THREAD

**Issue by MakisH** [wireapp/wire-android#599] opened 2017-02-13 16:16 UTC
I just noticed that I got disconnected from Wire. I had to sign-in and set my picture again.

Yesterday, a friend complained to me that the same thing happened to her, too.

This is not the first time that this happens to me and at the same time I noticed that it happened to other people, too. Perhaps it is related to updating?

I know that this bug requires investigation and I would like to ask other users to help with this. I would consider it very important, since it hurts the reliability of the service. Plus, when I get people use Wire and they stop receiving my messages, it is difficult to get them back into it.

I am running Wire 2.27.314 and Android 5.1.

**Comment by xuanzhaopeng** [comment] 2017-02-13 16:57
Hi @MakisH , thanks for your information! May I ask the auto logout happened after you upgrading into new version of Wire? if yes, do u still remember what's the previous version you use? if not,  do u remeber what's the last action in Wire you did before it logout?

Thanks

**Comment by MakisH** [comment] 2017-02-13 23:42
I see that the latest version (that I now have) was released on github 6 days ago. Could it be that I received it on my phone today? I receive the updates normally via the Google Play Store. I don't see anywhere when I last received an update.

Before getting disconnected, I had used my phone and my computer (web app) 1-2 hours ago, just texting. I didn't turn off my phone in the meanwhile, just normal operation.

The friend that had the same problem yesterday runs Android 6 and again it happened under normal operation, while the phone was idle.

**Comment by MakisH** [comment] 2017-02-21 08:20
This happened again to me today (maybe yesterday afternoon-night) and to the same friend of mine (two nights ego). I haven't asked any other people yet.

We still both have Wire 2.27.314, so it must not be related to updates. We are both located in Germany, I am registered with my e-mail, and my friend is registered with her phone number. Both on Android (5.1 and 6.0.1), different phone brands.

Again, before it disconnected, I didn't do anything unusual. Just text messages.

**Comment by rbieb** [comment] 2017-02-22 06:12
Two of my contacts suffer from the same issue. This has been occuring for some months now. Android version was always 7.x, both phones are Nexus 5x.

The issue is still occuring with the last version of wire. Please prioritize this bug if possible, since you can never be sure if your messages actually reached somebody or if they got logged out again without noticing.

**Comment by waltsims** [comment] 2017-03-02 22:44
This just happened to me as well. I had to login via SMS code!

**Comment by instantchow** [comment] 2017-03-29 23:53
Perhaps a catch all solution to this and other "got logged out and didn't know" problems is to have a notification in the **Notification Area** that says **"you're logged out, wanna do something about it?"**

**Comment by MakisH** [comment] 2017-03-30 08:44
I think this wouldn't be a good solution, because:
1. the source of the problem will remain unknown,
2. some people prefer to be logged out from some Apps by default. Showing a notification every now and then (trying to bring them back) would be annoying and in their position I may uninstalled the App.

**Comment by makingthematrix** [comment] 2020-05-07 11:28
I think I can safely close this issue now.

**Closed by makingthematrix** 2020-05-07 11:28 UTC
Labels: bug
