### ISSUE TITLE
Bring the app to f-droid

### ISSUE THREAD

**Issue by bootofood** [wireapp/wire-android#233] opened 2016-10-12 17:06 UTC
Please make it possible to compile the app without the non-free dependencies.
In this way it could be included in f-droid, finally beating Signal!

**Comment by someoneEsle** [comment] 2016-10-12 17:58
https://github.com/wireapp/wire-android/issues/5
Please close.

**Comment by bootofood** [comment] 2016-10-13 08:42
Thanks. That issue is closed, that's why I didn't find it. Good to read that they're interested in publishing the app in f-droid, certainly a more friendly and reasonable approach than what we got for Signal.

Shouldn't a "f-droid issue" stay open until we've got it in there, complying with the inclusion policy?

**Comment by someoneEsle** [comment] 2016-10-13 22:08
I don't know what the policy as for keeping issues open is, but it looks like something they're aware of, therefore there's no need to let the ticket open (which may be why they closed the other one). I'm pretty sure they'll remember even if this issue gets closed.
(I understand your point about leaving an issue open though, maybe they could leave the original one open as it has the official reply too)

**Comment by bjoernherbig** [comment] 2016-10-14 06:46
Thanks guys for bringing this up again and yes, we will remember it for sure. As for closing it, we will leave this one open since there are likely to come in more requests for f-droid.

**Comment by h-2** [comment] 2016-10-14 18:25
Out of curiosity: what are the proprietary dependencies blocking f-droid acceptance? Seems like if you already have a fallback for GCM you are almost there or not? Maybe other people could help in this process?

**Comment by legovini** [comment] 2016-10-16 14:01
@h-2 take a look here:

https://github.com/wireapp/wire-android/issues/5#issuecomment-234947466

and compiling without GCM is probably non trivial, even if there is already a fallback mechanism.

**Comment by h-2** [comment] 2016-11-04 14:15
I am posting a 50€ bounty for someone who creates a version of the Android Wire client that fully meets F-Droid’s criteria, i.e. no proprietary dependencies. Preferably the changes would also meet upstream’s criteria for integration into the official repository, e.g. via a Flavor or build flag or something like that.

I can send the money via Paypal or WireTransfer/SEPA.

**Comment by lipis** [comment] 2016-11-04 14:50
💶 💵 💶 💵 💶 💵

**Comment by grote** [comment] 2016-11-06 12:38
The first step, before anybody can take this on would be to get rid of the [custom maven repository](https://dl.bintray.com/wire-android/third-party/com/wire/) and get those dependencies submitted to jcenter.

Currently, these libraries are affected:
* gradle-android-scala-plugin - non-upstreamed fork?
* icu4j-shrunk - non-upstreamed fork?
* robotest_2.11 - non-upstreamed fork?
* spotify-auth - non-free software?
* spotify-player - non-free software?

Having some information on these libraries would make it easier to assess the actual effort needed for a 3rd-party to take on this work.

**Comment by h-2** [comment] 2016-11-08 14:57
Users of Signal have three months until the last version "expires" that works without PlayServices. If wire published a preliminary free software version until then, it could motivate quite a few people to switch and would definitely get some attention...
https://twitter.com/VenemaSander/status/794937272697294852
https://twitter.com/shiromarieke/status/793947755840413696

(Note that Free Software server source and federation #237 would be really cool, but totally unrelated to this issue as Signal didn't provide these either)

**Comment by darkbluelight** [comment] 2016-11-11 10:17
Referencing [https://github.com/wireapp/wire-android/issues/233#issuecomment-253722552](url)
@bjoernherbig count one more request for f-droid from a Signal user (with quite some friends using Signal...) willing to change to Wire! I'm really looking forward to it. Especially as the GCM free WebSocket Signal for f-droid is very likely to be discontinued :(

**Comment by bgermann** [comment] 2016-11-16 12:18
The bintray maven repository [wire-android/third-party](https://dl.bintray.com/wire-android/third-party) that @grote mentioned is not the only one that is in use and not allowed by f-droid. There are some more by wire ([wire-android/releases](https://dl.bintray.com/wire-android/releases), [wire-android/snapshots](https://dl.bintray.com/wire-android/snapshots)), which can be built from the github sources, a [consp1racy repo](http://dl.bintray.com/consp1racy/maven) and a [Localytics repo](http://maven.localytics.com/public).

The consp1racy repo can safely be removed, as the artefact is available in jcenter.

The Localytics library seems to be BSD licensed, but I cannot find the corresponding source. I guess this tracking library would have to be removed for f-droid anyway.

I have not checked all build scripts. Maybe there are some other Maven repositories not allowed by f-droid.

For the mentioned third-party libraries I have found the following:

- gradle-android-scala-plugin - [non-upstreamed fork](https://github.com/deanrobertcook/gradle-android-scala-plugin), can be imported [via jitpack](https://jitpack.io/#deanrobertcook/gradle-android-scala-plugin/83a8c877a5).
- icu4j-shrunk - can be replaced by standard icu4j.
- robotest_2.11 - There is a newer incompatible version available on standard repos. But you can use a [jitpack build](https://jitpack.io/#zbsz/robotest/v0.7) on [v0.7](https://github.com/zbsz/robotest/releases/tag/v0.7).
- spotify-auth - A newer version is [available](https://github.com/spotify/android-auth/). I have pull requested them to be able to export a Maven artefact. There is one line to be patched out, as one interface changed.
- spotify-player - non-free software! [In 2014 they said it will be open sourced](https://github.com/spotify/android-sdk/issues/13), but you cannot expect that to happen soon. However it is still an active project. So this has to be non-trivially patched.

**Comment by h-2** [comment] 2016-11-23 15:40
So it seems it is mostly about making the spotify stuff optional, the rest is just infrastructural cleanup?

**Comment by pboesch** [comment] 2016-12-11 14:17
I'm waiting to have Wire on Fdroid :)!

**Comment by bgermann** [comment] 2016-12-15 18:29
@wireswiss in app/opensource.txt you list Spotify Authentication Library and Spotify Player Library as Apache 2.0 licensed. While this is true for a newer Authentication Library than the Beta version you link with, the Spotify Player Library is subject to [Spotify Developer Terms of Use](https://developer.spotify.com/developer-terms-of-use) rather than any open source license.

You also list Localytics SDK in that file, but it is not open sourced as well. I guess it is redistributable under the Localytics [Terms of Service](https://www.localytics.com/terms-of-service).

I suggest you remove the lines from app/opensource.txt and mention the proprietary dependencies at [README](https://github.com/wireapp/wire-android#what-is-included-in-the-open-source-client)

**Comment by grote** [comment] 2016-12-15 18:31
I would also be nice if you could clarify whether you would accept a PR that introduces a new gradle flavor that builds the app without these non-free dependencies.

**Comment by hakonbo** [comment] 2016-12-16 09:47
Hi all,

We are looking into creating an F-Droid flavour, but it's a side project and will take a bit of time. Would be great if you want to contribute. 
Spotify/Localytics libs are included in the sync engine project as well, so we need a new flavour of that one as well.
@bgermann Thanks for checking the licences, I think that file might be a bit outdated, I'll see if we can get it updated.

**Comment by bastoGrande** [comment] 2016-12-29 20:52
Why was it closed? I think it's still not published in F-Droid.

So what's next on the agenda to make publishable on F-Droid?

**Comment by grote** [comment] 2016-12-31 18:01
@bastoGrande the issue is still open and the current status has been posted right above your message.

**Comment by someoneEsle** [comment] 2016-12-31 18:04
@grote when @bastoGrande asked "why was it closed" I think he was talking about the PR introducing free build types: https://github.com/wireapp/wire-android/issues/411

**Comment by JustAskin** [comment] 2017-01-13 14:05
I think Signal developers should prioritize enabling it on F-droid. Quite a chunk of their potential user base is privacy nazis and tinfoil hatters (proudly including myself) who'd never let Google's playstore touch their device.

There's also no real VOIP FOSS substitute to Signal with everything else being amateurishly broken or difficult for my normie friends to learn. Even Wire collects your metadata. Please make Signal available to us ASAP!

**Comment by TomSea** [comment] 2017-01-21 13:38
Yes. Please make wire as an fdroid package. Thanks!!!

**Comment by h-2** [comment] 2017-03-27 15:24
> I am posting a 50€ bounty for someone who creates a version of the Android Wire client that fully meets F-Droid’s criteria, i.e. no proprietary dependencies. Preferably the changes would also meet upstream’s criteria for integration into the official repository, e.g. via a Flavor or build flag or something like that.
>
> I can send the money via Paypal or WireTransfer/SEPA.
>
> edit: timeframe: for this bounty there should be some alpha/beta version until 2017-02-01

Signal now works well with Websockets and is available as APK, but not in F-Droid so I am renewing this pledge until 2017-07-01!

**Comment by bgermann** [comment] 2017-04-01 22:14
spotify-auth is now available on jCenter. I created a pull request https://github.com/wireapp/wire-android/pull/759 to update Wire accordingly.

**Comment by bgermann** [comment] 2017-04-20 19:32
Have a look at #805 and you will see that spotify dependencies will be gone.

**Comment by fungs** [comment] 2017-05-03 20:18
Yes, I'm also waiting for Wire to get fully open (FDroid build support) before I can convince my contacts to switch from Signal/LibreSignal to Wire. It would be nice for all of us who do not use Google apps on our phones.

**Comment by mxmehl** [comment] 2017-05-11 09:39
>> I am posting a 50€ bounty for someone who creates a version of the Android Wire client that fully meets F-Droid’s criteria, i.e. no proprietary dependencies. Preferably the changes would also meet upstream’s criteria for integration into the official repository, e.g. via a Flavor or build flag or something like that.
>
> Signal now works well with Websockets and is available as APK, but not in F-Droid so I am renewing this pledge until 2017-07-01!

I add another 50€ to @h-2's pledge, same timeframe and same conditions.

It would be awesome to have Wire in F-Droid!

**Comment by Larx** [comment] 2017-05-25 05:30
Just for the record, wire works fine with MicroG. As thus a non-free dependency is seamless replacable by a free drop-in, I don't know how FDroid's stance is.

**Comment by fungs** [comment] 2017-05-25 06:48
@Larx: AFAIK FDoid allows non-free dependencies but marks them as anti-features. Nonetheless, many build on FDroid have such dependencies removed. I'm not sure if MicroG can be incorporated as a replacement at compile time or if it needs a modified OS with signature spoofing enabled (I believe the latter). Wire doesn't need GCM/MicroG at all, if the WebRTC fallback method is used.

**Comment by Larx** [comment] 2017-05-25 08:22
I have a modified ROM (signature spoofing) for MicroG. Otherwise, Wire runs as downloaded (even the PlayStore version), no modification at all, and get its notifications through "GCM". IMHO (but I'm no purist) this makes me "Google-free" enough, but I guess the FDroid guys have other restraints.

**Comment by eighthave** [comment] 2017-05-25 09:13
F-Droid requires apps be free software and be built from source.
Including Google's proprietary GMS libraries makes Wire non-free
software.  If Google made those Android libraries free software, we
could include Wire as it is right now.

**Comment by bgermann** [comment] 2017-05-25 09:18
That is not true. The proprietary spotify-player (still in wire-android-sync-engine) and Localytics dependencies would have to be patched out additionally.

From f-droid Inclusion Policy about Play Services/MicroG: 

> We cannot build apps using Google's proprietary "play-services". Please talk to upstream about an untainted build flavor (either using microg or removing non-free deps completely).

**Comment by Larx** [comment] 2017-05-25 10:05
I don't want to spam this thread, just wanted to point out that Wire is already completely usable without the Google packages on the device.

**Comment by bgermann** [comment] 2017-05-25 11:00
@Larx Even if it is usable without Google packages on the device, the Google dependencies are still needed for the compilation. For a free version those dependencies would have to be removed or replaced by MicroG.

**Comment by bgermann** [comment] 2017-07-26 07:34
I had a look at the MicroG libraries. The play-services-base, play-services-location and play-services-gcm dependencies could be replaced by the MicroG libraries, but as of now there are no replacements for **firebase-messaging** (maybe Google will free this one) and **play-services-maps** (only API version 1).

**Comment by grote** [comment] 2017-07-26 13:19
> play-services-maps (only API version 1).

Did you look into whether [Lost](https://mapzen.com/blog/open-source-location-services-with-lost/) could be a free replacement here?

**Comment by grote** [comment] 2017-07-26 13:20
Sorry not Lost, but there's also osmdroid and maps libraries by Mapzen and Mapbox which should be compatible.

**Comment by bgermann** [comment] 2017-07-26 14:11
The MicroG lib uses osmdroid under the hood. Upstream does [not support V2](https://github.com/osmdroid/osmdroid/issues/75) either. There is a feature [request for Mapzen](https://github.com/mapzen/android/issues/225). I do not see hints for Mapbox supporting any version of the Google API.

So there seems to be no trivial solution. Maybe the V2 calls can be replaced by V1 calls easily and then MicroG/osmdroid can be used.

**Comment by Mis012** [comment] 2017-09-01 09:00
MicroG supports maps api v2, I think. It's just not written correctly somewhere.

**Comment by bgermann** [comment] 2017-09-01 09:53
It is only [partially supported](https://github.com/microg/android_packages_apps_GmsCore/wiki/Implementation-Status). I [requested wire's missing API calls](https://github.com/microg/android_external_GmsApi/issues/7).

**Comment by Mis012** [comment] 2017-09-01 16:09
oh I see. Maybe someone from here could help with that? For example a callback may be relatively easy thing to implement?

**Comment by h-2** [comment] 2017-09-02 13:13
@Mis012 Can we move discussion about MicroG to a different thread? It won't help bring it to F-Droid...

**Comment by Dionis0s** [comment] 2018-02-14 11:18
It's very important for dataprivacy reasons to get Wire on F-Droid. 
Please publish your app there. :)
What is the current status?

**Comment by colans** [comment] 2018-02-14 18:56
If you really want to be using F-Driod, you should consider switching to https://riot.im/.

The MicroG issue here is related to a similar one in that queue: https://github.com/vector-im/riot-android/issues/994.

**Comment by phoen7x** [comment] 2018-02-17 16:25
> colans:
 If you really want to be using F-Driod, you should consider switching to https://riot.im/.

Why the hell?!?
We want use **wire** and **not** Matrix! We are here in the wire github repo and not in riot.im.
_______________________________________________________

Back to topic, please bring your app to F-Droid, it's:

1.  the only googlefree way to use wire (the version from website includes google (gcm))
2.  compfortable for useres without PlayStore

Thank you guys for your great work!! :)

**Comment by phoen7x** [comment] 2018-02-22 21:06
Take an example on [Tutanota](https://tutanota.com).

> One of our aims with Tutanota is to offer a **secure alternative** to mainstream mail services like Gmail and Yahoo that spy on their users.

> To fully leave Google behind, we as the Tutanota developers have yet to do our share: Right now the Android app relies on Google's GCM for push notifications. That's why it is so important for us to publish the Tutanota app on F-Droid.

So are there positiv news for us?

https://tutanota.com/blog/posts/secure-mail-open-source

**Comment by bgermann** [comment] 2018-02-22 23:59
> the new Android app will finally come without any ties to Google services

So no. **unhelpful!**

**Comment by phoen7x** [comment] 2018-03-09 21:15
Freeze?

**Comment by strypey** [comment] 2018-07-12 03:47
Mapzen has shut down, so their Lost API etc may not be a replacement for Google location services, but Mapzen posted this guide to some alternatives: https://mapzen.com/blog/migration

**Comment by mnemi** [comment] 2018-10-03 21:44
It looks like Tutanota was able to overcome the GCM issue and release their app on f-droid. Maybe this will be helpful to Wire? https://f-droid.org/en/2018/09/03/replacing-gcm-in-tutanota.html

**Comment by fungs** [comment] 2018-10-04 13:11
@mnemi, the last paragraph is very true: there should be an open standard for push notification and everybody should pick a trusted provider for him or herself, reducing the number of active connections and controlling the flow of data.

AFAIK GCM is not the main issue for bringing Wire to FDroid as it has a working websocket implementation which could be selected at compile time.

**Comment by selurvedu** [comment] 2018-10-11 15:54
Wire always worked just fine without GCM. See my short report in #1833.

**Comment by fungs** [comment] 2018-10-12 07:35
@selurvedu: The question is whether it can be built from sources using the fdroid tool chain without google requirements.

**Comment by tuxayo** [comment] 2018-12-05 09:57
About FCM (ex GCM) see #1903

**Comment by trymeouteh** [comment] 2019-04-03 23:38
Is this still in the works. I would like to have Wire on my LineageOS devices.

**Comment by fungs** [comment] 2019-04-10 16:39
As for #5 which was closed I think there is no clear communication whether the Wire team wants to support the open source community by bringing Wire to FDroid. Also, its seems that the organization lacks policies and/or resources to classify and handle these kinds of requests. All I can see is users communicating with each other but no statement, assignment or prioritization whatsoever.

For me it looks like the Wire company has entirely shifted towards providing a business tool while ignoring its principal open source philosophy and community.

**Comment by sudoquai** [comment] 2019-06-14 14:46
F-Droid please !

**Comment by JonasDralle** [comment] 2019-07-14 10:00
This ticket is open while #5 has been closed. This seems wrong to me.
The devs said something along the line of "yeah we are aware" and then closed the original ticket.

**Comment by EdaNano** [comment] 2019-11-09 12:54
Let's ask again :)
Hi Wire developers, is this issue, three years after it was opened, still in your TODO list? And is it getting near the exit point on this list? Should we F-Droid users still hope ;)
Thank you :)

**Comment by tuxayo** [comment] 2019-11-09 17:23
In the hope to move this forward a bounty has been started for the removal of the non-libre FCM dependency: https://github.com/wireapp/wire-android/issues/1903#issuecomment-552118691

**Comment by Gardosen** [comment] 2020-02-27 14:31
Hey Everyone,

i am currently cleaning up this issues board and i stumbled across this long ongoing discussion.
i fully understand this request and started investigating about decisions, actions taken and things in the past related to this request by talking to colleagues.

i will continue this investigation and sync up with my team members in the Android Team to be able to give a clear and final answer about if it will ever be possible to make this F-droid support possible.

Kind regards
Marco from the Android Team

**Comment by Gardosen** [comment] 2020-03-02 08:42
Update Week 10(2nd of March): I closed two tickets, related to this topic, so we have one ticket as the source of truth about it.

OpenPush will be discussed internally this week.

Kind regards
Marco from the Android team

**Comment by genodeftest** [comment] 2020-04-18 22:56
In theory, the [rfc2822 F-Droid repo](https://gitlab.com/rfc2822/fdroid-firefox) should contain the Wire APKs. However, the download link broke because Wire's version numbering changed ([bug report](https://gitlab.com/rfc2822/fdroid-firefox/-/issues/10)). It would be nice if you could fix that.

**Comment by 12people** [comment] 2020-04-20 09:34
@Gardosen How did the internal discussion go? Any plans on incorporating OpenPush?

**Comment by android10** [comment] 2020-05-07 08:07
@12people and the rest, sorry for the late reply. At the time being there are no plans to address this. Unfortunately we are suffering from other issues that are higher priority. In any case, we will keep you posted if anything changes in the mid term. 

Thanks for the patience.

**Comment by genodeftest** [comment] 2020-05-07 17:58
You may just add the [rfc2822 F-Droid repo](https://gitlab.com/rfc2822/fdroid-firefox) to F-Droid. The issues I mentioned a few weeks back have been fixed.

**Comment by zabbal** [comment] 2020-05-07 18:11
> You may just add the rfc2822 F-Droid repo to F-Droid

No you can't:

> The APKs are unaltered and hence still signed by the app developers.

So the Wire installed from that repo will still rely on proprietary FCM and won't work for lots of phones. The point of this ticket is not to automate manual .apk download step, it's to uplift Wire to the same code quality standards which are used by other secure chat apps in f-droid.org repos, like Telegram for example.

**Comment by zabbal** [comment] 2020-05-07 18:27
On a positive side, with the introduction of E2E to Riot and other Matrix clients this issue might become obsolete in a foreseeable future :)

**Comment by stephenjudge** [comment] 2020-05-07 18:37
I understand @zabbal point, however it doesn't look like Wire will ever buy in a position to replace the FCM dependcy and to be fair to Wire, they have pivoted aware from being a consumer client and are now focused on corportate solutions, so bring Wire to the F-Droid Repository is not going to be a very high priority for them.

If they cannot replace their FCM dependecy, then I would suggest that the best middle ground solution would be for them to host their own F-Droid Repository using the F-Droid Repomaker https://f-droid.org/en/repomaker/. This allows them to be in control of how their app is distrubted using the F-Droid app, rather than relying on third-party repositories like rfc2822 or Izzy's Repo.

**Comment by colans** [comment] 2020-05-07 20:17
> On a positive side, with the introduction of E2E to Riot and other Matrix clients this issue might become obsolete in a foreseeable future :)

Just to add more perspective to that thought, I've been using Riot.im/Matrix.org for a couple of years now, having dumped Wire a while ago (mostly due to https://github.com/wireapp/wire/issues/160).  E2EE was in the Matrix protocol before, but [the UX recently got better](https://blog.riot.im/e2e-encryption-by-default-cross-signing-is-here/) (yesterday, in fact).

**Comment by strypey** [comment] 2020-05-08 05:19
@stephenjudge 
> Wire ... have pivoted aware from being a consumer client and are now focused on corportate solutions

This is a red herring. If a corporate user chooses Wire over a proprietary chat app (eg WhatsApp or whatever Goggle calls their "enterprise" chat apps these days), it's because they care about security. Therefore they are just as likely as anyone to want a client that meets the requirements for inclusion in the F-Droid repo. With E2EE now being on by default in Riot, If Wire don't prioritize F-Droid inclusion, and rolling out support for server<>server federation (see https://github.com/wireapp/wire/issues/160#issuecomment-582012258 ), they might find the corporate users they want as customers starting to use Matrix via Modular.im instead.

**Comment by 2011** [comment] 2020-07-20 12:02
Just to add a comment to this thread so I can find it again...

The about page on the web site states "We put security and privacy first..." I don't see how Wire can make that claim (regarding privacy, not security) when Google gets a timeline of all received messages (via FCM) for the Android app, and would likely have no problem determining the identities of two or more people (all using Android) communicating with each other (in a real-time text chat, for example).

**Comment by tuxayo** [comment] 2020-07-22 01:22
> have no problem determining the identities of two or more people (all using Android) communicating with each other (in a real-time text chat, for example).

I'm not sure how much users&messages traffic are needed to make such an attack impractical. That would be interesting to explore. IMHO, not much. I don't know how much of the 1.000.000+ install have daily activity but seeing only the GCM traffic should be terrible mess to match to user.
Responding quickly to the other is also important to help the attack.
And it's only for the receiver that gets a GCM push which makes matching harder.

**Comment by strypey** [comment] 2020-07-22 06:43
@tuxayo 
> I'm not sure how much users&messages traffic are needed to make such an attack impractical. 

Doesn't that rather depend on the nature of the attack? What @2011 is saying is that GCM is leaking metadata. Let's not forget that fomer government spooks have made public comments about [killing people based on metadata](https://www.techdirt.com/articles/20140511/06390427191/michael-hayden-gleefully-admits-we-kill-people-based-metadata.shtml). While that's unlikely to be part of the threat model for a corporate client, it seems wise for Wire engineers to do everything they possibly can to reduce the amount of metadata that Wire leaks.

**Comment by codedust** [comment] 2020-08-18 08:49
More importantly, the closed-source libraries to use GCM need to be included in the Wire apk. This ruins the high mark of confidence of the Wire app not being able to bypass e2ee that is introduced by releasing the source code of the app. Only if the app can be build without any proprietary Google library, full trust in the app can be established.

**Comment by zabbal** [comment] 2020-12-21 11:35
https://github.com/threema-ch/threema-android - given the recent news on Threema going Free (as in Freedom) way I think this issue can be closed once threema appears on f-droid.org

**Comment by grote** [comment] 2020-12-21 11:37
Does not like Threema is (fully) Free Software though: https://github.com/threema-ch/threema-android/blob/main/app/build.gradle#L384-L392

So it won't appear in F-Droid anytime soon.

**Comment by zabbal** [comment] 2020-12-21 11:45
Given that this issue will soon meet half-decade jubilaum, I'm prepared to use more relaxed definition of "soon" in this case.

**Comment by SailReal** [comment] 2021-01-30 23:25
Related to Threema: With this ugly hack I dropped all proprietary libs and code related to it https://github.com/SailReal/FOSS-threema-android/commit/ade01768be1a15095363710931787e8e149033ed ... feel free to use it :)

I will re-implement it using a build flavor to push it to the upstream repo and Threema said that they will accept this contribution but it will take time so feel free use the fork for time being.

**Comment by est31** [comment] 2021-01-31 08:36
@SailReal this is a thread about the Wire app. There is a dedicated thread for Threema's inclusion on the f-droid RFP tracker: https://gitlab.com/fdroid/rfp/-/issues/1596

**Comment by JavaZauber** [comment] 2021-09-25 10:37
Cool!

**Comment by Gardosen** [comment] 2021-11-09 08:55
Hello Everyone,

with the big help of @obfusk we have managed to finally get rid of this goliath.
to anyone who wants to help us finetune the last steps, please have a look at the following mergerequest to the fdroid metadata project on gitlab.
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10045

i will close this feature request issue here now, and we can move the continued talk to the gitlab merge request.

Kind regards
Marco

**Closed by Gardosen** 2021-11-09 08:55 UTC
Labels: feature request

**Comment by alexander-cato** [comment] 2021-12-07 03:36
What happened to the merge request?

**Comment by Rick-W-Storm** [comment] 2021-12-07 14:56
Where?
![](https://user-images.githubusercontent.com/6533815/145052232-9e627ec6-e4a9-4874-87b0-832655ae8fdf.png)

https://search.f-droid.org/?q=wire

**Comment by alexander-cato** [comment] 2021-12-07 19:25
Here is what I found on the topic @Rick-W-Storm:
![IMG_0513](https://user-images.githubusercontent.com/52341592/145092936-f6bbc607-7af1-44ce-9a03-42881a5cc788.jpg)

Hopefully there is a way to force a redeploy sooner though. Maybe @Gardosen can make this happen since they're familiar with FDroid's GitLab process's and CI/CD pipelines.

**Comment by eighthave** [comment] 2021-12-08 10:06
You can see the current and previous build runs here:
* https://monitor.f-droid.org/builds/running
* https://monitor.f-droid.org/builds/build

There you can see the build log from each app, including _com.wire_, which is listed under "Failed":
https://monitor.f-droid.org/builds/log/com.wire/1982129#site-footer

The data center that hosts the signing server is having some power difficulties due to the aftermath of a big storm, so signing is running intermittently.

**Comment by Rick-W-Storm** [comment] 2021-12-08 10:10
Then this issue is not _closed_.

**Comment by alexander-cato** [comment] 2021-12-10 20:09
@eighthave Thanks for this resource. I see now Wire has built successfully yet it is still coming up 404 on https://f-droid.org/packages/com.wire/

Perhaps some type of caching or propagating? Will check back in a few days.

**Comment by sandwm** [comment] 2021-12-10 21:41
@alexander-cato See here: https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client

So yes, it will probably be available in a few days, after the apk has been manually signed and the new index published to the F-Droid clients (and a bit later to the website).

**Comment by DC7IA** [comment] 2021-12-11 15:29
> @eighthave Thanks for this resource. I see now Wire has built successfully yet it is still coming up 404 on https://f-droid.org/packages/com.wire/

It just became available.

**Comment by tuxayo** [comment] 2022-01-01 14:38
Thanks to everyone involved in this :heart:
