### ISSUE TITLE
Images not receiving

### ISSUE THREAD

**Issue by purpleden** [wireapp/wire-android#2282] opened 2019-09-06 21:33 UTC
On my android phone (7.1.2 ASOP) I am not receiving any pictures or videos or sounds sent to me, it stopped working about two weeks ago. I am able to send, and see pictures/videos/sounds I send. All text comes through fine. All messages and media are timed to expire after one week.

Wire App version 3.37.820 (Direct from website)

To reproduce, I simply ask someone to send me a picture/media file. I receive the pic/video/audio in wire web app fine.

**Expected behavior**
I used to receive media fine.

Phone is constantly using wifi

[UPDATE]
Can receive media on android app, providing the sender switches off auto-destruct for that particular media item

**Comment by brainode** [comment] 2019-09-11 10:04
The same thing on Android app ver. 3.38.826.
Using HTC U11, with Android 9

**Comment by brainode** [comment] 2019-09-11 10:31
@purpleden i think this issue duplicate #2232

**Comment by marcoconti83** [comment] 2019-09-24 20:43
Hi all,
Thanks for the reports! We investigated the issue and likely found the cause, we are working on a fix that should be ready soon.

Let's continue to track the discussion on the duplicated ticket #2232 , I'll close this one.

**Closed by marcoconti83** 2019-09-24 20:43 UTC
