### ISSUE TITLE
choose display name for contacts

### ISSUE THREAD

**Issue by Be-ing** [wireapp/wire-android#310] opened 2016-11-14 08:47 UTC
Many people only put their first name as their viewable contact name in Wire. As contacts lists grow, this will get confusing with multiple contacts using the same name. Account avatars alleviate this issue, but the contact could change their avatar and I anticipate some people will do this pretty frequently. So, it would be helpful for users to choose their own display name for contacts (and not have it affect how that contact appears to other people).

**Comment by someoneEsle** [comment] 2016-11-14 17:02
Duplicate of #214 
I would suggest pulling the names from the phone's contacts list too (if the user has allowed access to contacts), it is the standard in other IM apps.

**Comment by someoneEsle** [comment] 2016-11-15 20:17
They've started working on usernames apparently https://github.com/wireapp/wire-android-sync-engine/tree/usernames. Keep an eye on the repository for updates

**Comment by h-2** [comment] 2016-11-23 13:28
Yes, lets move discussion to #248

**Closed** 2020-01-09 14:46 UTC
Labels: enhancement

**Comment by globetrotter7** [comment] 2020-05-01 07:43
Has this issue been resolved yet?  It would be helpful to know which Mike, Tom or Sam I'm writing to when I have many friends with the same name.

**Comment by grinapo** [comment] 2020-05-08 10:59
> Has this issue been resolved yet? It would be helpful to know which Mike, Tom or Sam I'm writing to when I have many friends with the same name.

It has been **rejected** (in #248) and **closed** (both places). Or vice versa. It will not be implemented by Wire. No point complaining.
