### ISSUE TITLE
Renaming my own name is not synchronized 

### ISSUE THREAD

**Issue by theincogtion** [wireapp/wire-android#781] opened 2017-04-08 21:10 UTC
I changed my account name on windows but this has not been synced to my android app.
I waited for a whole day (24h) and tried to change it manually but this also fails.
I have now 2 different user names.

**Comment by mykola-mokhnach** [comment] 2017-04-09 11:58
Have you changed the name from Windows application or from a browser (which one)? Were both devices online at that time or only one of them? What are versions of Windows and Android applications?

**Comment by theincogtion** [comment] 2017-04-09 12:23
> Have you changed the name from Windows application or from a browser (which one)?

From the Windows application

> Were both devices online at that time or only one of them?

Both online

> What are versions of Windows and Android applications?

Android 2.31.324
Windows 2.12.2729

**Comment by mykola-mokhnach** [comment] 2017-04-10 08:26
Unfortunately, we cannot reproduce the issue. Could you please contact our support and provide logs?

**Comment by theincogtion** [comment] 2017-04-10 09:13
I sended my logs from android and refereed to this issue. Where can I find windows logs?

**Comment by david-wire** [comment] 2017-04-11 12:00
Unfortunately the Android log file does not seem to pinpoint where you issue lies. To gather the logs on Windows, please have a look at: https://github.com/wireapp/wire-desktop/wiki/Start-Parameters (Start production wrapper with devtools section).

**Comment by theincogtion** [comment] 2017-04-13 08:48
I tried to change the user name on android to the same as the windows one. This failed. I just send a debug log of this issue. please tell me if you still need the windows log.

**Comment by theincogtion** [comment] 2017-04-19 07:51
I started wire with devtools option and I just see a new sidebar (looks like in chrome). Where can I find the log?

**Comment by david-wire** [comment] 2017-04-19 14:34
Can you expand that sidebar? The log are in the 'Console' tab. You can right click > Save as and send us the logs as a text file. Also, have you tried to log out and log back in on the Android app to see if the issue persists?

**Comment by theincogtion** [comment] 2017-04-19 14:39
Ok right, I changed my name again and got this in the log:
`HEAD https://prod-nginz-https.wire.com/users/handles/usefulvid5 404 (Not Found)`
This message is not shown in 
C:\Users\xxx\AppData\Roaming\Wire\console.log

**Comment by makingthematrix** [comment] 2020-06-05 08:56
We wrote this functionality completely. I will close this bug. Please reopen if anything like it happens again.

**Closed by makingthematrix** 2020-06-05 08:56 UTC
