### ISSUE TITLE
"The person is writing me" indication hides later than it should

### ISSUE THREAD

**Issue by avently** [wireapp/wire-android#688] opened 2017-03-07 16:28 UTC
I'm chatting with a person that use iPhone. I use Android. After this person sent me a message "The person is writing me" indication (pencil + a name) wasn't hid. It hides after a minute or so. It doesn't happen everytime.  Maybe 1 of 4 messages shows this bug. 
I don't know it's related to Android version or iPhone version of app. So I'm writing you here. You know better. 

2.28.317, AOSP 7.1.1

**Comment by mykola-mokhnach** [comment] 2017-03-07 18:40
This works as designed. IsTyping indicator only disappears immediately if the other side deletes typed message or sends it. But in case something is written in the input field, but it not send yet, then we consider that the sender is still considering what to write and thus showing the indicator until timeout happens.

**Comment by someoneEsle** [comment] 2017-03-07 18:52
Duplicate of #431 , this is indeed a bug as I've seen with my own eyes people not touching their phone when the isTyping indicator was displayed on my phone :)

**Comment by avently** [comment] 2017-03-07 18:55
Hm, I don't think that it is expected behavior. Typing means that Now I'm tapping on keyboard's buttons and not just watch on the screen with some characters in the text field. I didn't see this behavior in any messager I used (whatsapp, vk, Skype and others). This really annoying when I'm waiting a message but minute gone and indicator just hides and no message was received. I could not even confirm your words because i don't know what person on the other side is doing with his phone...but every ~4 message he is watching on the filled text field? I don't think so. 

Maybe after some time of inactivity you can send a message like isTyping=false? Something like 5 seconds after last entered symbol. This will be fair. If a guy on the other side is looking on the screen without any interaction with keyboard we can think that he is not typing. 
What do you think?

**Comment by avently** [comment] 2017-03-07 18:57
Oh, sorry for the duplicate. Maybe now you will want to take a look at this issue?

**Comment by bjoernherbig** [comment] 2017-03-08 07:26
closing this as a duplicate. we will review the behaviour soon. it indeed seems not as reactive as one would expect it.

**Closed by bjoernherbig** 2017-03-08 07:26 UTC
Labels: question
