### ISSUE TITLE
Message not shown in a message thread after sending

### ISSUE THREAD

**Issue by pprucia** [wireapp/wire-android#603] opened 2017-02-14 08:44 UTC
I was sending a message to someone on wire. After sending it doesn't show up in message thread immediately. I went back to recent contacts and then enter the thread back, still, message wasn't there. It appeared only after killing the app and launching it again.

[wire-logs.txt](https://github.com/wireapp/wire-android/files/773511/wire-logs.txt)

Wire version: 2.27.314

**Comment by someoneEsle** [comment] 2017-02-14 10:02
duplicate of #595

**Closed** 2020-06-05 08:50 UTC
Labels: duplicate
