### ISSUE TITLE
Wire app does not work on Android 9 x86 or x86_64 systems

### ISSUE THREAD

**Issue by msdhedhi** [wireapp/wire-android#2286] opened 2019-09-09 21:08 UTC
Wire app does not work on Android 9 x86 or x86_64 systems. I tried this on the Android 9 emulator and it just hangs after the login screen. I used wire android app version 3.37.820 from playstore.

Following is what I saw in the adb log.
___________________________________________________________________________________________

09-09 21:01:00.142  1906  1927 I ActivityManager: Start proc 5772:com.wire/u0a88 for activity com.wire/com.waz.zclient.LaunchActivity
09-09 21:01:00.175  5772  5772 I com.wire: The ClassLoaderContext is a special shared library.
09-09 21:01:00.306  1906  2601 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.wire/com.waz.zclient.LaunchActivity bnds=[35,1659][237,1917]} from uid 10030
09-09 21:01:00.511  1906  2601 I ActivityManager: START u0 {cmp=com.wire/com.waz.zclient.appentry.AppEntryActivity} from uid 10088
09-09 21:01:02.142  1906  1934 I ActivityManager: Displayed com.wire/com.waz.zclient.appentry.AppEntryActivity: +1s472ms (total +1s990ms)
09-09 21:01:02.314  1719  1878 W SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen com.wire#0
09-09 21:01:02.314  1719  1878 W SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen com.wire#0
09-09 21:01:04.382  5772  5774 I com.wire: Compiler allocated 4MB to compile com.google.i18n.phonenumbers.PhoneNumberUtil com.google.i18n.phonenumbers.PhoneNumberUtil.getInstance()
09-09 21:01:04.498  5772  5772 E com.wire: Invalid ID 0x00000000.
09-09 21:01:06.171  2060  2060 I LatinIme: onActivate() : EditorInfo = Package = com.wire : Type = Email : Learning = Disable : Suggestion = Hide : AutoCorrection = Disable : Microphone = Hide : Incognito = Disable
09-09 21:01:06.199  2060  2060 W Conv2QueryExtension: Conv2Query not enabled due to current app [com.wire] not in whitelist
09-09 21:01:10.311  2215  2215 D ImsResolver: maybeAddedImsService, packageName: com.wire
09-09 21:01:11.910  5772  5772 E com.wire: Invalid ID 0x00000000.
09-09 21:01:11.933  2060  2060 W Conv2QueryExtension: Conv2Query not enabled due to current app [com.wire] not in whitelist
09-09 21:01:23.348  1906  1920 I ActivityManager: START u0 {cmp=com.wire/com.waz.zclient.MainActivity (has extras)} from uid 10088
09-09 21:01:23.457  5772  5797 E com.wire: No implementation found for void com.waz.call.FlowManager.attach(android.content.Context, long) (tried Java_com_waz_call_FlowManager_attach and Java_com_waz_call_FlowManager_attach__Landroid_content_Context_2J)
09-09 21:01:23.713  1906  1934 I ActivityManager: Displayed com.wire/com.waz.zclient.MainActivity: +352ms
09-09 21:01:24.312  5772  5812 I chatty  : uid=10088(com.wire) RenderThread identical 16 lines
___________________________________________________________________________________________

It looks like the native API "com.waz.call.FlowManager.attach" is not resolving ( via JNI ).
The API is only present in  the ARM flavors armeabi-v7a/libavs.so and arm64-v8a/libavs.so

If the wire app is not supported on x86/x86_64, then it is better to use the appropriate switches in the Android app gradle files to not include these .so files under lib/x86 and lib/x86_64. This will also reduce the apk size. See https://proandroiddev.com/reducing-apk-size-by-using-abi-filters-and-apk-split-74a68a885f4e

**Comment by marcoconti83** [comment] 2019-09-10 09:03
Hi @msdhedhi ,
thanks for opening the issue and for digging into the causes.

**Comment by marcoconti83** [comment] 2019-11-15 10:56
Hi,
This fix has just been released to public with version 3.42. I'll close the issue, feel free to reopen if this is still a problem.

**Closed by marcoconti83** 2019-11-15 10:56 UTC
Labels: bug
