### ISSUE TITLE
Wire Android Repeatedly crashes on launch

### ISSUE THREAD

**Issue by wiredOr** [wireapp/wire-android#1948] opened 2019-01-17 07:51 UTC
## The problem

Since yesterday, after launch, Wire briefly shows my home screen (with my icon in the top left, and my name in top center) and then immediately crashes on my Android phone.

## Environment

* Wire version that exhibits the issue: 3.24.684
* Last Wire version that did not exhibit the issue (if applicable): (not sure)
* Android OS version used to run Wire: Android 7.0
* Is this a custom firmware or a stock one: Stock
* Mobile phone model/manufacturer: HTC One M9
* Mobile network type (EDGE/LTE/Wi-Fi/Offline):3G + WiFi

## Details

Since yesterday, after launch, Wire briefly shows my home screen (with my icon in the top left, and my name in top center) and then immediately crashes on my Android phone.

Two things I observed before:

1) Someone texted me on Wire, but I could only see the notification + post on my desktop. The phone showed no notification. At this time, I still was able to launch wire on the phone, and there it shows the text.

2) later I answered the message I received in 1) on the desktop, also with a text message.  This message was a bit lengthy, about 2450 Characters.

After 2), I started observing the crash on launch on the phone.

What I tried, without success:

* Clearing app cache
* Restarting device.

## Link to Debug logs

Since the crash happens right on startup, I am unable to generate a Wire log. But I connected to the device via ADB and logcat gave me the following trace:

```
--------- beginning of crash
01-17 08:34:01.423 30491 30491 E AndroidRuntime: FATAL EXCEPTION: main
01-17 08:34:01.423 30491 30491 E AndroidRuntime: Process: com.wire, PID: 30491
01-17 08:34:01.423 30491 30491 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=90; index=90
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:207)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at android.text.SpannableString.setSpan(SpannableString.java:46)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at android.text.DynamicLayout.<init>(DynamicLayout.java:187)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at android.widget.TextView.makeSingleLayout(TextView.java:6912)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at android.widget.TextView.makeNewLayout(TextView.java:6810)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at android.widget.TextView.onMeasure(TextView.java:7164)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at android.view.View.measure(View.java:19850)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6141)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1117)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:642)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at android.view.View.measure(View.java:19850)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6141)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at com.waz.zclient.messages.MessageViewLayout.protected$measureChildWithMargins$36e9e238(MessageViewLayout.scala:102)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at com.waz.zclient.messages.MessageViewLayout$$anonfun$onMeasure$1.apply(MessageViewLayout.scala:1102)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at scala.collection.immutable.List.foreach(List.scala:392)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at com.waz.zclient.messages.MessageViewLayout.onMeasure(MessageViewLayout.scala:100)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at android.view.View.measure(View.java:19850)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:29994)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:589)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1767)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:356)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:887)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:689)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:616)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:873)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:173)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6523)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
01-17 08:34:01.423 30491 30491 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
01-17 08:34:01.424  1320  1368 E ActivityManager: App crashed! Process: com.wire
01-17 08:34:01.425  1320  1368 W ActivityManager:   Force finishing activity com.wire/com.waz.zclient.MainActivity

```

**Comment by NokiasSOFT** [comment] 2019-01-24 11:00
It was reported and fixed 2 versions back!
Timestamp bug!
Install last version!

**Comment by wiredOr** [comment] 2019-01-24 11:59
Hi, thanks for answering NokiasSOFT!

I updated to the latest version (3.25.685) some days ago. The crash is still there, with a very similar stack trace: ```--------- beginning of crash
01-24 12:59:11.564 14018 14018 E AndroidRuntime: FATAL EXCEPTION: main
01-24 12:59:11.564 14018 14018 E AndroidRuntime: Process: com.wire, PID: 14018
01-24 12:59:11.564 14018 14018 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=90; index=90
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:207)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.text.SpannableString.setSpan(SpannableString.java:46)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.text.DynamicLayout.<init>(DynamicLayout.java:187)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.TextView.makeSingleLayout(TextView.java:6912)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.TextView.makeNewLayout(TextView.java:6810)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.TextView.onMeasure(TextView.java:7164)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.View.measure(View.java:19850)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6141)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1117)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:642)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.View.measure(View.java:19850)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6141)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at com.waz.zclient.messages.MessageViewLayout.protected$measureChildWithMargins$36e9e238(MessageViewLayout.scala:102)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at com.waz.zclient.messages.MessageViewLayout$$anonfun$onMeasure$1.apply(MessageViewLayout.scala:1102)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at scala.collection.immutable.List.foreach(List.scala:392)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at com.waz.zclient.messages.MessageViewLayout.onMeasure(MessageViewLayout.scala:100)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.View.measure(View.java:19850)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:29994)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:589)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at com.waz.zclient.messages.MessagesListView.onLayout(MessagesListView.scala:152)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.View.layout(View.java:17632)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5633)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.View.layout(View.java:17632)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5633)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.View.layout(View.java:17632)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5633)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.View.layout(View.java:17632)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5633)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.View.layout(View.java:17632)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5633)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.View.layout(View.java:17632)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5633)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.View.layout(View.java:17632)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5633)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.View.layout(View.java:17632)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5633)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.View.layout(View.java:17632)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5633)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.View.layout(View.java:17632)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5633)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.View.layout(View.java:17632)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5633)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.View.layout(View.java:17632)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5633)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.View.layout(View.java:17632)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5633)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.View.layout(View.java:17632)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5633)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.View.layout(View.java:17632)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5633)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.View.layout(View.java:17632)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5633)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.View.layout(View.java:17632)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5633)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.View.layout(View.java:17632)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5633)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.View.layout(View.java:17632)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5633)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.View.layout(View.java:17632)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5633)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:750)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.View.layout(View.java:17632)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5633)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2463)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2169)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1310)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6550)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:887)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:689)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:619)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:873)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:173)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6523)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
01-24 12:59:11.564 14018 14018 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
01-24 12:59:11.567  1458 13731 E ActivityManager: App crashed! Process: com.wire
01-24 12:59:11.577  1458 13731 W ActivityManager:   Force finishing activity com.wire/com.waz.zclient.MainActivity```

**Comment by wiredOr** [comment] 2019-01-29 14:07
Issue still present in v3.26.694

**Comment by marcoconti83** [comment] 2019-02-11 17:46
Hi @wiredOr ,

Thanks for reporting. We will have a look at what happens with a similarly large message.

**Comment by marcoconti83** [comment] 2019-09-27 12:45
Hi @wiredOr ,
I tried with receiving messages of 4000k, both live (app in the foreground) and in the background/while offline, but I could not reproduce the issue.
Are you still in experiencing this crash? I wonder if you could somehow reproduce again with a message of the same size, to confirm that the size is indeed the issue.

**Comment by makingthematrix** [comment] 2020-03-12 16:52
I think I can safely close this bug now. Please reopen if crashes happen still for this reason.

**Closed by makingthematrix** 2020-03-12 16:52 UTC
Labels: bug
