### ISSUE TITLE
Expiring messages diabled when sharing an image from a third party app.

### ISSUE THREAD

**Issue by 2048-Bit** [wireapp/wire-android#1307] opened 2017-12-01 14:53 UTC
When a user shares an image from a third party app, to a wire contact via the official Android share function, the automatic message experation is turned off.  This only seems to occur when sending an image via share, and not when selecting the send image icon within Wire. 

To be clear, there is an option to set the image expiration before sending it to the user; however, it defaults to off. This also seems to occur regardless of which app you're sharing from.

## Environment

Wire Version: Android 3.3.374
Android 8.0.0 and all versions of Android 7.0  (have not tried older versions).
Stock Image 
Google Pixel 2
LTE/Wi-Fi

1. Open your favorite gallery app (I've tried QuickPic, Google Photos, and Snapseed).
2. Select an Image and choose "share".  
3. Select the "Wire" app your target share. 
4. When presented with a contact note that the timer is "OFF".  

IMHO the timer should follow whatever is already present for that particalar conversation.

**Comment by someoneEsle** [comment] 2017-12-06 08:02
Duplicate of #1282

**Closed by someoneEsle** 2017-12-06 08:02 UTC
