### ISSUE TITLE
Calls and video calls not working on self built android wire client

### ISSUE THREAD

**Issue by armetdev** [wireapp/wire-android#1892] opened 2018-11-28 12:53 UTC
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Wire).
Tell us what you were trying to do and what happened instead.

The self-built Android client crashes when accepting a call or video call.

## Environment

* Wire version that exhibits the issue: **master, release (checkout out 26.11.2018)**
* Last Wire version that did not exhibit the issue (if applicable): **2.40.357** works although the app crashes once the call is finished.
* Android OS version used to run Wire: **8.0.0** (on a Galaxy A5), **7.1.1** (on an Aquaris X5 Plus), **9.0** on a Nokia 6.1)
* Is this a custom firmware or a stock one: **Stock**
* Mobile phone model/manufacturer: **Galaxy A5 (2017)** (Samsung), ** Aquaris X5 Plus**, **Nokia 6.1**
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): **Wi-Fi**

## Details

Describe the steps necessary to reproduce the problem in more details. The detailed description
will help us to fix the issue faster.

Built the Android Wire client from the current sources as described in the repository (switched to branch release and executed ./gradlew AssembleProdRelease. The client seems to run fine until I accept a call, or somebody accepts my call. The app freezes and creashes, sometimes after about 4 seconds but most of the time immediately. Sometimes I even had to reinstall the app since it crashed on startup after that. I also tried to build the ProdDebug version, but the problem remains the same. This problem occurs on all listed devices.
Running version 2.40.357 calls and video call worked, although the app crashed after the call ended. On the Nokia phone calls did not work but i think this is a compatibility issue due to the Nokia running on Android 9.0 which was released just recently. Version 2.41.359 does not work anymore for me.
I found this working version thanks to:
https://stackoverflow.com/questions/51954483/android-wireapp-logs-unsatisfiedlink-error-wcall-set-video-send-state-when-at

Looking through various GitHub issues I got the impression that this has been a problem for a longer time and I would really like to solve this as I plan to use the Wire client for an upcoming project.

**Steps**
Build the app and start it, login or register, call someone from the contact list or get called by someone. Accept the call.
It does not matter if it’s just a normal call or a video call. Both crash the app.

## Link to Debug logs

Create a [GIST](https://gist.github.com) which is a paste of your Wire logs, and link them here.
It is recommended to directly contact our [customer support](mailto:support@wire.com) and send the debug report by email, because it can potentially contain some private information, that you don't want to share to the public.

Sent a mail to the support with the GIST link containing the error log.

**Comment by hub-ch** [comment] 2019-02-12 18:20
We everyone built from source have same problem
 "The self-built Android client crashes when accepting a call or video call." :(

https://github.com/wireapp/wire-android/issues/1499

@makingthematrix 
@someoneEsle @marcoconti83

>>At lease please check all common features and most important things such as audio/video calls facilities works properly or not when release a stable build.

> and let us know by add comment with release if there any known issues you guys aware when make a release

if that bug take time to fix, can be tell which old releases doesnt have that problem? or provide any temporally solution as ex: if possible fix by import certain old source files to last release so just we can have bit unstable but working app

**Comment by marcoconti83** [comment] 2019-02-12 19:10
Hi @hub-ch ,
On our build machines and my workstation it builds fine, so if it doesn't work for people checking out the source from scratch, there is probably a mismatch of AVS versions, we'll investigate in that direction then.

**Comment by marcoconti83** [comment] 2019-02-15 14:27
Hi all,
I just committed a bump to the AVS version (https://github.com/wireapp/wire-android/commit/8783cd0f8f14217458ab6e3fb0688a39782a6bda), please give it a try and let us know!

**Comment by hub-ch** [comment] 2019-02-15 20:36
@marcoconti83
 Still issue exist without any different as mentioned above

3.27 release
build worked fine includes some warnings
  (Env: android studio 3.3.1 (64bit) on new vm > loaded 3.27 (no changes or plugin update) > build

warnings - https://pastebin.com/qSLFJ0Sb
apk - https://transfer.sh/4mCEs/wire-prod-release-3.27.99999.apk

**Comment by hub-ch** [comment] 2019-02-16 06:33
@marcoconti83
Still issue exist without any different as mentioned above

3.27 Release
Build worked fine includes some warnings
Env: Android studio 3.3.1 (64bit) on new vm > modified avs version > Loaded 3.27 ( no change anything else or plugin update) > Build (prodRelease)

warnings - https://pastebin.com/qSLFJ0Sb
apk - https://transfer.sh/uCE3p/wire-prod-release-3.27.99999.rar (edit: link changed to correct apk)

**Comment by hub-ch** [comment] 2019-02-17 05:03
https://github.com/wireapp/wire-android/issues/1481

**Comment by hub-ch** [comment] 2019-02-17 05:04
https://github.com/wireapp/wire-android/issues/1154 (build works fine)

**Comment by marcoconti83** [comment] 2019-02-18 11:05
Hi @hub-ch ,

thanks for linking all the relevant issues 👍 

We are puzzled on why this is still happening - we'll run more test on our side and get back to you.

**Comment by hub-ch** [comment] 2019-03-12 16:05
@marcoconti83 "we'll run more test on our side and get back to you." sure next century 🔢 
i dont see if it solved yet on last releases, still not work. but while has proprietary working sources why dont find whats the wrong here? :(
wire enhance new features, fix bugs too slower, looks like no enough enthusiastic developers on team and might work on wire part time :D
  here +1 https://github.com/wireapp/wire/issues/260 something important facility. its related that and to do bit more task for both proprietary and opensource then during time can fix that bug together so hope may able to have some priority for move bit to top on work list :)

**Comment by marcoconti83** [comment] 2019-03-14 16:31
Hi all ,
The issues has been fixed with this commit: https://github.com/wireapp/wire-android/commit/cbddcea992a471440346149be8ade4cf9cd6daba. We tested it on a phone with a local build and we could not reproduce it anymore after the commit.

**NOTE**: the fix has been committed to *develop*. We switched the default branch from *master* to *develop*, so make sure that you are on the right branch before building.

If it still happens for you even after that commit, please re-open this issue. Thanks for your patience!

**Closed by marcoconti83** 2019-03-14 16:31 UTC
Labels: bug

**Comment by hub-ch** [comment] 2019-03-15 08:39
Solved.
  _thank you very much. just had to bother more ;)_
