### ISSUE TITLE
[Feature Request] Allow read/write messages, while having a call

### ISSUE THREAD

**Issue by boldt** [wireapp/wire-android#246] opened 2016-10-17 21:50 UTC
This is a FR: 
Unfortunately, it is not possible to read/write messages, while having a call.

**Comment by xtotdam** [comment] 2017-08-14 21:09
Hey! You say this is duplicate of #487 which is duplicate of #246 which is duplicate of #487 which is duplicate of #246 which is duplicate of #487.... I don't think I get it :)

**Comment by someoneEsle** [comment] 2018-06-13 12:53
Hey everyone! We just pushed a beta to the play store that adds this functionality. Let us know if you find any bugs!

**Closed by someoneEsle** 2018-06-13 12:53 UTC
Labels: Design, enhancement

**Comment by boldt** [comment] 2018-06-13 21:36
Nice to see, that my 2.5 years old issue got fixed. I'm looking forward to test it.
