### ISSUE TITLE
actice call when connecting to car

### ISSUE THREAD

**Issue by kroerig** [wireapp/wire-android#1360] opened 2018-01-02 22:35 UTC
## The problem

Every time I connect my phone to my car handsfree system while wire is running in backgroud my car displays an ongoing call (and so mutes the radio), which does not happen. Now I can either stop that call, which has no destination or terminate wire.
## Environment

* Wire version that exhibits the issue: 3.4.382
* Last Wire version that did not exhibit the issue (if applicable):
* Android OS version used to run Wire: 6.0.1
* Is this a custom firmware or a stock one: Sony stock ROM
* Mobile phone model/manufacturer: Sony Experia X3
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE

## Details

Have wire running in backgroud, connect to Volkswagen Composition Media Radio System via bluetooth.
Composition Media shows an active call as log as wire is loaded.

## Link to Debug logs

Create a [GIST](https://gist.github.com) which is a paste of your Wire logs, and link them here.
It is recommended to directly contact our [customer support](mailto:support@wire.com) and send the debug report by email, because it can potentially contain some private information, that you don't want to share to the public.

## How to send detailed debug report from Wire:

1. Go to Settings -> About
2. Tap "Wire swiss GmbH" 10 times
3. Reproduce your issue
4. Send the report from Settings -> Advanced -> Submit debug report
5. Go to Settings -> About
6. Tap "Wire swiss GmbH" 10 times again to disable detailed debug reports, because this slows down Wire

Will do the next time in the car.

**Comment by kroerig** [comment] 2018-01-05 18:16
I've sent a debug log to customer support.

**Comment by kroerig** [comment] 2018-01-05 18:20
<script src="https://gist.github.com/kroerig/5a6f67046ff68e98fd1a20184d696834.js"></script>

**Comment by pinki3** [comment] 2018-01-11 14:59
I experience the same problem, but with my bluetooth headset.

**Comment by pinki3** [comment] 2018-01-17 12:42
Now I'm starting to have this problem without even having the Wire app open.
Every other time, to "end the call" (put my bt headset out of call-mode) I have to open the Wire app and the close it. Please have a look at this, It's driving me nuts.

**Comment by SeoRoman** [comment] 2018-01-17 15:08
Agreed. The issue isn't wire being open, it's being active on the phone. You have to fully close the wire app in order to get your stereo to "disconnect the active (not really active) call" to be able to utilize your stereo again. 

This is also happening with my Android (Samsung Galaxy S6) + Mazda Cx9 Bluetooth.... so I'm assuming it's any bluetooth device. 

This is highly annoying as I can't do anything with my stereo until the wire app is fully closed and the system disconnects from the microphone. 

Other thing to note, I was NEVER on a call in wire, so for some reason it's accessing the microphone the entire time, even though it was never used. (so that's an issue)

**Comment by SeoRoman** [comment] 2018-01-17 15:09
Follow Up: The issue doesn't happen if your car is on, and THEN you open wire... it's only if wire is previously opened on your phone and either active or minimized and THEN you connect (start your car)... Highly annoying though :D

**Comment by kroerig** [comment] 2018-01-17 17:15
Yes, I can confirm that.

**Comment by MtMovo** [comment] 2018-01-18 10:33
Same issue here. Xiaomi Mi6, Android 7.1.1 and Peugeot 3008. @kroerig Thanks for posting the issue, i was scratching my head was could be the source of this madness :D

**Comment by kristin-wire** [comment] 2018-01-18 13:56
Hi all, thanks for flagging. Which bluetooth headsets are you using?

**Comment by luciusbono** [comment] 2018-01-23 23:01
I am having this exact issue on my Pixel 2 running stock Android 8.1 and Wire 3.4.382. 

I can reproduce this issue across EVERY device that I have that supports a headset profile via bluetooth, including the following: 

1. Sennheiser PXC 550 (headphones)
2. Phiaton 100 NC (headphones)
3. Sony SRS-XB30 (Bluetooth speaker)
4. Jabra Jambox (Bluetooth speaker)
5. Ford Sync 2 (car audio system)
6. Kenwood Car Audio System

I have to "hang up" the call on the bluetooth device or quit Wire in order for the media profile to kick in and allow media playback through the device. Quitting wire IMMEDIATELY resolves the issue. 

This issue is only present on connect. If I launch Wire after any of these devices has connected, the device remains on the media profile. 

I have two friends who are also experiencing this issue, one on a Pixel (running beta software) and the other on an Essential PH-1. 

I have also experienced this issue on a Moto G4 Plus running stock firmware (7.1.1 I believe). I still have that device and I am happy to wipe it and install Wire to confirm. I'm also happy to provide logs for any / all my devices.

**Comment by luciusbono** [comment] 2018-01-24 04:46
Reproduced this bug on my stock Moto G4 Plus. Repro steps: 

1. Wipe phone
2. Log in with Google Account
3. Install Youtube Update
4. Pair bluetooth headphones (Phiaton 100 NC)
5. Open Youtube and play random video
[Audio plays through headphones as expected]
6. Power off headphones
7. Install Wire
8. Log in to wire
9. Switch back to Youtube App
10. Turn on headphones
11. Headphones attempt to use headset profile (which is signaled by the headphones vibrating an extra time at power on)
12. Attempt to play Youtube, no sound
13. Switch to Wire App
14. Switch back to same Youtube video, press play, sound heard through headphones

I also, just for fun, tried just installing Wire straight away an not testing the headphones before installation and they still repro'd the issue. I'm happy to run through this as many times as necessary and provide any and all device logs. I even used a separate Google and Wire account for testing and still reproduced the issue.

**Comment by someoneEsle** [comment] 2018-01-24 09:25
Thank you for your detailed description! We're looking into it :)

**Comment by luciusbono** [comment] 2018-01-25 17:49
Wanted to provide an update to this thread: Wire support reached out to me (I had submitted my Debug log through support.wire.com) and they are going to try out a potential fix for this issue in the next Beta build for Android (which could ship as early as next week). Fingers crossed!

**Comment by SeoRoman** [comment] 2018-01-26 15:25
Woot! That would be AMAZING! So tired of dealing with this one... This will
solve "some" of the issues i have found with Wire

**Comment by kroerig** [comment] 2018-01-29 20:35
Got verion 3.6.91 on Friday and the issue seems to be fixed.

**Comment by luciusbono** [comment] 2018-01-29 21:36
@kroerig is that 3.6.391? I still experience the issue in 3.6.391 - and the devs said that a fix would be inbound this week (at the earliest).

**Comment by kroerig** [comment] 2018-01-31 15:38
Yes, it's 3.6.391. Something must have changed but till now it's working for me.

**Comment by luciusbono** [comment] 2018-02-01 17:31
Just wanted to report that 3.6.393 solves this issue for me (and another totally unrelated issue). Thanks for your hard work!

**Comment by someoneEsle** [comment] 2018-02-02 08:49
Cool, thanks for letting us know! I'll close this issue for now, but feel free to reopen if version 393 is somehow still not working (it's currently in beta, so people who are not beta testers will have to wait some more days).

**Closed by someoneEsle** 2018-02-02 08:49 UTC
Labels: bug

**Comment by Strit** [comment] 2018-02-21 08:23
So when is 3.6.393 gonna get to us regular users? This issue has annoyed me for months!

**Comment by cgarst** [comment] 2018-02-23 14:25
@Strit I just received a 3.7.398 update via Play Store containing this fix.

**Comment by Strit** [comment] 2018-02-23 16:31
Me too. And it worked! Thanks!
