### ISSUE TITLE
release build getting failed 

### ISSUE THREAD

**Issue by nikhilsh90** [wireapp/wire-android#439] opened 2017-01-05 08:04 UTC
Hi,

I am trying to build the project from the last one day but I get stuck with the same set of error each time. Even, I've tried to rectified this error but each build giving me same error. The error is related to XML parsing only. Can you please help me to rectify this error?

/wapp/wire-android/wire-ui/build/intermediates/res/merged/release/drawable/selector__icon_button__background__cursor_camera.xml:20: error: Error parsing XML: XML or text declaration not at start of entity

:wire-ui:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wire-ui:processReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

**Comment by JPonte** [comment] 2017-01-05 08:46
You need to have the `<?xml version="1.0" encoding="utf-8"?>` at the beginning of the xml file. That probably happened because the license plugin inserted the license text before that tag.

**Comment by nikhilsh90** [comment] 2017-01-05 11:41
I've tried both the ways. But still I am getting the same error. Do I need to remove license header from xml manually?

**Comment by JPonte** [comment] 2017-01-05 13:36
Those things that I told you should keep the plugin from adding the license again. But if it had already added then you have to remove it manually.

**Comment by nikhilsh90** [comment] 2017-01-06 13:29
Thanks! I was able to build the project from the last input. But I am unable to install the apk from android studio. I am sharing the screenshot of the error which I am getting in android studio while installing the apk.
![screen shot 2017-01-06 at 6 51 11 pm](https://cloud.githubusercontent.com/assets/12181217/21719158/286f042e-d442-11e6-94ac-7057b6b41f25.png)

**Comment by JPonte** [comment] 2017-01-06 13:34
Those messages are scala warnings. The error should be on the 'Run' tab. 
I would guess that the issue is that you have already the store version of the app installed there is a conflict since you're trying to build the release version with the same package name and different but different signatures.

**Comment by nikhilsh90** [comment] 2017-01-06 15:43
I don't have any installed version while building the release version. Previously, I had but I've uninstalled that before making the build. I do aware with the scala warnings but I am not able to figure out why its getting failed when build was successful.

**Comment by nikhilsh90** [comment] 2017-01-09 11:10
I am able to install the debug apk if I am generating it from the terminal. But If I am trying to run the app from the android studio then its getting failed always. Can you please guide me to run the app using android studio? If I missed something to run the app using android studio?

**Comment by JPonte** [comment] 2017-01-09 14:55
Can you show the error that occurs? 
Are you providing a keystore to sign the release version?

**Comment by nikhilsh90** [comment] 2017-01-12 11:16
I was able to build the app.

I want to change the package name. Is it possible to do the same? And what
is the way of changing the package name?

Thanks in advance!

On 09-Jan-2017 8:25 PM, "João Ponte" <notifications@github.com> wrote:

Can you show the error that occurs?
Are you providing a keystore to sign the release version?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/wireapp/wire-android/issues/439#issuecomment-271304250>,
or mute the thread

**Comment by JPonte** [comment] 2017-01-12 14:30
You should check the app build.gradle, and create a new flavour or change the existing.

**Comment by nikhilsh90** [comment] 2017-01-17 08:18
Hi,

I've changed the version number and version name in the gradle file. But I
am getting update page while opening the app. I know it's checking the
version code with the server that's why I am getting this page in the app.
Can you please guide me to stop checking the version code with the server
or guide me to resolve this issue?

Thanks in advance!
Nikhil

On 12-Jan-2017 8:00 PM, "João Ponte" <notifications@github.com> wrote:

You should check the app build.gradle, and create a new flavour or change
the existing.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/wireapp/wire-android/issues/439#issuecomment-272177074>,
or mute the thread

**Comment by NetE1** [comment] 2019-03-23 22:10
Hello,
@nikhilsh90 
1. Use a release or use release branch through studio and do not allow plugin update
2. You asked,
 "I want to change the package name. Is it possible to do the same? And what
is the way of changing the package name?"

             you can change it within default.json applicationID

3. "please guide me to stop checking the version code with the server"

              don't put lower version numbers than latest wire release. no update page appear 
                     or you can change that android layout or disable it.

4. Run ./gradlew command or build > generate apk

Follow instruction here https://github.com/wireapp/wire-android/issues/1892 to avoid a avs bug.

This issue able close now.

**Comment by marcoconti83** [comment] 2019-03-25 09:54
Hi @nikhilsh90 ,
this ticket is now 2 years old, is your question still relevant? I'm closing it for now, feel free to reopen if you figured out. Thanks @NetE1 for providing some hints!

**Closed by marcoconti83** 2019-03-25 09:54 UTC
Labels: help wanted
