### ISSUE TITLE
Messages, or notifications, greatly delayed 

### ISSUE THREAD

**Issue by forteller** [wireapp/wire-android#1279] opened 2017-11-21 15:38 UTC
I sent a photo to a friend of mine and he didn't get a notification about it until three days later. He's using the Android app. It could be that the message got delayed, but I'm guessing that it was actually the notification on the app that was delayed. Not that I know, of course.

I could ask him for the details about his setup, but it might take some time to get the answer ;)

**Comment by someoneEsle** [comment] 2017-11-22 12:38
Hi @forteller , thanks for getting in touch. Please always search for existing issues before opening new one -- this sounds like a duplicate of #254 and probably some others as well.
That being said, do you know if your friend is using google play services? We need more information to look into this. Phone model, operating system, wire version and all the fields you saw in the template when creating the issue are fundamental pieces of information that we ask users to provide so that we can better help them. :)

**Comment by forteller** [comment] 2017-12-04 13:41
Yeah, sorry about not providing more info at the start. I can't know for sure if it's the same issue, but I don't think so. Because my friend did get a notifiation about my message after three days, while that other issue says that messages are already marked as read.

My friend is using Wire 3.2.373 on the Fairphone version of Android 4.2.2 on the Fairphone 1. Hope that helps.

**Comment by someoneEsle** [comment] 2017-12-04 14:24
Could you show [this](https://support.wire.com/hc/en-us/articles/203624294-What-can-I-do-if-I-m-not-getting-any-notifications-on-Android-) to your friend?

**Comment by hub-ch** [comment] 2019-02-24 11:02
https://github.com/wireapp/wire-android/issues/777#issuecomment-466763316

**Comment by marcoconti83** [comment] 2019-04-08 12:18
Hi all,
there are a lot of duplicated issues covering this same problem (or a very similar one), let's unify all conversations and keep it going here: #777 . Closing this one and continuing there.

**Closed by marcoconti83** 2019-04-08 12:18 UTC
