### ISSUE TITLE
Black screen on launch

### ISSUE THREAD

**Issue by alien2003** [wireapp/wire-android#2756] opened 2020-04-07 09:34 UTC
**Describe the bug**
Black screen on launch after today update

**To Reproduce**
Update Wire mobile version for Android to 3.47.892 Beta, launch, get black screen.

**Expected behavior**
Wire should launch as usual

**Screenshots**
![signal-attachment-2020-04-07-123150](https://user-images.githubusercontent.com/11610652/78653451-ca8aa700-78cb-11ea-8687-ff7309c3dcd0.png)

**Smartphone (please complete the following information):**
- Wire version: 3.47.892 (Beta)
- Last Wire version that did not exhibit the issue (if applicable):
- Android OS version used to run Wire: 9
- Is this a custom firmware or a stock one: No, stock
- Mobile phone model/manufacturer: Planet Computers Cosmo Communicator (https://www.indiegogo.com/projects/cosmo-communicator/)
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): WiFi

**Comment by alien2003** [comment] 2020-04-07 09:51
Yellow line with "NO INTERNET" label appeared on top for a minute

**Comment by makingthematrix** [comment] 2020-04-07 09:56
@alien2003 : Hi. What was the version you updated from? Was it 3.46 or did you skip one or more updates?

**Comment by alien2003** [comment] 2020-04-07 10:22
@makingthematrix I am not sure, but I installed it ~7-11 days before from GPM and I was signed up for Beta. Everything was smooth before today

**Comment by makingthematrix** [comment] 2020-04-07 11:03
@alien2003 : Yes! If you can send us logs, that would be great. We can't reproduce this bug.

**Comment by IronJunkie** [comment] 2020-04-07 11:47
I'm seeing the same with this latest beta, screen is black as above, just clock, battery etc icons. Only difference is NO yellow bar at top, so internet access is good I assume. 

Essential phone stock Android 10 (latest Feb release), no mods

Also updated from previous beta release.

(Note: have access to location & contacts set to deny, changed location setting to allow, relaunched app, still the same)

**Comment by alien2003** [comment] 2020-04-07 11:59
@makingthematrix sorry, can't provide logs. Downgraded to the last stable and lost all my conversations (backups are also broken)

**Comment by android10** [comment] 2020-04-07 12:14
@alien2003 thanks for reporting. Fernando here to also help. 

**Quick question:** Are you using the app in landscape mode? I mean that is what I saw on the screenshot, which surprises me a bit since we do not support it yet.

**Comment by Sledge-Hammer** [comment] 2020-04-07 13:31
Just got the same issue on Android 5.1
Upgraded from 3.46.890 and got the black screen
Tried downgrading to 3.46.890 and 3.45.886 but the app is stuck on the loading shield... Went back to 3.47.892 and it's back to the black screen after the loading screen hides...
All the .apk files are downloaded from wire.com

**Comment by android10** [comment] 2020-04-07 14:28
@Sledge-Hammer thanks for reporting too. We will work on this and keep you posted on the progress. This is definitely an unexpected issue that is blocking all of you from using the app. 

BTW great username :heart: 

![hammer](https://user-images.githubusercontent.com/1360604/78681266-cc189700-78ec-11ea-8033-cd15018f6c50.jpg)

**Comment by kroerig** [comment] 2020-04-07 14:31
Same problem here. Just got version 4.7.892.
Android 9.

**Comment by android10** [comment] 2020-04-07 14:45
@kroerig @alien2003 @Sledge-Hammer @IronJunkie we are trying to reproduce the exact same scenario and we are struggling a bit. It would be super helpful if you can share the logs when you start the app. 

Also as an add-on and totally appreciated would be this information:

**Smartphone (please complete the following information):**
- Wire version: 
- Last Wire version that did not exhibit the issue (if applicable):
- Android OS version used to run Wire: 
- Is this a custom firmware or a stock one: 
- Mobile phone model/manufacturer: 
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): 

Thank you very much one more time for your time and effort. :heart:

**Comment by my-name-is-lad** [comment] 2020-04-07 15:49
Also having this problem after today's update. Installing Wire from scratch (in a work profile in my case) fixes the issue, except I no longer have my conversation history which is rather long.

Wire version: 3.47.892
Last Wire version that did not exhibit the issue (if applicable): The previous one, 3.46.890
Android OS version used to run Wire: Android 10, security patch from April 5.
Is this a custom firmware or a stock one: Stock firmware
Mobile phone model/manufacturer: Pixel 2 XL
Mobile network type (EDGE/LTE/Wi-Fi/Offline): Any

**Comment by disposablereviewer** [comment] 2020-04-08 00:57
Was on latest Pre-beta version and recently signed up for Beta to get this version today.
Stock OnePlus5 fully updated
Wifi

Steps:
1. Force quit wire
2. Open wire while watching logcat logs.

Logcat:
`2020-04-07 17:51:56.279 1356-3661/? E/ANDR-PERF-JNI: Iop tryGetService failed
2020-04-07 17:51:56.284 1356-3661/? E/ActivityTrigger: activityStartTrigger: not whiteListedcom.wire/com.waz.zclient.LaunchActivity/892
2020-04-07 17:51:56.284 1356-3661/? E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.wire/com.waz.zclient.LaunchActivity/892
2020-04-07 17:51:56.290 1356-11025/? E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.wire/com.waz.zclient.LaunchActivity/892
2020-04-07 17:51:56.638 1356-1368/? E/ActivityTrigger: activityStartTrigger: not whiteListedcom.wire/com.waz.zclient.MainActivity/892
2020-04-07 17:51:56.639 1356-1368/? E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.wire/com.waz.zclient.MainActivity/892
2020-04-07 17:51:56.661 1356-2648/? E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.wire/com.waz.zclient.MainActivity/892`

**Comment by android10** [comment] 2020-04-08 08:31
@my-name-is-lad @disposablereviewer thanks for the details. Totally appreciated it. We are working hard in order to fix this one. #2759 

We will keep you posted. :heart:

**Comment by kroerig** [comment] 2020-04-08 10:08
@android10 I added the requested information.

Can you say when there will be a fixed version. Luckily I can use Wire on my desktop, too.

**Comment by android10** [comment] 2020-04-08 12:27
@kroerig this is high priority. There should be a version of it between today and tomorrow. It is high priority for us since it is causing problems. 

2 potential solutions have been already pushed so far. We are generating a build and testing it internally.

**Comment by android10** [comment] 2020-04-09 13:16
Hey everyone. First of all thanks again for reporting. 

Some heads-up:

We were not able to 100% reproduce the issue at least internally. We got also other logs from other people but we did not see any potential patterns that provide more information about the issue. 

We also pushed 2 possible solutions: since we are migrating our codebase from Scala to Kotlin, a DB migration is required in order to move forward, so there were some schema changes that could have had an impact on this and for instance not letting the up to start normally (DB migration or schema changes happen at startup time).

We released a new beta and there were no new users experiencing this issue, so we are confident we might have solved it. This bring us to the point that for all of you that experienced this, the new apk will not solve the issue since you might have first to go to an older version of the app and afterwards update to the latest one. We are very sorry about this since this may lead to some data loss. 

I will keep you all posted. And please any feedback or input is more than welcome. :heart:

**Comment by kroerig** [comment] 2020-04-09 13:26
Is there any chance to rescue the existing data, e.g. with a separate wire backup tool?

**Comment by android10** [comment] 2020-04-09 13:30
@kroerig not as far as I know if you have not done a backup before. I will keep you all posted on further progress. Sorry for that, we are working hard to fix this issue asap.

**Comment by Sledge-Hammer** [comment] 2020-04-09 15:07
This is all I'm getting through logcat (after a fresh start of both 3.46.890 and 4.47.892):

```
W/linker  ( 8414): /data/app/com.wire-1/lib/arm64/libsodiumjni.so: unused DT entry: type 0x6ffffffe arg 0x10d00
W/linker  ( 8414): /data/app/com.wire-1/lib/arm64/libsodiumjni.so: unused DT entry: type 0x6fffffff arg 0x1
E/SQLiteLog( 8414): (1299) abort at 55 in [INSERT INTO ConversationsTemp SELECT * FROM Conversations]: NOT NULL constraint failed: ConversationsTemp.archive_time
E/SQLiteLog( 8414): (1299) abort at 55 in [INSERT INTO ConversationsTemp SELECT * FROM Conversations]: NOT NULL constraint failed: ConversationsTemp.archive_time
E/SQLiteLog( 8414): (1299) abort at 55 in [INSERT INTO ConversationsTemp SELECT * FROM Conversations]: NOT NULL constraint failed: ConversationsTemp.archive_time
```

So, am I understanding correctly that if the problem is with the existing history DB and downgrading to an older version of the app doesn't help there's no chance of it being fixed and I've lost all the history on the device?

**Comment by tokariu** [comment] 2020-04-09 16:29
What a meltdown! I also did an update from 3.46.890 to 3.47.892 and had the black screen issue. 
How could you release such a backend-changing update without checking it for stabilty first (QA anyone?). 

I had hopes that at least an update would fix the issue, but the moment you mentioned the update initiated a db conversion at the first start, I knew I've irreversible lost my wire-chat-history since the last full app backup.

Please people at wire, don't just code your app, also _use_ your app. sometimes and not just in this case, one could think you were just coding it without ever using it privately in RL, or otherwise a ton of issues would have been found before releasing the update.

**Comment by iGlaedr** [comment] 2020-04-10 12:11
same issue on oneplus 3t
rom: lineageos 17
wire version 3.47.892

**Comment by IronJunkie** [comment] 2020-04-11 02:36
@android10 
1) The new beta ver 3.47.893 still gets stuck at black screen on my device (ref my 1st post)

2) so I guess the database is corrupted or unrecoverable & downgrade won't now make it accessible, has anyone tried? (where can I find official  app ver 3.46 as I can't find old download page I used once before)

3) so we must "clear storage" or do a clean reinstall of new beta? Thus guarantee data loss.

4) If no possibility of a tool to recover database how about making it possible to select multiple posts or whole threads so contacts could forward theirs back to me in next release?

**Comment by my-name-is-lad** [comment] 2020-04-11 09:32
I can confirm, the new beta (893) is also affected. Furthermore, I managed to reproduce the bug using a backup from the previous beta (892).

Steps:
1. Make a fresh install of Wire;
2. When prompted during the sign-in, load the backup made in the previous beta (892);
3. Restart Wire;
4. Enjoy the black screen;

**Comment by disposablereviewer** [comment] 2020-04-11 20:05
Still failing for me as well.  New build's logcat on my phone below

OnePlus5 Stock latest update OTA

`2020-04-11 13:03:50.442 599-599/? W/hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.iop@2.0::IIop/default in either framework or device manifest.
2020-04-11 13:03:50.442 1356-2650/? E/ANDR-PERF-JNI: Iop tryGetService failed
2020-04-11 13:03:50.451 1356-2650/? E/ActivityTrigger: activityStartTrigger: not whiteListedcom.wire/com.waz.zclient.LaunchActivity/893
2020-04-11 13:03:50.452 1356-2650/? E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.wire/com.waz.zclient.LaunchActivity/893
2020-04-11 13:03:50.458 1356-2650/? E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.wire/com.waz.zclient.LaunchActivity/893
2020-04-11 13:03:50.578 22790-22842/? W/ROOM: Overriding migration com.waz.db.Migration$$anon$1@b49d734 with com.waz.db.Migration$$anon$1@43aa95d
2020-04-11 13:03:50.593 599-599/? W/hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.iop@2.0::IIop/default in either framework or device manifest.
2020-04-11 13:03:50.661 1356-2333/? E/ActivityTrigger: activityStartTrigger: not whiteListedcom.wire/com.waz.zclient.MainActivity/893
2020-04-11 13:03:50.664 1356-2333/? E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.wire/com.waz.zclient.MainActivity/893
2020-04-11 13:03:50.684 1356-2333/? E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.wire/com.waz.zclient.MainActivity/893
2020-04-11 13:03:50.714 22790-22790/? W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@41f3998
2020-04-11 13:03:50.762 18735-18735/? W/LauncherTransition: Failed to animate, surface got destroyed.
2020-04-11 13:03:51.979 801-2817/? W/SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen com.wire#0
2020-04-11 13:03:51.979 801-2817/? W/SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen com.wire#0`

**Comment by BehindTheBrain** [comment] 2020-04-11 21:36
Just mentioning another couple instances on multiple phones with Lineage Android 8.1. Hoping not to have to revert to the significantly older archives I made a while back.

**Comment by IronJunkie** [comment] 2020-04-13 04:34
@disposablereviewer 
that looks like zonealarm stopping upgrade (though I'm no bona fide coder so don't quote me 😜), I'm also running  antivirus I wonder if mine is doing the same. Antivirus app only shows .wirf activity, no details.

Wonder if others with black screen are running similar security programs, though your issue may be different to other peoples.

**Comment by Sledge-Hammer** [comment] 2020-04-13 15:01
I also don't have a recent backup, but have everything on another platform so finally completing the cross-platform history import/export feature might indeed be the best solution right now.

@IronJunkie - I don't have any security software installed and still got the black screen, so it shouldn't be the reason.

**Comment by disposablereviewer** [comment] 2020-04-13 18:04
@IronJunkie I also don't have a security software installed.  I just added the WARNs in the logs to give a little more context when I opened wire.  It's possible some messages were not related.

Also, I had an encrypted few month old backup of my android history and after uninstall/reinstall, the import failed.  nothing was imported.  so that's fun.  Are history imports also broken on android?

**Comment by android10** [comment] 2020-04-14 09:29
Hey everyone. Thanks for all the updates and efforts providing all this valuable information in order to fix the problem. We spent pretty much last week trying to solve the issue and it is a high priority one for this sprint. 

Some of you complained about releasing this (with a valid argument) but we tested it internally and it passed all our tests, that is why we are asking for all this information, since we still cannot understand why this is happening. 

We are trying to find a pattern here, let's say android version, app version, installed apps, number of accounts, size of the database, etc. 

We have not yet succeeded, but let me try to more clear on this so you have all the context and information to understand the current situation (this is important).

 - We are migrating our app to Kotlin because of no support for scala (our current language) in the android ecosystem which puts as a bit behind when it comes to innovation and using android functionalities. 
 - This is also a very legacy codebase with a lot of unknowns which difficult understanding 100% what is going on. Some past design decisions to speed up development are paying off right now due to the amount of technical debt we are suffering from. 
- Migrating the DB is a big step for us towards refactoring and rewriting the app and over this process we bumped into one of this unknowns I mentioned: we tested it internally and it passed our QA that is why we were confident to at least put it out there in our Beta Program. 

It is unfortunate that some of you loosed your data. Apologies for that. I hope you understand this situation. I will keep you posted during the week with the progress.

**Comment by Sledge-Hammer** [comment] 2020-04-14 15:02
@android10 - what beta program?
Version 3.47.892 was an officially released .apk on your website when I installed it (and it still is).

Please, prioritize the cross-platform history import/export feature, so at least some of us can restore the lost data, because so far it seems very likely that this won't be fixed and even if it gets fixed we probably still won't be able to get the history for the time between it occurred and the time it gets fixed unless we import it from another device...

**Comment by tokariu** [comment] 2020-04-15 09:53
> @android10 - what beta program?
> Version 3.47.892 was an officially released .apk on your website when I installed it (and it still is).

indeed, what beta program? I didn't take part in any beta program. Just downloaded the official .apk from the wire.com website.

**Comment by android10** [comment] 2020-04-15 10:23
@Sledge-Hammer @tokariu the original report came from a beta version we uploaded to Play Store. In any case we are still investigating the issue. 

> Please, prioritize the cross-platform history import/export feature, so at least some of us can restore the lost data, because so far it seems very likely that this won't be fixed and even if it gets fixed we probably still won't be able to get the history for the time between it occurred and the time it gets fixed unless we import it from another device...

@Sledge-Hammer Unfortunately it is not straightforward and as I said we are working on this. We have our priorities. Please be polite and bring up constructive feedback. This was not done on purpose.

**Comment by makingthematrix** [comment] 2020-04-15 16:55
Ok, so at least one mystery seems to be solved: that link was published too early. You all shouldn't have access to that version.

**Comment by android10** [comment] 2020-04-16 10:26
More updates: We will be merging this very soon: #2772. 

We are trying to rollback some changes and help you to recover from the crashes/missing data. We will keep you in the loop.

**Comment by android10** [comment] 2020-04-24 10:23
Hey everyone. More heads-up on this issue. After adding a couple of fixes + logs that you can check here: https://github.com/wireapp/wire-android/pulls?q=is%3Apr+is%3Aclosed

We have rolled out today a new **beta version: 3.47.909**. You have to use the one from Google Play because due to some confusion we got rid of the downloads from our website in order to have only one source of truth. 

We run all our tests again and again and we had a 98% success rate. The 2% of failures are just minor cosmetic issues that are on the way. 

![Wire 2020-04-23 at 3_31 PM](https://user-images.githubusercontent.com/1360604/80202660-443dc700-8626-11ea-80ae-013c2111dc31.png)

Any constructive input/feedback is more than welcome.

**Comment by my-name-is-lad** [comment] 2020-04-24 14:22
After updating to 3.47.909, all my chat history is gone for good.

Fortunately, I made a backup right before updating.

**Comment by makingthematrix** [comment] 2020-04-24 16:52
@my-name-is-lad : Yeah, sorry for that. We tried to come up with something that may help recover from that previous, bugged Beta version, but the chances were pretty low from the beginning :(

**Comment by iGlaedr** [comment] 2020-04-26 13:39
when will the next stable published ?

**Comment by makingthematrix** [comment] 2020-04-28 10:19
@iGlaedr : We're releasing gradually right now. On top of that, since stabilizing 3.47 took additional time, 3.48 will be coming soon.

**Comment by Sledge-Hammer** [comment] 2020-04-29 00:58
As I don't have a google play account I had to wait until you publish the .apk on wire.com and finally managed to install and test the latest version...
Now it just shows the message "Unfortunately, Wire has stopped" as soon as I login... even after I cleared my data and had to set it up as a new device, and even restarted the phone... also doesn't matter whether I install over the old version or uninstall the old one first... 

I'm sure that you'll fix this in a few versions from now... I can still use the old one until then... that's not the problem... the problem is I lost all of my history and since I'm not getting it back, it's time for a rant...


It took me more than half a year to convince everyone I know to switch to Wire... in less than 3 months about half of them abandoned it... some of them complained about the lack of other people using it, but most of them complained from the android version and how unusable it is... until now I disagreed with them because even full of bugs it did everything I needed, but without the history I've collected for almost two years and a way to import it from my PC it just became completely useless... after all I can't be 24/7 in front of the PC and the history contains stuff I need while on the go... and no, I can't remember to manually back it up every day or week...
I hoped that Wire will be my last messaging platform but after this experience it seems that I'll have to keep looking...
I'm pretty sure I'm not the only one who thinks that history is one of the most important features of a messaging platform and the way you guys implement it is just plain wrong...
I completely understand it not being kept on the server and the lack of auto sync when you login from a new device, but not being able to import it from another OS is simply unacceptable... what happens if I don't own a PC but only an android phone and decide to switch to an iOS device - that's right - if I want my history I can't!
This isn't a feature you have to implement 20 years from now, it's a core functionality that should've been there from day one and the current mishap just shows that I'm completely right.
And no - I'm not saying that you've introduced the current issue on purpose, I'm just saying that this would've been a problem for less people if they could just import their lost history from another device.
Not that I expect anything to change - it's much easier for you to lose some non-paying users than to fix what's actually broken in the platform...

**Comment by makingthematrix** [comment] 2020-04-29 08:21
@Sledge-Hammer : We're but a small team. We do what we can.

**Comment by tokariu** [comment] 2020-04-29 11:08
@Sledge-Hammer you're not alone.
It's all the same here with my circle of friends. It took me/us a lot of time and effort to make (most of) them replace whatsapp or install Wire as 2nd IM app (more often 3rd, 4th). We literally lose friends jumping off the Wire-ship every week now.
They are all done with the technical problems and the new course the Wire management took (you know, the story that the Wire Swiss GmbH was taken over by the american Wire Group Holdings Inc. and Wire was holding back this information for almost a year losing serious trust, aswell as the new direction of Wire towards business/enterprise customers, neglecting personal users, exchanging 'privacy' with 'security', etc.)
Many friends are unfortunately getting back to whatsapp and telegram, some to signal or threema and a few are trying out new things like matrix/riot and the like. Only a little core is left who don't want to tinker around so much or still don't want to use phone numbers for apps. You can count the days until the last one has left Wire.
Personally I regret how things are turning out for Wire and for us personal wire users. There was such a big potential but it didn't fulfill.
There are still reasons to use Wire, though. It has some features that other IM apps don't have (like open source, no phone numbers, multi-client syncs, multi-accounts, very special and very niche features but important to those who care). But the others are getting there too and even beyond with new features (free group video calls in corona times!), so at some point, there would be no reason to still mess around with wire's problems.

@android10 @makingthematrix and the rest of the wire dev team
we know you are a small team and you don't get the ressources needed to handle all these problems. we still appreciate your effort and hard work trying to fix all these issues. we believe you are not directly responsible for the course the Wire management took. However, it seems to be a tilt at windmills with all the things happening lately and maybe it's also the intention of the management to get rid of us personal users in the end.

about the black screen issue:
I won't upgrade to new versions until the update is bulletproof. I already lost my history and after restoring a backup I was suddenly losing new messages (not getting them decrypted) until I reset all the sessions for my clients and friends. I'm not going to risk that again, sorry therefor.

**Comment by makingthematrix** [comment] 2020-05-04 09:14
Hi all,

We have just released a hotfix which should fix the crash on Android 5 & 6 and force-refresh conversation lists. The new version is 3.47.911. It may take a while until Google Play Store make it available. Let us know if it worked.

Cheers,

**Comment by IronJunkie** [comment] 2020-05-05 07:08
FYI
My contacts chat reappeared after I received the updated to .909 beta version, which was a nice surprise, but sadly not the group conversations. So your attempt to recover some data may have been partially successful, for some people.

Also I had cloned the original faulty app giving it a fake phone identity as a temp fix for black screen issue on my phone ,which worked, but of course no chat history (as expected as Wire seeing a new device), so could have been why my chat history reappeared, though I would be surprised if this was the reason.

**Comment by IronJunkie** [comment] 2020-05-05 07:53
Update:
it seems even my group chats are now recovered after updating to ver 3.47.911 & the reason they were not showing was to do with the group chat issue on 909 release (I guess). So nice to have group chats history back as well.

**Comment by makingthematrix** [comment] 2020-05-06 12:28
Great!
I'll keep this issue open until the end of the week, just in case.

**Comment by tokariu** [comment] 2020-05-06 22:59
I hope there is something you (wire team/management) can take with you from these issues lately. don't just close this and consider it done, because this issue was just the tip of the iceberg of way more fundamental issues.

Wire lacks detailed communication and transparency with it's users about incidents (technically aswell as economically ['wire holding']), and lacks more than ever stability and quality assurance.

Together with all the tiny but plenty issues people were complaining about since years that have never been worked on, it's not really hard to scare users away from using wire any longer.

I'm a Wire user since 2016 and I brought many friends to Wire over these years.
Now it's 2020 and over 2/3 of those friends quit using Wire, the most in the last few days. They went back to competitors due to the exact critics I named above.
It's really disappointing considering the amount of time used to get them all to use Wire instead of the much more popular competitors - just to lose them again now.

**Comment by makingthematrix** [comment] 2020-05-07 08:41
@tokariu : To be honest, I think we are very transparent. You can basically see all our work here, on GitHub, in public. Decision-making, documentation, code reviews, PRs, and releases. Bugs are being fixed and new features are being added all the time. And you can track it all. 

Personally I don't believe we can move forward without making some breaking changes and occasional mistakes. We're in the middle of a massive refactoring (that too you can track on GitHub). We wouldn't be able to do it if we were afraid to take risks. Those changes are needed in order to make the app much more stable and performant in the near future.

**Closed** 2020-05-08 13:37 UTC

**Comment by tokariu** [comment] 2020-05-08 17:09
@makingthematrix I was thinking of a different kind of transparency.

transparency in the sense of:
- why you prefer fixing issues x,y,z and not a,b,c. Or why you think issue x,y,z deserves higher priority than a,b,c. (when a,b,c are everlasing open issues wanted by users)

or non technically transparency.. 

- why Wire moves away from private users towards enterprises, replaces "privacy" with "security" etc, why it's gonna be sold to a holding in the USA without telling it's users for so long... 

I don't see transparency here. This really bugs me.

regarding technical issues:
we wire users often don't understand why so many little issues don't get the attention. many of these little issues could get fixed by like 3 lines of code, yet they aren't fixed even after years.

it looks for us like you set priorities to issues that you find most important and everything else gets just postboned endlessly, because there are always issues with higher priority. 

I said it once and I say it again:
Wire needs at least 1-2 days a week where all coding ressources are only dedicated to fixing bugs and lower priority fixes/features. and all the rest of the week and time you could devote for the higher priority issues. 
that way, the lower priority features are not getting postboned forever and the higher priority issues don't lose too much ressources.

of course it's your decision how to adjust the time table. but the status quo shows there is seriously something lacking regarding stability, QA and fixing the many smaller issues.

I understand that some issues must have priority, though. For example, currently you can't call and videochat with wire-desktop and wire-web with chromium browsers which renders the app useless. Such issues naturally needs to be fixed first, but even these issues are postboned now and we don't get information as to why? a little feedback after the issues get recognized and sorted out would be damn good.

> Personally I don't believe we can move forward without making some breaking changes and occasional mistakes.

I strongly DISAGREE. Never, under no circumstances, should anything ever break something for the live- and enduser. You can break things for test, nightly, alpha and beta users, they know which risks they accepted when using these versions. But endusers count on stability and availablity. Both of these were not given the last couple of weeks. Many people have lost their complete history. And these users were in no way beta users (-> due to the fact you released the beta version as public apk for live users) This is really something Wire could have predicted and managed better before!

I hope all the points I mentioned above get discussed Wire internally, they are really important.

**Comment by makingthematrix** [comment] 2020-05-10 10:05
@tokariu : So we will not agree. Okay.

I can assure you that GitHub can give you a very good insight into how we make decisions about what can we do and when. If you see a bug or a feature which is being postponed and you think it can be easily done, we invite you to open a PR. We will help you with code review and we will be happy to merge it.

**Comment by iGlaedr** [comment] 2020-05-14 12:19
Hi me again.
My issue was fixed on my old phone by installing a newer version. My phone broke.
I got a new an istalled wire on it restored from a new backup. Wire worked a few hours and now i'm back to the black screen.

The new phone is a ond plus 6 eith oxygen os 10.3.2 wire version 3.48.915
thx
