### ISSUE TITLE
Camera exposure

### ISSUE THREAD

**Issue by Da0012** [wireapp/wire-android#1808] opened 2018-09-27 17:21 UTC
## The problem

The camera does not adjust the exposure well, many times it is necessary to use the smartphone camera,at night it is not possible to make a video call (the smartphone camera works well, whatsapp's and other applications too.).

## Environment

* Wire version that exhibits the issue:3.18.650
* Last Wire version that did not exhibit the issue (if applicable): any version before the previous month
* Android OS version used to run Wire: 7.1.1
* Is this a custom firmware or a stock one: stock
* Mobile phone model/manufacturer: zenfone 4 max
* Mobile network type (EDGE/LTE/Wi-Fi/Offline):

**Comment by someoneEsle** [comment] 2018-10-16 09:17
Sounds like a duplicate of https://github.com/wireapp/wire-android/issues/671

**Closed by someoneEsle** 2018-10-16 09:17 UTC
