### ISSUE TITLE
Enable 2FA (Two Factor Authentication)

### ISSUE THREAD

**Issue by fakeid30** [wireapp/wire-android#1190] opened 2017-10-13 15:19 UTC
Please enable users to use Authy / Google Authenticator / SMS based two factor authentication.

**Comment by mimkorn** [comment] 2018-04-03 07:35
Looks like a duplicate of https://github.com/wireapp/wire/issues/85

**Closed** 2018-04-03 08:07 UTC
Labels: enhancement

**Comment by v3EtBhYE** [comment] 2019-10-20 06:07
Is mfa coming anytime soon?
