### ISSUE TITLE
log in required when phone is restarted

### ISSUE THREAD

**Issue by Be-ing** [wireapp/wire-android#531] opened 2017-01-25 06:08 UTC
When my phone restarts, I have to log into Wire again. This is confusing, especially because Wire asks to reregister; logging in without reregistering is not obvious. Even now that I am aware of this, it is difficult to remember and I sometimes miss messages until a while later because I am not logged into Wire.

**Comment by someoneEsle** [comment] 2017-01-25 18:20
I cannot reproduce consistently on my Nexus 5X, Android 7.1. I just rebooted, but Wire was working as expected. However I've had this issue too recently -- not sure what the cause is. I've also had several friends reporting that Wire had logged them out (they all use Android, some of them have only one device, so it's probably an android-only issue).

**Comment by bjoernherbig** [comment] 2017-01-26 09:29
Thanks. This is a bug we are investigating.

**Comment by makingthematrix** [comment] 2020-05-07 11:28
I think I cna safely close this issue now :)

**Closed by makingthematrix** 2020-05-07 11:28 UTC
Labels: bug
