### ISSUE TITLE
Sometimes newly written messages do not appear in chat log

### ISSUE THREAD

**Issue by ghsrcgh** [wireapp/wire-android#1254] opened 2017-11-08 02:03 UTC
Sometimes newly written messages do not appear in chat log. You may write a few messages, they are really sent, but not visible (not appear) in chat log. Like they does not exist.

Workaround: close the WIRE app and restart it. Then you will see sent messages.

I do not know the reason why this occurs, but this bug I see periodically.

**Comment by someoneEsle** [comment] 2017-11-08 09:10
Thanks for reporting, this sounds like a duplicate of #1174. Actually there is no need to restart the app, as opening a different conversation and coming back to the initial one fixes the problem. It's a bug we have been working on recently.
Again thanks for reporting, but please look for issues before opening new ones :)

**Closed by someoneEsle** 2017-11-08 09:10 UTC

**Comment by ghsrcgh** [comment] 2017-11-12 02:20
Probably it is a dupe, but in my case opening a different chat and coming back does NOT help - messages are NOT shown. I had tried it a lot of times. Only restart of app is helping to see the sent messages.
