### ISSUE TITLE
Feature request: Playing voice-messages over the phone's earpiece

### ISSUE THREAD

**Issue by t-aus-m** [wireapp/wire-android#1349] opened 2017-12-25 11:58 UTC
Basically every other recognized instant-messenger has this, so here is my request to include this in Wire is well:

The ability to hear to voice-messages with the earpiece of my phone.

E.g. WhatsApp realizes this by using the distance-sensor. When you start playing a voice-message and then put your phone up against your ear, the phone detects the low distance and routes the audio to the earpiece.

We all know, how everybody hates people hearing to their voice-messages at the tram aloud, so please implement this! ;) (And yes, I just assumed, that everybody hates them.)

**Comment by someoneEsle** [comment] 2017-12-27 07:34
Thanks for reporting, this is a duplicate of #1175. You can upvote that ticket.

**Closed by someoneEsle** 2017-12-27 07:34 UTC
