### ISSUE TITLE
Password Protection

### ISSUE THREAD

**Issue by 5an1ty** [wireapp/wire-android#289] opened 2016-11-04 21:06 UTC
This is an issue for both mobile clients, would it be possible to add a simple pin code to unlock the app?

**Comment by someoneEsle** [comment] 2016-11-05 17:56
Duplicate of https://github.com/wireapp/wire-android/issues/13

**Comment by bjoernherbig** [comment] 2016-11-07 15:27
something we want to do, we don't have a timeline on this though. it's a capacity/priorisation issue

**Comment by Be-ing** [comment] 2016-11-14 06:54
I recommend encrypting your entire phone storage.

**Comment by KillingSpark** [comment] 2016-12-06 07:17
Hey just asking if I'm thinking of the right thing:
Could one implement an Password-checker Activity and out of that activity start the AppEntryActivity?

**Comment by PyRoAcIdK** [comment] 2017-01-31 22:48
+1. I believe that you should be able to lock the application with either a pin or pattern, either per open or for a certain period of time. This could be basic to begin with but later offer more protection with higher encryption mechanism, no visible information when it's on the task manager, etc further down the track.

You can have end to end encryption and encryption on your hardware, however, if someone has access to an unlocked device (e.g under duress), they have full access to the content, which reduces the effectiveness of the whole system.

**Comment by baimafeima** [comment] 2017-11-20 19:08
Not sure why this thread did not receive more attention. In order for me to use Wire on my Android devices, it is _mandatory_ that I can `PIN-lock` it. Quoting @mrbiber who opened #13 

> As, for example, Signal does it (i.e. the app is running and can receive messages, but to read them you need to enter the PIN which then unlocks the app for a configurable period of time). Of course, that feature should be optional.

There are many use cases for this feature: 
- Android-based mobile devices are not only significantly less secure than Linux-based desktop operating systems but they are also much more subject of attention from anyone who happens to walk by the device (e.g. when being at a party) and generally get lost more frequently than desktop- or laptop devices. 
- The display or phone needs to be repaired with granting someone (under your eyes) temporary access to your device. 
- Even a basic privacy-focused email provider such as ProtonMail (and I don't consider them the best in terms of either security or privacy) has this feature: https://protonmail.com/blog/protonmail-vs-gmail-security/
To quote Irena M. from their team: `There security features are available across all our platforms, even Android. For extra security, you can also enable PIN lock on Android to protect your emails in case somebody unlocks your phone.`

Again, unless this feature is available, I do not recommend the use of Wire on any mobile device.

**Comment by manasb** [comment] 2017-12-01 06:19
I logged on to suggest the same thing. Thank you for creating this issue @5an1ty - @baimafeima raises excellent points as well, thanks.

If I, or anyone else, were to lend my phone to a family member, or a friend, I would want to be able to specifically allow them to view my Wire messages. Currently, if my phone is unlocked, all of my Wire notifications/messages are readable, and unauthorized messages can also be sent - these will appear to the receiver as being legitimate. I imagine it would also be possible for someone to send a message and delete it on my end only.

It is possible to improve the privacy of Wire messages by using 3rd party applications such as [Privacy Knight](https://play.google.com/store/apps/details?id=com.ali.babasecurity.privacyknight&hl=en) and [CM Locker](https://play.google.com/store/apps/details?id=com.cmcm.locker&hl=en) (and many others) to **(1)** ensure that notifications from Wire do not include any information about the sender or the messages they have sent and **(2)** Requiring a PIN, Pattern, Fingerprint (or other forms of authentication) to unlock the application for reading & sending messages. These applications do have their own quirks/bugs/limitations, however. One of them is that there can be a short lag between opening the "locked" appplication, such as Wire, and the PIN/Pattern/Fingerprint/etc. prompt being displayed. In that lag it is possible to read messages or the contacts list, depending on the last open screen in Wire. Additionally, the full Wire screen can be viewed through the application switcher mode on Android, even if the application is "locked" - displaying a plain window with the Wire logo could be an improvement to privacy.

If these features (application lock, notification privacy, preview window privacy) were implemented directly in Wire, they could be implemented in a much better manner and 3rd party privacy tools (which do not seem to be open source) can be avoided.

**Comment by forteller** [comment] 2018-09-13 20:33
I'd like to bump this issue. I recently convinced a friend to use Wire in addition to Signal and Telegram. Not something people like to do. She now asked if she could lock the app, since she's used to that from both Signal and Telegram, and thought that is a normal and necessary security measure. I felt really bad when I had to tell her no.

Please look into this issue now!

I'd like to add that there should also be a setting to add a timer to the web app version of Wire for locking the app after X minutes. 

Thanks!

**Comment by tiagoad** [comment] 2018-10-02 12:04
I also recommended Wire to a friend and then found while setting it up on her phone that it offered no option to lock the app. I was forced to switch to Signal, which only has phone number authentication, as I find it to be an essential feature if you want to seriously approach privacy and information security.

Thinking about this lead me wonder about the measures taken to protect the Wire data on disk. Is it encrypted? Are deleted messages and images purged from cache?

I'll take a deeper look at the code and maybe contribute some.

Thanks :)

**Comment by northvik** [comment] 2019-01-18 12:00
I just found out that you can't add a pin to lock the app.
That's quite disappointing.
It feels a bit like it's missing a big point of the safety of the app.
it doesn't change the fact that Wire is a great app in my point of view.
Continue the good work
Thanks :)

**Comment by KaKi87** [comment] 2019-02-24 09:42
+1

**Comment by nikolayhg** [comment] 2019-03-17 21:13
+1

**Comment by marcoconti83** [comment] 2019-11-27 08:59
Hi all,
I'm going through the old comments, sorry for late update. 
This feature is now available on the app!

**Closed by marcoconti83** 2019-11-27 08:59 UTC
Labels: enhancement

**Comment by KaKi87** [comment] 2019-12-01 13:57
Oh really ? @marcoconti83 Where is it ?

**Comment by KaKi87** [comment] 2019-12-16 09:47
Please have a look at #2483 and #2485, thanks
