### ISSUE TITLE
Click on notification does not open the corresponding conversation

### ISSUE THREAD

**Issue by lab34** [wireapp/wire-android#1700] opened 2018-08-03 14:54 UTC
Hello,
## The problem
When I'm receiving a notification from a friend called John, if I click on it, it opens wire inside the last conversation I was browsing (for exemple Bob). It's annoying if you chat alternatively with Bob and John at the same time. You always open the wrong conversation. You have to click back and choose the good one.

Plus, it can be very confusing if you chat with Bob in a group conversation, and in one to one, in the same time.

## Environment
Wire 3.14.628 on Android 7.1.2 (MIUI 9.5.10.0)

Best regards.

**Comment by lab34** [comment] 2018-08-06 10:04
Hello, here are the steps:

- You already have Bob in your Wire contacts
- create a group called "Family"  and add Bob in it. (and other guys/girls)
- Text "Hello" inside the group and close wire
- Bob reply "Hi" to the group Family, your receive the notification
- You click on Bob's notification: you read "Hi" on the group Family
- You close wire, lock your phone
- Bob send "Hello my friend" just to you (not the Family group)
- You received Bob's notification, click on it: this open Wire in the same state it was opened before: inside the family group, not inside the Bob conversation

**Comment by someoneEsle** [comment] 2018-08-06 13:53
Still can't reproduce, but we'll keep an eye out. Thanks for reporting!

**Comment by makingthematrix** [comment] 2020-05-07 12:25
I think this should be fixed by now? I'll close the issue. Please reopen if anything like this happens again.

**Closed by makingthematrix** 2020-05-07 12:25 UTC
