### ISSUE TITLE
Voice calling isn't working.

### ISSUE THREAD

**Issue by valera911** [wireapp/wire-android#905] opened 2017-06-05 11:33 UTC
Hello.
Voice calling has been broken after last update.
I'm using android 7.1.2 without google play services on my asus z00a (x86).
When i try to touch on the call button nothing happens.

**Comment by david-wire** [comment] 2017-06-08 13:14
Hello, thanks for reporting. We are aware of this issue, could you send us some logs?
1. Go to Settings -> About
2. Tap "Wire swiss GmbH" 10 times
3. Reproduce your issue
4. Send the report from Settings -> Advanced -> Submit debug report and include a note so that we can identify it.
5. Go to Settings -> About
6. Tap "Wire swiss GmbH" 10 times again to disable detailed debug reports, because this slows down Wire
We will then follow up accordingly.

**Comment by revpp** [comment] 2017-07-21 22:20
From time to time it's happening to me as well. "Force stop" needed to make it work again. Most of the time it happens when established conversation fails & I try to make another one immediately after.

**Comment by makingthematrix** [comment] 2020-02-27 09:30
Ok, I guess I can close this ticket at last. Please reopen if the problem still occurs.

**Closed by makingthematrix** 2020-02-27 09:30 UTC
Labels: bug
