### ISSUE TITLE
After Entering Authorization Code, Wire Shows the User a Blank Activity Screen

### ISSUE THREAD

**Issue by jvarghe** [wireapp/wire-android#681] opened 2017-03-04 16:30 UTC
My friend and I had Wire installed on our Android phones. Wire logged out on both our phones about one week after we installed it. I don't know if this is a bug, but let me describe another bug my friend ran into when he tried to re-authenticate his device.

My friend has Android 5.1.1 on a Nexus 4. He had Wire send him an authorization code over text message. When he typed it into the app, the next Activity screen was blue, but completely blank. He was stuck and asked me to fix it. I fixed this issue by pressing the back button, and submitting the code again. This time, the app worked correctly.

**Comment by bjoernherbig** [comment] 2017-03-06 08:13
thanks you for reporting. could you please provide the version number you were using?

**Comment by jvarghe** [comment] 2017-03-06 19:31
He's running version 2.28.317. I don't think he's updated since hitting the bug.

**Comment by bjoernherbig** [comment] 2017-03-08 07:29
@red-avtovo

**Comment by bjoernherbig** [comment] 2017-03-13 14:01
cannot reproduce this. closing it for now.

**Closed by bjoernherbig** 2017-03-13 14:01 UTC
