### ISSUE TITLE
Incoming Cell Phone Call Makes Wire Call Disconnect

### ISSUE THREAD

**Issue by liocalset** [wireapp/wire-android#541] opened 2017-01-26 19:43 UTC
Hello,

I was on a wire audio call on my Android device when I received a call over the cell phone network from a suspected spammer. Receiving that call made the wire call disconnect, without answering it or pressing anything on the screen such as "Dismiss". I then tried reproducing this issue by calling my smartphone from a second phone while on a wire call and am able to make this happen 100% of the time. So to recap, all it takes for a wire call to automatically disconnect is for a call from the cell network to come in with no interaction from the user.

Device Specs:

Android 6.0.1
wire version 2.26.307

Also see: #415

Thanks!

**Comment by someoneEsle** [comment] 2017-01-26 20:36
Wait, so you know this is a duplicate of #415 and you still posted it?
https://giphy.com/gifs/teamcoco-crying-cry-l2JhtKtDWYNKdRpoA

**Comment by liocalset** [comment] 2017-01-26 21:58
I found your fairly poorly written issue which was completely lacking in essential details after I posted mine, since you asked. Ever consider that case?

**Comment by someoneEsle** [comment] 2017-01-26 22:01
**# You know you can post comments under my issue, right?** Also, I don't expect everyone to appreciate my ability to briefly explain problems. And by the way, I attached a debug log. Enough said.

**Comment by liocalset** [comment] 2017-01-26 22:20
Well your bug went unfixed probably because you didn't write it up right. Reading it, it looks like something a little kid wrote. There's a difference between briefly explaining a problem and a total wanton lack of effort and/or incapability to perform the task.

I am sorry that you are so offended that I opened up an issue after not seeing yours, the one that was so artfully and masterfully written...Now can you stop trolling here please. Thank you.

**Comment by someoneEsle** [comment] 2017-01-26 22:28
I'm not offended that you're wasting the developers' time by creating duplicate issues instead of commenting on existing ones. The issue I reported is known and will be fixed as soon as the developers get more time for fixing bugs. I hate to break it to you, but opening a duplicate issue won't speed things up. If the developers hadn't understood my report, they would have asked for a better explanation. And even if it was badly written, clearly it was good enough for you to find it, hence you should've posted a comment there instead of opening a new issue. Your logic is flawed pretty badly, my friend. Best of luck.

**Comment by liocalset** [comment] 2017-01-26 22:31
I just said numerous times that I found it **AFTER**...get it? **After** I posted my issue. I went back in and edited my issue and referenced the idiotic one that you wrote. I know that is really complicated for you to comprehend.

If anyone is wasting developer's time it's you. You are still here trolling because you apparently have some issue with someone writing up a bug report better than you ever could. Read mine and learn how it's done.

**Comment by someoneEsle** [comment] 2017-01-26 22:34
Sorry but this is still a duplicate issue. The standard behaviour among civilised adults is to close duplicate issues, and comment on the original one instead. Next time you write an issue include a bug report, that's a lot more useful and interesting than your conspiracy theory on the "suspected spammer" ;)

**Comment by liocalset** [comment] 2017-01-26 22:35
Once again, you are showing that you are an idiot. That is part of the Android system which says "Suspected Spammer" in big bold letters. You really are dense; probably the dumbest person I've ever seen on GitHub.

**Comment by someoneEsle** [comment] 2017-01-26 22:38
What's the point in mentioning it if you can consistently reproduce? Or are you flagged as suspected spammer too? lol.
This is still a duplicate issue, just close it.

**Comment by liocalset** [comment] 2017-01-26 22:40
I am not closing the issue as your title is stupid and your issue that you wrote up is writted stupidly. Have a nice day and enjoy trolling more on the internet, since you obviously have nothing better to do.

**Comment by someoneEsle** [comment] 2017-01-26 22:43
I know yours is "writted better", but you can improve #415 with your elaborate language. This is still a duplicate issue. Have fun being trolled on the internet, obviously trolls can tell who will feed them.

**Comment by liocalset** [comment] 2017-01-26 22:46
Right. Once again, have a nice day...or a better one tomorrow.

**Comment by someoneEsle** [comment] 2017-01-26 22:48
I will always be here in case you want to close the issue or learn more about irregular verbs. I'll be waiting for you :cupid:

**Comment by liocalset** [comment] 2017-01-26 22:49
I am sure you will be waiting for any and all attention anybody gives you. Hopefully someday you will realize how disruptive you are.

**Comment by someoneEsle** [comment] 2017-01-26 22:52
"Destructive" is when you keep an issue open even though you know it's a duplicate of an issue that has already been labelled as bug and assigned to a developer.
This is still a duplicate issue.

**Comment by liocalset** [comment] 2017-01-26 22:54
No, destructive is when you keep trolling a thread because you have to have the last word and had already been politely asked to **stop**.

**Comment by someoneEsle** [comment] 2017-01-26 22:55
Still a duplicate issue.

**Closed** 2017-01-27 22:35 UTC
