### ISSUE TITLE
Can't see medias

### ISSUE THREAD

**Issue by Paviluf** [wireapp/wire-android#518] opened 2017-01-22 13:52 UTC
Hello,

I can't see the medias (images, audio, videos, drawing, gif, files) that are sent to me. I just see a white square or I have a message that the download of the file have failed. The rest of the feature (audio and video call) seem to work. I have a Motorola Razr i (x86) on CM11 (without any Google stuff) with Wire 2.25.305.

Thanks !

**Comment by Paviluf** [comment] 2017-01-22 16:00
Maybe related to https://github.com/wireapp/wire-android/issues/220

**Comment by Paviluf** [comment] 2017-01-23 05:40
After more tests I updated the first message accordingly.

**Comment by hThoreau** [comment] 2017-01-30 20:06
I believe I'm experiencing this same problem. I can send and see the images and videos that I send, but not those that are sent to me. I use a modded version of android, having removed Google's dependencies as well (as much as I could, at the very least). Those who I talk to, who also use Android, do not suffer from this issue. To be more specific, I'm using a Sansung Galaxy Tab 3 with an Android 4.2.2 kernel version 3.0.31, and my interlocutor is using a Motorola Moto E and an Android 6.0. Both of us are using Wire 2.24.303. An by the way, when am I going to see you guys at Debian's repository? ;)

**Comment by Paviluf** [comment] 2017-02-01 04:50
Here is a log 
[wire-2017-01-31-07-28-15.txt](https://github.com/wireapp/wire-android/files/743872/wire-2017-01-31-07-28-15.txt)

**Comment by Paviluf** [comment] 2017-02-05 17:57
@xuanzhaopeng do you think it's because we don't have google services ?

**Comment by xuanzhaopeng** [comment] 2017-02-06 13:30
Hi @Paviluf thanks for your information. Could you please try again on latest build, to see whether you still could reproduce it? 

I try to reproduce on Android 6.0 on CM 13, without Goolge service,  but it works. I guess the issues is related to OutOfMemeory(CM 11 is on Android 4.4 I guess), but I don't see that in your attached log.  I have a similar issue for receving image, which could be the exception such as :
```
java.lang.Exception: Bitmap decoding failed, got empty bitmap for asset: 8e754fa3-2c2b-43af-ade0-23a9c4f2d575
     .... .....
```

If you still could reproduce it on latest build, please let me know and provide full log if possible, maybe with some screenshot will be helpful.

**Comment by Paviluf** [comment] 2017-02-06 20:48
The problem it still here with the latest build. Here is a log and a screenshot after a test with otto the bot that send me a picture:

[2017-02-06-21-41-36.txt](https://github.com/wireapp/wire-android/files/755808/2017-02-06-21-41-36.txt)
![screenshot_2017-02-06-21-41-48](https://cloud.githubusercontent.com/assets/17159065/22665690/f3ae13c4-ecb5-11e6-8f1f-2e33d4059888.png)

**Comment by Paviluf** [comment] 2017-02-11 10:14
Did that help ? Do you think fixing this bug will take long ?
Because for now the app is almost useless for us :D

Thanks !

**Comment by xuanzhaopeng** [comment] 2017-02-11 12:57
Hey, @Paviluf , thanks a lot for your information! Sorry for Inconvenient,  I will try to reproduce it again in Monday. I will make the priority of this ticket as highest as possible :)

I will let u know as soon as possible I get something new . 

Thanks again.

**Comment by xuanzhaopeng** [comment] 2017-02-13 11:15
@Paviluf Hey I cannot reproduce it, but I guess I know the reason. 

1) First of all, you don't have Google Play service, so you cannot recevie the message from GCM
2) So now you will recevie messages by our WebSocket
3) But your Websocket hand shake failed.

**Comment by Paviluf** [comment] 2017-02-13 13:02
I don't have access to atlassian but does that mean that you can fix it ?
Thanks !

**Comment by xuanzhaopeng** [comment] 2017-02-13 14:06
Hey @Paviluf,  could u please check:
Settings -> Security -> Trusted credentials 

that you already trust : DigiCert Inc (Root CA) and DigiCert Inc (Global Root CA)

Merci!

**Comment by Paviluf** [comment] 2017-02-13 14:38
It seem so
![screenshot_2017-02-13-15-36-13](https://cloud.githubusercontent.com/assets/17159065/22887452/6b2cdbb4-f202-11e6-979a-28f965f64484.png)

**Comment by darkbluelight** [comment] 2017-02-16 19:38
I have the same big problem since the last 2-3 releases. I as well can only see images that I send myself. I'm using Wire on Android, version 2.27.314.

I as well didn't install Google's apps and services and I'm using migroG instead. But since Wire supports Websocket, I didn't register Wire for migroG.

I use a custom 4.4.4 Android with kernel 3.4.67, strict SELinux status.

DigiCert Inc (Root CA) and DigiCert Inc (Global Root CA) are trusted as well.

Is Wire specifically in need for any Google stuff for it to show images? If yes, what are those?

**Comment by Paviluf** [comment] 2017-02-22 06:15
@xuanzhaopeng any news ? Do you need anything else ?

**Comment by xuanzhaopeng** [comment] 2017-02-23 13:28
Hey @Paviluf , thanks a lot for your patient! Good news is that today we reproduce this issue!

And we almost find the reason is that your device may don't support TLSv2, that means your devices maybe only could send TLSv1 request,  that is not acceptable by our backend. 

We are working on this issue now.  cc: @JPonte 

Thanks

**Comment by Paviluf** [comment] 2017-02-23 17:32
Ok thank you very much ! I hope that you guys will be able to fix this quickly now :)

**Comment by Paviluf** [comment] 2017-03-01 19:27
Is there any news ? Sorry to insist but I never be able to use the app and I really want to :)

**Comment by mykola-mokhnach** [comment] 2017-03-01 19:59
@Paviluf Unfortunately this cannot be fixed on our side. Wire provides the highest level of security possible, but your current platform does not support TLS version 1.2. You must either update to Android 5.0 or install Google Play services with TLS 1.2 support.

**Comment by Paviluf** [comment] 2017-03-01 20:17
Thanks for the update. Well I simply won't use Wire in this case... Let me explain, my phone, like a lot of phones, will never have anything newer than Android 4.4 and the point of using an app that respect my privacy is not to use Google Play Services that don't respect it.

Maybe you can make a fallback mode or integrate TLSv1.2 directly in Wire for those that don't have it ? It's too bad, I really like the app.

**Comment by mykola-mokhnach** [comment] 2017-03-01 20:21
We'll check with the backend whether it's possible to use fallback for cases like yours. Thanks for your patience.

**Comment by Paviluf** [comment] 2017-03-01 20:24
Thank you ! I really hope you will find a way.

**Comment by david-wire** [comment] 2017-03-06 10:04
@Paviluf Thanks for your patience. We have thoroughly looked into this but unfortunately we cannot come up with a fallback option that would solve your issue (for security related reasons - due to the aforementioned lack of support for TLS version 1.2 on your device). 
Apologies for the inconvenience.

**Comment by Paviluf** [comment] 2017-03-06 11:14
Ok I understand. Too bad there is no solution, because I like the app :(

**Comment by Paviluf** [comment] 2017-03-07 08:09
One thing that I don't understand is that messages, for instance, works. How could it be is since I don't have TLS 1.2 ?

**Comment by JPonte** [comment] 2017-03-07 14:14
Not all endpoints seem to have this restriction and since we intend to drop older versions of TLS on the long run, there is little interest on updating those to support it.

**Comment by Paviluf** [comment] 2017-03-07 16:54
@HazouPH build me a ROM with TLS 1.2 support but that didn't worked :(
It seem that a browser test without any gapps does indicate TLS 1.2 support.

https://forum.xda-developers.com/showpost.php?p=71306404&postcount=2184

Anyway is it possible to integrate TLS 1.2 in wire ?
Thanks !

**Comment by david-wire** [comment] 2017-03-20 12:59
@Paviluf as previously mentioned, there is no workaround for devices that run Android < 5.0 AND do not use Google Play Services. It will fall back to TLS 1.0. and we cannot provide a workaround.

**Closed by david-wire** 2017-03-20 12:59 UTC
Labels: bug

**Comment by Paviluf** [comment] 2017-03-20 19:21
No problem I use Signal now. It work perfectly :)

**Comment by cgruber** [comment] 2017-05-14 19:08
This doesn't track.  I have play services and am in modern Android (N) and have had this problem on a Samsung S8 and a Google Nexus 6p.  Same symptoms exactly. :/

**Comment by Paviluf** [comment] 2017-05-15 09:38
@david-wire by the way as I said here https://github.com/wireapp/wire-android/issues/518#issuecomment-284785273 I tested with a CM build that was built with TLS 1.2 support but that didn't worked. Maybe there is something else ?

**Comment by Paviluf** [comment] 2017-05-17 11:14
It seem that it's totally possible to use TLS 1.2 on phone with Android 4.1+

https://github.com/square/okhttp/issues/2372#issuecomment-244807676

**Comment by IronJunkie** [comment] 2017-05-21 08:45
@cgruber
same symptoms but I think you have a different problem, see https://github.com/wireapp/wire-android/issues/760

**Comment by IronJunkie** [comment] 2017-06-03 13:45
Images (only got a photo so far) downloading & showing properly now for me on todays Wire update from Play Store. (linageOS 14.1.2 gps ver 11. Xxx)

**Comment by IronJunkie** [comment] 2017-06-03 13:50
Sorry wrong thread, this does not fix your issue.
