### ISSUE TITLE
Unable to switch to dialogues during the call

### ISSUE THREAD

**Issue by kirusyaga** [wireapp/wire-android#1056] opened 2017-08-01 20:51 UTC
**Wire Version:** 2.38.352
**OS:** Android 7.1.2 Nougat
**Do you have an antivirus software installed:** no

**What steps will reproduce the problem?**
1. Start a call
2. Try to press "Back" button.

**What is the expected result?**
Open last dialogue. Call will continue in background.

**What happens instead?**
Unable to return to a dialogues and read and write messages during the call.

**Comment by someoneEsle** [comment] 2017-08-03 09:12
Hi! This is a duplicate of #829 so I'll close this for the moment. You can upvote #829 by reacting with the 👍 to show your support. Thanks!

**Closed by someoneEsle** 2017-08-03 09:12 UTC
Labels: enhancement
