### ISSUE TITLE
Notifications on 3.9.423

### ISSUE THREAD

**Issue by TubaOrNotTuba** [wireapp/wire-android#1503] opened 2018-03-26 13:41 UTC
Ok, this is getting frustrating and I'll try to be calm here, but does anyone at Wire test notifications before shipping a build of Wire for Android? In 3.9.423, notifications are all out of whack again.  If I'm in a conversation I DO NOT need it to chime and/or vibrate to tell me a new msg has arrive, I don't need the heads-up notification telling me a new message has arrive, and I do not need a notification try icon telling me a new message has arrived.

Please guys, I beg of you, spend a few minutes actually testing things like this.  It's beyond annoying and distracting to have all this unnecessarily busy notification stuff going on.  

I had a commercial customer really looking at Wire for their business and they dropped it from consideration after all the bugs.  It's really hard to promote a product where bug are constantly reintroduced.  Notifications was a huge problem last year, took forever to get right, now it's broken again.

**Comment by someoneEsle** [comment] 2018-03-26 14:00
What are your notification-related setting? I cannot reproduce on my phone. Also please always provide information regarding your phone model and operating system. Thanks!

**Comment by TubaOrNotTuba** [comment] 2018-03-26 14:30
Mine is LG V20, Android 7.0.0 (Verizon).  My settings have not changed in a year.  Sounds and vibrations are on, like they always have been.  There is no option to enable or disable the heads-up notification, though I want it to happen when I'm not in a chat.

**Comment by someoneEsle** [comment] 2018-03-26 14:57
How many accounts are you logged in with on Wire? 1 or 2?

**Comment by TubaOrNotTuba** [comment] 2018-03-26 15:03
1

**Comment by RITFW** [comment] 2018-04-04 05:27
I have to agree that the notifications are still a big issue. To the point that I'm not reliably reachable via Wire. The notifications work well as long as the app is open or was recently opened, but after a while the notification usually stop working.

I'm on LineageOS 14.1 (20180316) with an Samsung Galaxy S5 (KLTE) and Wire 3.8.412. I didn't install any GAPPS. I have the same settings for Conversations, Threema and Telegram and only experiencing unreliability with Wire.

Is there any priority on the notifications issue? As it seems to be stuck for a while.

**Comment by mattcoxonline** [comment] 2018-10-04 13:11
> I have to agree that the notifications are still a big issue. To the point that I'm not reliably reachable via Wire. The notifications work well as long as the app is open or was recently opened, but after a while the notification usually stop working.

Same here with my friends and I. People I message seem to get notifications sometimes, but not regularly. And I have experienced it myself; having no notifications until I open the app and then I get about 20 at once.

**Comment by hub-ch** [comment] 2019-02-24 11:03
https://github.com/wireapp/wire-android/issues/777#issuecomment-466763316

**Comment by marcoconti83** [comment] 2019-04-08 12:19
Hi all,
there are a lot of duplicated issues covering this same problem (or a very similar one), let's unify all conversations and keep it going here: #777 . Closing this one and continuing there.

**Closed by marcoconti83** 2019-04-08 12:19 UTC
