### ISSUE TITLE
Cannot block Otto the Bot

### ISSUE THREAD

**Issue by fortran77** [wireapp/wire-android#461] opened 2017-01-11 01:07 UTC
This issue is common to the Android (version 2.24.303) and web app (version 2016-12-13) implementations, and possibly to other implementations too.

Otto the Bot's replies to my questions did not answer my questions. To minimize clutter on the screen, I blocked Otto. Otto no longer appeared on my screen.

Then I invited other people to also install Wire. One of them (let's call him Bob) sent me a text message, and it came from both him and Otto. Presumably he included Otto in the conversation.

On my screen I saw:

BOB STARTED A CONVERSATION WITH OTTO AND YOU

And on the screen I saw the same type of irrelevant and unsolicited messages from the Otto the Bot for which I had previously blocked him. And yet, on this conversation screen, Otto's icon had the no entry image (similar to 🚫) superimposed on it, showing that he was still blocked.

So it appears that blocking Otto blocks him only locally, and other Ottos on other devices might still remain unblocked(?).

Ideally, once a user has blocked Otto, he should remain blocked on that user's screen, even if other people include him in their conversations.

(Edit: Typos/punctuation fixed.)

**Comment by mykola-mokhnach** [comment] 2017-02-26 18:29
This is by design that blocked users can still receive and send messages from/to the person who blocked them in group conversations. It is theoretically possible to just hide such messages in a group, but the conversation flow might look totally corrupted without seeing the whole messages chain.

And regarding Otto - we are currently working on a new fresh bots paradigm implementation, so this will be changed in the future anyway.

**Comment by makingthematrix** [comment] 2020-01-09 16:42
I think we can safely close this issue now - Otto won't start any conversation ever again ;)

**Closed by makingthematrix** 2020-01-09 16:42 UTC
Labels: question
