### ISSUE TITLE
feedback loop persisted after call ended

### ISSUE THREAD

**Issue by Be-ing** [wireapp/wire-android#308] opened 2016-11-14 07:19 UTC
I connected with my friend through Wire when we were in the same room with some quiet background music playing. I called her Motorola Droid Maxx with Wire to test Wire's call functionality. Our phones were close to each other, within a few inches. With the latency of the call, each phone picked up the other playing a sound that originated from the music, creating a continuous loop of beeping, like a delay effect. Strangely, her phone kept making that noise after the call was ended. I had to force quit Wire on her phone to get the beeping to stop. I tried to reproduce the issue, but Wire was not picking up any sounds on her phone after I started Wire again. I restarted her phone and tried again. The continuous loop of beeping occurred as expected, but I could not replicate the issue of her phone continuing to make that sound after ending the call.

**Comment by jspittka** [comment] 2016-11-14 14:59
Running 2 phones close to each other will result in a feedback loop similar to what often is experienced on stage when a microphone picks up the speaker signal. We have some safeguards in the software to suppress the annoying feedback sound, and in combination with the latency, this may sound as you described it. Still this is not a typical use-case and the resulting sound is expected. What is not expected is that the call seems to have continued on one of your devices after the call was hung up. The only explanation that I can see is that unfortunately something went wrong on that device and either the device and/or Wire stalled. Recording and playout loops run on a very high priority and therefore kept running while everything else became unresponsive. After restarting the device the audio system was reset and worked normally again. That would also explain why you were not able to reproduce the issue later. We apologize for the inconvenience and hope this will not happen again as we constantly improve our software.

**Comment by Be-ing** [comment] 2016-11-14 23:54
>while everything else became unresponsive

Everything else did not become unresponsive. Neither the Wire UI nor the Android UI froze.

**Comment by mykola-mokhnach** [comment] 2017-02-26 18:14
@Be-ing I'm closing the report for now. Feel free to reopen it if you observe the thing works wrong.

**Closed by mykola-mokhnach** 2017-02-26 18:15 UTC
