### ISSUE TITLE
Cant build client app

### ISSUE THREAD

**Issue by Tyriod** [wireapp/wire-android#583] opened 2017-02-07 18:10 UTC

**Comment by mykola-mokhnach** [comment] 2017-02-26 18:38
Please provide more details on the issue (screenshots, error logs, etc.). Otherwise we will not be able to help.

**Comment by ronidee** [comment] 2017-06-17 02:11
Although this issue is several months old already and Tyriod never responded, I wanna use this post to find some help while having the same problem (so I don't have to open another issue).

The following error occurs when I load the project: 
"Gradle sync failed: No such property: useAnt for class: org.gradle.api.tasks.scala.ScalaCompileOptions"

Thanks in advance for your help.

**Comment by marcoconti83** [comment] 2019-02-18 11:06
Closing this one as duplicate of #985 (Thanks @archivebase for spotting it!)

**Closed by marcoconti83** 2019-02-18 11:06 UTC
Labels: help wanted
