### ISSUE TITLE
Voice changer crash

### ISSUE THREAD

**Issue by leo-lb** [wireapp/wire-android#2290] opened 2019-09-14 20:17 UTC
On Wire 3.38.826, when I record audio then try to change voice with any of the filters, the application crashes.

**Comment by danila-io** [comment] 2019-09-15 21:21
The problem is also present on my friend's device HUAWEI COL-L29RU | COL-L29 | HONOR | HUAWEICOL-L29. App version is 826.

My friend's debug report: [wire_debug_report.txt](https://github.com/wireapp/wire-android/files/3614279/wire_debug_report.txt)

Same issue affects my device as well.

**Comment by marcoconti83** [comment] 2019-11-15 10:57
Hi all,
This fix has just been released to public with version 3.42. I'll close the issue, feel free to reopen if this is still a problem.

**Closed by marcoconti83** 2019-11-15 10:57 UTC
Labels: bug
