### ISSUE TITLE
SyncService hangs and requires restart to sync chat

### ISSUE THREAD

**Issue by iamtheoneaboveall** [wireapp/wire-android#1908] opened 2018-12-05 21:39 UTC
I'm using Wire without google play services and after some time SyncService hangs and chats don't get synced, i am using Wire on my PC to keep the chat going and open my phone just to see it's not synced up which requires me to use DisableService to kill SyncService that Wire registers and enable it again to force a sync of chats. I checked if any battery saving optimizations are applied to Wire app and i have disabled all of them in "Special Permissions" window in S8.

## Environment

* Wire version that exhibits the issue: 3.22.666
* Android OS version used to run Wire: 7 
* Is this a custom firmware or a stock one: Custom
* Mobile phone model/manufacturer: Galaxy S8
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE/Wi-Fi both show this problem

## Details
Run wire on a phone with removed/disable google play store/google play services framework

**Comment by m4rkusxxl** [comment] 2018-12-20 14:40
Same version, same problem. (Not rooted LineageOS 15.1 without any gapps.)
Solving it by regular force stop the app and restart it.

**Comment by m4rkusxxl** [comment] 2018-12-20 14:44
Same version, same problem. (Not rooted LineageOS 15.1 without any gapps.)
Solving it somehow by regular force stop the app and restart it. But thats no real solution.
Any idea how to help debug this?

**Comment by m4rkusxxl** [comment] 2018-12-24 08:33
Still open with 3.24.681.

**Comment by m4rkusxxl** [comment] 2019-01-29 13:04
Now with LineageOS 16.0. Still open with 3.26.694.

**Comment by GustavMarwin** [comment] 2019-02-09 14:25
Same here. Wish there is something I could do to get this resolved. Is that a resources / funding issue? Thank you.

**Comment by marcoconti83** [comment] 2019-02-11 12:48
Hi everyone,
thanks for reporting the issue. The problem should be related to not having google play services installed - can you confirm that you don't have google play services enabled?

**Comment by m4rkusxxl** [comment] 2019-02-11 18:18
Yes, I have no google play services installed. (Initial comment also states that.)

**Comment by m4rkusxxl** [comment] 2019-02-18 18:56
Anything we can do or help with?

**Comment by marcoconti83** [comment] 2019-02-19 12:24
We are in the process of enabling more logs on public builds, so that user can send us log to investigate issues that we can't reproduce on our side. Since logs might contain sensitive information, we are performing an audit of the logs logic to verify that the logs are reasonably anonymized and contain no sensitive information. Once this is done and deployed, we will ask you to send logs which will help us debug this issue.

**Comment by m4rkusxxl** [comment] 2019-03-16 13:17
Any ETA for this logging feature?

**Comment by marcoconti83** [comment] 2019-03-18 09:05
We are getting close, it was more complex than originally expected but it will most likely go out on the first week of April.

**Comment by marcoconti83** [comment] 2019-04-03 08:19
Hi everyone,
logs have been released to the public. 

This is how it works: before you can send logs, you need to enable logs recording. This is because we don't want to store this log file on your filesystem unless you decided to do it. As a consequence, you need to first enable logging, then reproduce your bug. If you do enable the logs after the bug has occurred, it will not contain the necessary information as nothing was recorded at that time.

To enable the logs, you can go to "Settings" -> "Advanced". You turn the logs on with the "Collect Usage Data" toggle. Once the logs are enabled, a log file is stored locally on your device. The log is not sent to Wire until you click on "Create debug report" in the same screen. When this happen, you are prompted to save/send the log file.

You can have a look at the log file yourself to make sure of what it contains; we have put an effort to anonymize most data via hashing. Once you are satisfied with the content, you can send it to our support (support@wire.com, and please mention the github ticket) or paste/link the content here, your choice.

**Comment by m4rkusxxl** [comment] 2019-04-04 13:27
I installed 3.30.764. Restarted the app and enabled the logging.
Then waiting until nothing more is received, i looked in the history of the specific user that wrote me. (See first log.)
Then I stopped wire (from app menu) and restarted it, the new message were there. (See second log.)
[wire_debug_report_1.log](https://github.com/wireapp/wire-android/files/3043642/wire_debug_report_1.log)
[wire_debug_report_2.log](https://github.com/wireapp/wire-android/files/3043643/wire_debug_report_2.log)

**Comment by marcoconti83** [comment] 2019-04-09 10:08
Hi @m4rkusxxl,
thanks for the logs, we are investigating further.

**Comment by m4rkusxxl** [comment] 2019-04-15 17:02
I just use IPv4 wifi.

Any more I can contribute to support?

**Comment by marcoconti83** [comment] 2019-04-16 08:52
Thanks everyone for the help, this has proven a very hard bug to reproduce on our side, we didn't manage yet. We will continue investigating.

**Comment by m4rkusxxl** [comment] 2019-05-04 18:15
Any news on this issue?

**Comment by rnd83** [comment] 2019-05-08 07:29
I created a new debug report with version 3.32.781. This time there is a lot more information.
I restarted the app and sent a message to it, which was received. Then i waited about 5 minutes and sent another message, which was not received. Then I opened the app - still no message - and stopped the log.
This time there is a crash in the log, so maybe that's more helpful.
[wire_debug_report.txt](https://github.com/wireapp/wire-android/files/3156031/wire_debug_report.txt)

**Comment by marcoconti83** [comment] 2019-05-08 16:02
Thanks @rnd83 ,
@CalumMcCall could you have a look at the crash reported in the log from @rnd83? Looks interesting.

**Comment by CalumMcCall** [comment] 2019-05-13 13:38
@rnd83 Thanks for sending the log, it's much appreciated! The crash you're having is caused by a lack of multidex support, this is unrelated to notifications, but it's surprising the App is working at all for you. Multidex is a method we use to split our app into multiple pieces to workaround a limitation with Android App sizes. For some reason multidex support isn't working on your device. We don't test with LineageOS devices, so perhaps there is something unusual on your configuration which is causing this. I had a look and it doesn't seem like multidex support is something you can normally disable, but I'm unsure. I've only seen this crash on internal, debug builds, and it's normally solved by doing a clean rebuild. Did you build Wire yourself from source?

**Comment by m4rkusxxl** [comment] 2019-05-14 10:06
You refer to this?
05-08 09:05:24.841 I/MultiDex( 6760): VM with version 2.1.0 has multidex support
05-08 09:05:24.841 I/MultiDex( 6760): Installing application
05-08 09:05:24.841 I/MultiDex( 6760): VM has multidex support, MultiDex support library is disabled.

Shouldnt this be normal for every android api>20? (Because since api 21 multidex is natively supported. So no "support lib" is needed.)

**Comment by CalumMcCall** [comment] 2019-05-15 15:37
You're right @m4rkusxxl, it appears this crash _is_ related to the notification issues we are having, and we are currently working on a fix. So please bear with us!

**Comment by rnd83** [comment] 2019-05-17 12:34
@CalumMcCall Probably not important anymore but no, I did not build from source. I used the version from the Play Store.

**Comment by 8FordPrefect8** [comment] 2019-07-17 11:14
Is there any update? After some issues I don't habe microG anymore and sadly observed that the bug is still persistent.

**Comment by 8FordPrefect8** [comment] 2019-07-20 09:32
Wire without Gapps is really not usable right now and since months. I got a response minutes after I send a message and got no notification. Killing the APP via settings and starting it hours later showed the message.

**Comment by marcoconti83** [comment] 2019-09-27 14:29
Hi all ,
thanks for the report. We just released a beta version that should fix an issue with missing messages while in the background. And even if this is not fixing your specific issue, this version has enhanced logging that will tell us what went wrong - so please try it out and let us know. If you still have the issue, we can probably figure out what's wrong with your phone from the logs.

We will probably release it to public beginning of next week, but you can give the beta version a try if you want to provide us some feedback. You can join the beta from the Play store page.

**Comment by marcoconti83** [comment] 2019-09-30 11:35
Hi all,
we released a fix to public just today. You can get it from the play store and from our website. I'll close the issue for now, please reopen if this is still an issue for you. Thanks!

**Closed by marcoconti83** 2019-09-30 11:35 UTC
Labels: bug, wait for logs
