### ISSUE TITLE
opening a conversation does not scroll to bottom

### ISSUE THREAD

**Issue by Be-ing** [wireapp/wire-android#313] opened 2016-11-14 22:54 UTC
When I view a conversation from my contacts list, it is scrolled up a little bit, which can hide the contents of the most recent message in the conversation. It's not always obvious that there is more recent content in the conversation that I am not seeing. This is on a Galaxy S5 Mini.

**Comment by someoneEsle** [comment] 2016-11-15 13:26
Duplicate of #112 and related to #191 .

**Comment by bjoernherbig** [comment] 2016-11-16 10:16
correct as stated by @someoneEsle . work in progress, closing it as duplicate

**Closed by bjoernherbig** 2016-11-16 10:16 UTC
