### ISSUE TITLE
Introduce @mentions

### ISSUE THREAD

**Issue by fllp** [wireapp/wire-android#1377] opened 2018-01-13 21:52 UTC
## The problem

In a group chat it can get busy at times. With a mention mechanism like the one used in IRC, one could e.g. answer to someones earlier message without interrupting the topic currently talked about.
Also, a @mention could be used to 'ping' one person only, instead of the whole group.

## Environment

* Wire version that exhibits the issue: 3.4.382 
* Last Wire version that did not exhibit the issue (if applicable): n/a
* Android OS version used to run Wire: 7.1.2
* Is this a custom firmware or a stock one: custom
* Mobile phone model/manufacturer: n/a
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): n/a

**Comment by someoneEsle** [comment] 2018-01-15 15:25
duplicate of #778 , you can upvote that issue :)

**Closed by someoneEsle** 2018-01-15 15:25 UTC

**Comment by fllp** [comment] 2018-01-15 15:27
Done :)
