### ISSUE TITLE
Double tapping space to add period on Gboard leaves period after space

### ISSUE THREAD

**Issue by Kommynct** [wireapp/wire-android#1425] opened 2018-02-21 23:58 UTC
This only happens in wire and I have no idea why. 
## Environment

* Wire version that exhibits the issue: latest from the play store
* Last Wire version that did not exhibit the issue (if applicable):two versions before the most recent. 
* Android OS version used to run Wire: lineageos 15.1
* Is this a custom firmware or a stock one: custom
* Mobile phone model/manufacturer: Nexus 6p from google

**Comment by someoneEsle** [comment] 2018-02-22 07:42
Please avoid using expressions like "latest from the play store" when specifying the version number, they are of no value to us. Also, this is a duplicate of #1328 -- feel free to reopen it if your wire version is more up-to-date than the ones mentioned there.

**Closed by someoneEsle** 2018-02-22 07:42 UTC
