### ISSUE TITLE
Sharing a picture or video from Google photos inserts it twice in the chat

### ISSUE THREAD

**Issue by DavyLandman** [wireapp/wire-android#1559] opened 2018-05-04 12:07 UTC
## The problem

Sharing a picture with wire (from Google photos) the picture is send twice. Similarly with a video. It's send twice. The receiver also sees it twice.

## Environment

* Wire version that exhibits the issue: 3.10.439
* Last Wire version that did not exhibit the issue (if applicable): the previous one
* Android OS version used to run Wire: Android 8.1
* Is this a custom firmware or a stock one: stock 
* Mobile phone model/manufacturer: pixel 2
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE

## Details

Take picture with stock camera, open stock gallery, share with wire, select contact, see the picture send twice.

**Comment by makingthematrix** [comment] 2020-01-29 15:33
Hi.
The assets and sharing functionality was rewritten since this issue was reported. I can't reproduce it anymore. I guess I can safely close this issue.

**Closed by makingthematrix** 2020-01-29 15:33 UTC
