### ISSUE TITLE
Wire looses messages received while offline

### ISSUE THREAD

**Issue by Larx** [wireapp/wire-android#1101] opened 2017-09-05 17:28 UTC
## The problem

Wire for Android seems to swallow messages received while offline (off or airplane mode). I had this several times the last few days, as I had to turn off the phone recently.
Using the application on my Linux desktop, I can see the lost messages (applies to calls also). I cannot make them be seen on the mobile phone.
As I use MicroG, I can see that Wire correctly receives GCM push notifications in the moment it goes online again. However, the messages received while offline are lost. No notification to the user, no message, nothing.

## Environment

* Wire version that exhibits the issue: 2.40.357
* Last Wire version that did not exhibit the issue (if applicable): don'tknow
* Android OS version used to run Wire: 7.1.2
* Is this a custom firmware or a stock one: LineageOS-based without Google services, but with MicroG
* Mobile phone model/manufacturer: Samsung S7
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): not applicable

**Comment by someoneEsle** [comment] 2017-09-06 06:56
Hi, thanks for reporting. This is a known bug that we are currently working on. It's a bit tricky but it should be fixed in an upcoming release!

**Comment by Larx** [comment] 2017-09-06 08:12
Plesse! Because of this and similar bugs, I begin to distrust Wire as a reliable means of communication. The sender of the lost message has the sent message marked as "received", but in reality the receiving side does not even know he/she has justed missed a message.

This is really, really bad for a communication service.

**Comment by someoneEsle** [comment] 2017-11-06 14:01
Hey @Larx, this issue should be fixed in an upcoming update that you will receive within the next couple of days (unless you're a beta tester and already have it). I'll close this issue for now, but feel free to reopen if it happens again!

**Closed by someoneEsle** 2017-11-06 14:01 UTC

**Comment by bruceleerabbit** [comment] 2022-03-01 09:07
I suffer from this quite serious bug on an Android 5.1 device.  F-droid only has 3 versions of Wire and all three versions are restricted to chronic upgraders who buy a new phone every year (app requires Android 7.0).

Where can the latest AOS 5.1-compatible apk file be downloaded from (outside of Google)?  And does that version contain the fix for this bug?

**Comment by embeddedt** [comment] 2022-03-02 13:42
> Where can the latest AOS 5.1-compatible apk file be downloaded from (outside of Google)? And does that version contain the fix for this bug?

https://github.com/wireapp/wire-android/releases/tag/3.53

I can confirm from personal testing that as of a couple weeks ago this version could still send/receive messages (though I did not test the issue reported here).

**Comment by bruceleerabbit** [comment] 2022-03-27 14:20
@embeddedt Thanks for the tip.  That link does not lead to an APK, so I suppose I would have to install an SDK and compile it myself, correct?

Although I suppose it apparently does not matter. I have to say it looks like the bug I’m experiencing is a different bug.  With my current version (which is indeed older than 3.53), messages sent while I was offline are coming through in general. As soon as I establish a connection in the morning, msgs that were sent throughout the night are delivered at that moment.

**Comment by bruceleerabbit** [comment] 2023-04-06 09:37
Now because of bug 3751 there is a dire need to get an APK for version 3.53.
